### PR TITLE
Match "https://" as well as "http://" for IRIS federator

### LINKED ISSUE #3126: IRIS federator routing client does not match https:// URLs — affects RASPISHAKE
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

I noticed that the `RoutingClient('iris-federator')` was never returning stations / data from the RASPISHAKE data center. Digging in, I found this line in the **federator** `_split_routing_response()` method: https://github.com/obspy/obspy/blob/9659cf3e4499fe15fa71bd0bd3a9600aca7f180e/obspy/clients/fdsn/routing/federator_routing_client.py#L167

Compare to this line in the **eidaws** `_split_routing_response()` method:
https://github.com/obspy/obspy/blob/9659cf3e4499fe15fa71bd0bd3a9600aca7f180e/obspy/clients/fdsn/routing/eidaws_routing_client.py#L195

Note the difference is that the **federator** ignores `https://` URLs. Well, RASPISHAKE's URL is `https://`, see [here](http://service.iris.edu/irisws/fedcatalog/1/query?net=AM&sta=RAF63&format=request&includeoverlaps=false&nodata=404):

> ```
> DATASELECTSERVICE=https://fdsnws.raspberryshakedata.com/fdsnws/dataselect/1/
> STATIONSERVICE=https://fdsnws.raspberryshakedata.com/fdsnws/station/1/
> ```

### Possible fix?

I imagine this is a quick fix, changing `"http://"` to `"http"` on line 167 to match how the **eidaws** URLs are handled. If this is indeed the case, I'm happy to make a PR.

### Code to Reproduce

```python
from obspy.clients.fdsn import Client, RoutingClient

kwargs = dict(network='AM', station='RAF63')

Client('RASPISHAKE').get_stations(**kwargs)  # GOOD: Returns Inventory with "Sending institution: SeisComP (RaspberryShake)"
RoutingClient('iris-federator').get_stations(**kwargs)  # BAD: Raises FDSNNoDataException, see attached error traceback
```

### Error Traceback

```Python traceback
---------------------------------------------------------------------------
FDSNNoDataException                       Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 RoutingClient('iris-federator').get_stations(**kwargs)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    230 if not kwsyntax:
    231     args, kw = fix(args, kw, sig)
--> 232 return caller(func, *(extras + args), **kw)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py:78, in _assert_filename_not_in_kwargs(f, *args, **kwargs)
     76 if "filename" in kwargs:
     77     raise ValueError("The `filename` argument is not supported")
---> 78 return f(*args, **kwargs)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/obspy/clients/fdsn/routing/federator_routing_client.py:105, in FederatorRoutingClient.get_stations(self, **kwargs)
     88 @_assert_filename_not_in_kwargs
     89 def get_stations(self, **kwargs):
     90     """
     91     Get stations from multiple data centers.
     92
   (...)
    103     for details.
    104     """
--> 105     return super(FederatorRoutingClient, self).get_stations(**kwargs)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    230 if not kwsyntax:
    231     args, kw = fix(args, kw, sig)
--> 232 return caller(func, *(extras + args), **kw)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py:78, in _assert_filename_not_in_kwargs(f, *args, **kwargs)
     76 if "filename" in kwargs:
     77     raise ValueError("The `filename` argument is not supported")
---> 78 return f(*args, **kwargs)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py:367, in BaseRoutingClient.get_stations(self, **kwargs)
    363 # Just pass these to the bulk request.
    364 bulk = [kwargs.pop(key, '*') for key in (
    365         "network", "station", "location", "channel", "starttime",
    366         "endtime")]
--> 367 return self.get_stations_bulk([bulk], **kwargs)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    230 if not kwsyntax:
    231     args, kw = fix(args, kw, sig)
--> 232 return caller(func, *(extras + args), **kw)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py:78, in _assert_filename_not_in_kwargs(f, *args, **kwargs)
     76 if "filename" in kwargs:
     77     raise ValueError("The `filename` argument is not supported")
---> 78 return f(*args, **kwargs)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/obspy/clients/fdsn/routing/federator_routing_client.py:142, in FederatorRoutingClient.get_stations_bulk(self, bulk, **kwargs)
    138 r = self._download(self._url + "/query", data=bulk_str)
    139 split = self._split_routing_response(
    140     r.content.decode() if hasattr(r.content, "decode") else r.content,
    141     service="station")
--> 142 return self._download_stations(split, **kwargs)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py:238, in BaseRoutingClient._download_stations(self, split, **kwargs)
    237 def _download_stations(self, split, **kwargs):
--> 238     return self._download_parallel(split, data_type="station", **kwargs)

File ~/miniconda3/envs/sonify/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py:245, in BaseRoutingClient._download_parallel(self, split, data_type, **kwargs)
    242 split = self._filter_requests(split)
    244 if not split:
--> 245     raise FDSNNoDataException(
    246         "Nothing remains to download after the provider "
    247         "inclusion/exclusion filters have been applied.")
    249 if data_type not in ["waveform", "station"]:  # pragma: no cover
    250     raise ValueError("Invalid data type.")

FDSNNoDataException: Nothing remains to download after the provider inclusion/exclusion filters have been applied.
```

### ObsPy Version?

1.3.0

### Operating System?

macOS

### Python Version?

3.9.12

### Installation Method?

conda

### PR DESCRIPTION
**Pull request by liamtoney**
### What does this PR do?

Allows for IRIS federator client to match URLs starting with `https://`

### Why was it initiated?  Any relevant Issues?

Fixes #3126 

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [x] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by liamtoney** [comment]
Let me know if I should update the `CHANGELOG.txt` — didn't know if it was warranted here or not.

**Comment by megies** [comment]
> Let me know if I should update the `CHANGELOG.txt` — didn't know if it was warranted here or not.

Yes, please, pretty much every change goes into the change log. Only exception being a bug getting fixed on master that was introduced after last release, i.e. not present in any released version.

**Comment by liamtoney** [comment]
Okay, I believe this is ready for review.

**Comment by megies** [comment]
Thanks for informing us about this bug and thanks for the PR! :rocket:

**Pull request merged**
