### PR TITLE
ImportError with custom plugin

### PR DESCRIPTION
**Pull request by trichter**
For illustration I use obspyh5 as custom plugin, but I guess it would be the same for other plugins.

Consider the following setup:

```
conda create -n test obspy h5py
conda activate test
pip install obspyh5
```

The following script is working:

```
import obspy
import obspyh5
```

The following script is not working in obspy master.

```
import obspyh5
```

```
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/workhorse/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2442, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'obspyh5' has no attribute 'readh5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import obspyh5
  File "/home/eule/dev/obspyh5/obspyh5.py", line 26, in <module>
    from obspy.core import Trace, Stream, UTCDateTime as UTC
  File "/home/eule/dev/obspy/obspy/__init__.py", line 59, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)
  File "/home/eule/dev/obspy/obspy/core/util/base.py", line 522, in make_format_plugin_table
    func = buffered_load_entry_point(*ep_list)
  File "/home/eule/dev/obspy/obspy/core/util/misc.py", line 644, in buffered_load_entry_point
    _ENTRY_POINT_CACHE[hash_str] = load_entry_point(dist, group, name)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/eule/anaconda/envs/workhorse/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/eule/anaconda/envs/workhorse/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2444, in resolve
    raise ImportError(str(exc))
ImportError: module 'obspyh5' has no attribute 'readh5'
```

@medlin01GA Thanks for spotting this mysterious bug.

### CODE REVIEW

**Comment by trichter** [comment]
+DOCS +DOC

**Comment by trichter** [comment]
I checked the 6 different plugin tables (Event, Inventory, Stream, read and write) in the documentation. All look good with working links.

**Comment by d-chambers** [comment]
Hey @trichter ,
 I just took a quick look at this. It seems like a good fix, but unfortunately our CI is a complete mess again... 

Anything else you want to do with it?

**Comment by ThomasLecocq** [comment]
aha, I noticed the same with obspy-dmx I wrote recently, good you found it !

**Comment by trichter** [comment]
@d-chambers No, nothing to do is left. I think it is ready to merge. And apart from fixing the `ImportError` it only affects the documentation, which I checked.

@ThomasLecocq One of the bugs which get triggered only under some rare circumstances.

**Comment by trichter** [comment]
I think this PR also reduces the import time of obspy somewhat.

**Comment by d-chambers** [comment]
Ok, I have looked over the CI runs as well as run a few tests locally and I feel ok about merging this.

However, I have uncovered one issue that is partially related. If someone tries to re-import obspy it fails because the `__doc__` strings have already been formatted when `obspy.__init__` is run again. For example, on python 3.7:

```python
import importlib

import obspy

importlib.reload(obspy)
```

raises a TypeError. 

I tried fixing it (just pushed here), do you mind taking a look at it. After that, it should be good to merge.

**Comment by trichter** [comment]
Thanks for running some tests and having a look.
Your changes look good.
I have some suggestions:
* be verbose and call the function `_add_format_plugin_table`
* move it to obspy.core.util.base
* Would something like this work, too?
```
def _add_format_plugin_table(func, group, method, numspaces=4):
    if '%s' in func.__doc__:
        func.__doc__ = func.__doc__ % make_format_plugin_table(
            group, method, numspaces=numspaces)
```

**Comment by d-chambers** [comment]
@trichter sure that works too. I should have time to make the changes early next week, or feel free to change how you see fit, then we will merge it.

**Comment by trichter** [comment]
@d-chambers Thanks, it is ready for merging now.

**Comment by d-chambers** [comment]
Ok, I ran one last set of tests on py27 and py37 and the failures are unrelated, merging.

**Pull request merged**
