### PR TITLE
Use subprocess.check_output instead of Popen.

### PR DESCRIPTION
**Pull request by QuLogic**
Less fiddling with stdout and stderr that way.

### CODE REVIEW

**Comment by megies** [comment]
Nice, didn't know / never used this `check_output` routine.. ah, new in 2.7, maybe that's why.

**Comment by megies** [comment]
Hmm, fails on appveyor though..

**Comment by QuLogic** [comment]
It seems that that failure always existed. It was just masked by the overly broad `except:` clause.

**Comment by megies** [comment]
> It seems that that failure always existed. It was just masked by the overly broad except: clause.

OK, even better then..

**Pull request merged**
