### PR TITLE
gh-actions: slightly verbose output for flake8

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Makes flake8 check print some slightly verbose information when linting code in CI / gh-actions.

### Why was it initiated?  Any relevant Issues?

Without that `-v` flag, the actual flake8 run shows no output at all if no linter doesn't find any problems, which can be confusing when looking at CI results because then "Successfully installed flake8" is the last thing that is shown in the CI log:

Screenshot from 2020-08-28 11-08-31

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by d-chambers** [comment]
I am not opposed to this but  now it may be too verbose. For example, I could see the following confusing a new contributor (especially the "found a total of x violations 0 reported" bit):

image

Alternatively, we could just test flake8's return code and echo "No flake8 violations found" if it is 0. We could also move the python installation to a prior step so the flake8 window only gives relevant information on code linting.

**Comment by QuLogic** [comment]
Maybe we can use reviewdog, like I added to Matplotlib? https://github.com/matplotlib/matplotlib/pull/17143

**Comment by megies** [comment]
Automated comments inline from flake8 check? Nice, I'm all for it

**Comment by d-chambers** [comment]
I haven't used reviewdog but from the documentation it looks good. I am ok with either cleaning up the linting job a bit or just using reviewdog.

**Comment by QuLogic** [comment]
So this is replaced by #2717, I think.

**Comment by megies** [comment]
Ok, sweet, thanks again @QuLogic!

**Pull request closed without merging**
