### PR TITLE
Travis Mac build reports miss version information

### PR DESCRIPTION
**Pull request by krischer**
screenshot from 2016-02-19 00 47 26

### CODE REVIEW

**Comment by krischer** [comment]
This is now a PR which raises a warning if the version number could not be determined. + An additional commit to "debug" the issue on travis.

**Comment by krischer** [comment]
I just restarted the travis run as I don't understand the error message and it now also fails on Linux which I understand even less...

**Comment by QuLogic** [comment]
Can you print out `os.environ`?

**Comment by megies** [comment]
Changed base branch to `maintenance_1.1.x`. Please ideally rebase on this base branch, eventually.

**Comment by megies** [comment]
Base branch will have to be changed either to `master` or to `maintenance_1.2.x` once 1.2.0 is released.

**Comment by megies** [comment]
what's travis?

**Comment by trichter** [comment]
> what's travis?

:smile: 

But maybe we could keep the warning (not the print outs) at the end?

**Comment by megies** [comment]
> But maybe we could keep the warning (not the print outs) at the end?

I didn't even check what the ticket was about exactly :rofl: 
Yea, sounds good

**Comment by megies** [comment]
pushed it onto maintenance directly

**Pull request closed without merging**
