### PR TITLE
Events without origin depths cause catalog plots to fail

### PR DESCRIPTION
**Pull request by megies**
~~Fair warning, this catalog is 3645 events long and takes a few minutes to download. I will try to cut it down at some point, but it illustrates the point for now:~~

```python
from obspy import UTCDateTime
from obspy.fdsn import Client

client = Client("IRIS")
starttime = UTCDateTime("2000-06-06T00:00:00")
endtime = UTCDateTime("2014-12-31T00:00:00")

# catalog = client.get_events(starttime=starttime, endtime=endtime,
#                             minmagnitude=5.5, maxmagnitude=6.0, magnitudetype='Mw',
#                             latitude=63.099203, longitude=-149.483061,
#                             minradius=30, maxradius=95)
catalog = client.get_events(eventid=1090422)
catalog.plot()
```
results in:
```python
TypeError                                 Traceback (most recent call last)
/usr/lib64/python3.4/site-packages/obspy/core/util/decorator.py in
echo_func(*args, **kwargs)
     77                         kwargs[nkw] = kwargs[kw]
     78                     del(kwargs[kw])
---> 79             return func(*args, **kwargs)
     80         return echo_func
     81 

/usr/lib64/python3.4/site-packages/obspy/core/event.py in
plot(self, projection, resolution, continent_fill_color, water_fill_color, label,
     color, colormap, show, outfile, **kwargs)
   3333                 c_ = event.origins[0].get('time')
   3334             else:
-> 3335                 c_ = event.origins[0].get('depth') / 1e3
   3336             colors.append(c_)
   3337 

TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

It can be worked around by doing `catalog.plot(color='date')`, but of course, it's not the same plot.

### CODE REVIEW

**Comment by megies** [comment]
For testing:
```python
from obspy import readEvents

catalog = readEvents()
catalog[0].origins[0].time = None
catalog[0].origins[0].depth = None
catalog.plot(color="depth")
catalog.plot(color="date")
```

**Comment by QuLogic** [comment]
Oops, didn't realize you made a PR out of it. I think this will pass now...

**Comment by megies** [comment]
> Oops, didn't realize you made a PR out of it. I think this will pass now...

Hijacked your ticket.. ;-)
Thanks for the fix.

**Comment by QuLogic** [comment]
FYI, @XStargate.

**Pull request merged**
