### PR TITLE
Licensing clean up

### PR DESCRIPTION
**Pull request by megies**
This is to keep track of all licensing details discussed in #824. The following list keeps track of anything that is currently not LGPLv3.

 - [x] replacing libtau with obspy/taupy ~~**libtau** (no license at all? consent to relicense by B. Kennett, see https://github.com/obspy/obspy/blob/master/obspy/taup/LICENSE.txt)~~
    - [ ] ~~license for `obspy.taup` needs to be clarified in https://github.com/obspy/obspy/blob/master/obspy/taup/README.txt~~
    - [ ] ~~include as is in `obspy.taup` under LGPLv3?~~
 - [x] **evalresp** (no license information at all?)
    - [x] contacted Ilya Dricker and Eric Thomas (both ISTI) - tjm@iris ... does not exists anymore
       - Ilya gave his Ok
    - [x] contacted Robert Casey (IRIS)
    - [x] got feedback from Robert Casey and Tim Ahern (IRIS)
    - [x] evalresp contains evr_spline.c which comes from GNU plotutils and that is GPL. evr_spline is based on #892 on a LGPL SPLINE library --- needs merge.
    - [x] include as is in `obspy.signal` under LGPLv3?
 - [x] **obspy.imaging** (reason was GMT beachball script)
    - [x] [GMT now LGPLv3](https://github.com/obspy/obspy/issues/824#issuecomment-46743006)
    - [x] [all authors of matlab script consented to LGPLv3 for derived python script](https://github.com/obspy/obspy/issues/824#issuecomment-46743006)
    - [x] make everything in `obspy.imaging` LGPLv3
 - [x] **obspy.earthworm**
    - [x] [contacted V. Kress](https://github.com/obspy/obspy/issues/824#issuecomment-46743006)
    - [x] wait for reply
    - [x] relicense under LGPLv3?
 - [x] **GSE_UTI** (`obspy.gse2`) (no license information at all?!)
    - [x] contacted S. Stange about licensing issues
    - [x] got OK for LGPL

Anything I missed?

Finally, if everything is clear..
 - [x] move LGPLv3 license information to `obspy` top level package folder?

### CODE REVIEW

**Comment by megies** [comment]
Can be merged after removal of `obspy.taup` and replacement with `obspy/taupy`.

**Comment by QuLogic** [comment]
BTW, I heard this on the iris page, but you need both GPL and LGPL license texts since LGPLv3 is an extension of GPLv3.

**Comment by krischer** [comment]
Also written down here: https://www.gnu.org/licenses/gpl-howto.html

So we should probably do that.

**Comment by krischer** [comment]
Done in 66985a33bf2f35188a721e7deb8f9d673c6191db. Does this also mean we can remove the license files in all submodules? I think so.

**Comment by megies** [comment]
> Done in 66985a3

This should have been done in and now is conflicting with this PR.. :P Anyway, not a big thing to fix.

> Does this also mean we can remove the license files in all submodules? I think so.

Already done in this PR.

**Pull request merged**
