### PR TITLE
Fix beach pdf output when Axes instance is provided to plot into

### LINKED ISSUE #2887: Bugs when saving plotted beachballs to .pdf or .eps figures
https://github.com/obspy/obspy/blob/477659fe6fc940b87a2ffee09a47e6b34438bdf4/obspy/imaging/beachball.py#L167

I encountered a bug in plotting beachballs for source mechanisms. Specifically, when calling the functions `beach(...)` in `obspy/imaging/mopad_wrapper.py` or `obspy/imaging/beachball.py` with the arguments `axes` not equals `None`, there is always an error if save the plotted beachballs into vector files (e.g., .pdf or .eps).

To locate the error/bug, I found that the functions `beach(...)` calls the function
`matplotlib.transforms.IdentityTransform()` to create a Transform object. However, the
created object does not have the method `translate(...)` that is essential for saving
plots into vector files.

To fix the bug, it is simple by using the function `matplotlib.transforms.Affine2D(np.identity(3))`
instead of `matplotlib.transforms.IdentityTransform()` to create the Transform object.
The object created by the former has the method `translate(...)` and hence allows for
saving into vector files, while the object created by the latter does not.
Except for this difference, the objects created by the two functions have the same behaviors.

I have fixed the bug in my fork. The commit is my fork is here.
https://github.com/sheng09/obspy/commit/ac85a77e317f76ff4fd68505a18656c5d41a6e34
The fixing is very simple so that I revise in the master branch. Therefore, I simply raise the issue here instead of
newing a pull request. But I can new a PR if you think it is ok.

Below is an example for saving beachball plots into .pdf file. Without the fix, errors always happen. With the fix, errors disappear.

```python3
import matplotlib.pyplot as plt
import obspy.imaging.beachball as beachball

fig = plt.figure(figsize=(18, 5.5) )
ax = fig.add_subplot(111, aspect='equal')

bb = beachball.beach((0, 45, 90), facecolor='k', width=30, axes=ax, xy=(0, 0) )
ax.add_collection(bb)

plt.savefig('test.pdf')
```

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

This commit is a bug fix, which corrects a bug in the obspy/imaging/…beachball functions.

Specifically, when calling the functions beach(...) in obspy/imaging/mopad_wrapper.py or obspy/imaging/beachball.py with the arguments axes not equals None, there is always an error if save the plotted beachballs into vector files (e.g., .pdf or .eps).

To locate the error/bug, I found that the functions beach(...) calls the function matplotlib.transforms.IdentityTransform() to create a Transform object. However the created object does not have the method translate(...) that is essential for saving plots into vector files.

To fix the bug, it is simple by using the function matplotlib.transforms.Affine2D(np.identity(3)) instead of matplotlib.transforms.IdentityTransform() to create the Transform object. The object created by the former has the method translate(...) and hence allows for saving into vector files, while the object created by the latter does not. Excep this difference, the objects created by the two functions have the same behaviours.

### Why was it initiated?  Any relevant Issues?

fixes #2887 and supersedes #3241 

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [ ] All tests still pass.
- [x] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] New modules, add the module to `CODEOWNERS` with your github handle
- [x] Add the `ready for review` tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
@d-chambers @trichter I added a means to set a custom filetype for plots in pytest. I had to look up how to do it and it seems [pytest docs promote using a marker to get data into a fixture](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#using-markers-to-pass-data-to-fixtures). Let me know if you know a better/smarter/more elegant way to do this.

**Comment by megies** [comment]
@sheng09 would you mind getting added to our contributors list? Don't want to force it on people without asking.. but you earned the honors :wink:

**Review by trichter — APPROVED** [review]
Looks sensible!

**Comment by sheng09** [comment]
> 



> @sheng09 would you mind getting added to our contributors list? Don't want to force it on people without asking.. but you earned the honors 😉

@megies, thanks, and I would love to! I am an obspy user and happy to contribute :)
Sorry for my late replay. Was lost around Christmas and new year until recently...

**Comment by megies** [comment]
No worries, and done! :smiley:

**Pull request merged**
