### PR TITLE
Remove deprecated xcorr function

### PR DESCRIPTION
**Pull request by trichter**
This PR removes the old xcorr function which became obsolete with #1585.

Edit: I just realized, that in the mentioned PR it was suggested to wait with the complete removal of xcorr until version 2.0. So maybe wait a bit more before merging this PR ... didn't want to rush.

### CODE REVIEW

**Comment by krischer** [comment]
Yea - I would also wait a bit longer - no harm in leaving the old version around for a bit longer as I'm sure lots of codes use it. Especially given that we want to increase our release frequency.

**Comment by trichter** [comment]
I guess it is OK to remove `xcorr()` in version 2.0?

**Comment by krischer** [comment]
> I guess it is OK to remove `xcorr()` in version 2.0?

Yea should be okay - as long as we clearly document the migration path but that is easy in this case.

**Comment by trichter** [comment]
I rebased this branch on latest master and updated it accordingly. Should be ready for merging?

**Comment by trichter** [comment]
Rebased again on latest master.

**Comment by heavelock** [comment]
I guess it's good to go. This was already agreed to be deleted in 2.0 and it was mentioned as deprecated. 

Or maybe, it would be a good place to start a document `Migration manual` or something similar indicating what could break after update and how to fix it?

**Comment by trichter** [comment]
I agree ;)

IMHO, the what's new document (or similar) could be created shortly before the actual release from the changelog file.

**Comment by heavelock** [comment]
If this would be a personal project of mine, I would not trust myself to leave it for later :P Anyway, merge it in if you feel like that.

**Review by heavelock — APPROVED** [review]

**Comment by megies** [comment]
I agree that usually for most changes its OK to just look up things from the Changelog at time of release when putting the "What's New" together but in these cases were people need to know how to change code I would propose to put it now already in a draft for the "Whats New". At least if I were to do the whats new, I wouldnt want to spend time looking up how to migrate code for this one.

**Comment by trichter** [comment]
OK, agreed and done! I am merging...

**Pull request merged**
