### PR TITLE
Deprecation+Reroute needed for many renamed functions

### PR DESCRIPTION
**Pull request by megies**
After merging #999, many renamed functions still lack Deprecation+Reroute like done here: https://github.com/obspy/obspy/commit/9c98852b4c53498c777f6768ddfae8387e95e408#diff-4fe4cf25e2fb8e2572239cc976936717R1613

### CODE REVIEW

**Comment by megies** [comment]
Ok, so here's a proposal how to handle this: Inject one deprecated function with old name calling the new function, and do this in a centralized place.

@krischer, I'm not 100% happy with renames like 'writeJSON' -> '_write_json'.. shouldn't these abbreviation-like format names etc. stay uppercase (i.e. `_write_JSON`)?

**Comment by megies** [comment]
The file type checker for GSE2 is defined twice, once in gse2/core.py and once in gse2/libgse2.py, one time private, one time public.. needs fixing

**Comment by megies** [comment]
I think we need to go through naming again, or best, first fix naming rules once and for all..

e.g. `compare_SEED` or `format_RESP` vs. `_is_gse1` etc.

**Comment by megies** [comment]
I tested the import rerouting (based on [this list of exposed import of 0.10.2](https://gist.github.com/megies/d4376661bb29471274ca#file-obspy_check_objects__public_important-uniq-condensed-txt)), using [this bash script](https://gist.github.com/megies/c0391471a015e809f308) and [this python snippet](https://gist.github.com/megies/ccfb499eafdef14c22e1).. here's current results:
```
OK:   is_AH from obspy.ah.core
OK:   read_AH1 from obspy.ah.core
OK:   read_AH2 from obspy.ah.core
OK:   read_AH from obspy.ah.core
OK:   write_CNV from obspy.cnv.core
OK:   frombuffer from obspy.core.compatibility
OK:   readEvents from obspy.core.event
OK:   writeJSON from obspy.core.json
OK:   writeJSON from obspy.core.json.core
OK:   isQuakeML from obspy.core.quakeml
OK:   Pickler from obspy.core.quakeml
OK:   readQuakeML from obspy.core.quakeml
OK:   readSeisHubEventXML from obspy.core.quakeml
OK:   Unpickler from obspy.core.quakeml
OK:   writeQuakeML from obspy.core.quakeml
OK:   isPickle from obspy.core.stream
OK:   readPickle from obspy.core.stream
OK:   writePickle from obspy.core.stream
OK:   complexifyString from obspy.core.util
OK:   createEmptyDataChunk from obspy.core.util
FAIL: deprecated from obspy.core.util   ()
FAIL: deprecated_keywords from obspy.core.util   ()
OK:   getExampleFile from obspy.core.util
OK:   getScriptDirName from obspy.core.util
OK:   guessDelta from obspy.core.util
OK:   scoreatpercentile from obspy.core.util
FAIL: skip from obspy.core.util   ()
FAIL: skipIf from obspy.core.util   ()
OK:   toIntOrZero from obspy.core.util
OK:   uncompressFile from obspy.core.util
FAIL: createEmptyDataChunk from obspy.core.util.base   ('module' object has no attribute 'createEmptyDataChunk')
FAIL: getBasemapVersion from obspy.core.util.base   ('module' object has no attribute 'getBasemapVersion')
FAIL: getExampleFile from obspy.core.util.base   ('module' object has no attribute 'getExampleFile')
FAIL: getMatplotlibVersion from obspy.core.util.base   ('module' object has no attribute 'getMatplotlibVersion')
FAIL: getSciPyVersion from obspy.core.util.base   ('module' object has no attribute 'getSciPyVersion')
FAIL: getScriptDirName from obspy.core.util.base   ('module' object has no attribute 'getScriptDirName')
FAIL: toIntOrZero from obspy.core.util.base   ('module' object has no attribute 'toIntOrZero')
FAIL: getExampleFile from obspy.core.util.decorator   ('module' object has no attribute 'getExampleFile')
FAIL: raiseIfMasked from obspy.core.util.decorator   ('module' object has no attribute 'raiseIfMasked')
FAIL: skip from obspy.core.util.decorator   ('module' object has no attribute 'skip')
FAIL: skipIf from obspy.core.util.decorator   ('module' object has no attribute 'skipIf')
FAIL: skipIfNoData from obspy.core.util.decorator   ('module' object has no attribute 'skipIfNoData')
FAIL: uncompressFile from obspy.core.util.decorator   ('module' object has no attribute 'uncompressFile')
FAIL: complexifyString from obspy.core.util.misc   ('module' object has no attribute 'complexifyString')
FAIL: flatnotmaskedContiguous from obspy.core.util.misc   ('module' object has no attribute 'flatnotmaskedContiguous')
FAIL: guessDelta from obspy.core.util.misc   ('module' object has no attribute 'guessDelta')
FAIL: scoreatpercentile from obspy.core.util.misc   ('module' object has no attribute 'scoreatpercentile')
FAIL: toIntOrZero from obspy.core.util.misc   ('module' object has no attribute 'toIntOrZero')
OK:   isCSS from obspy.css.core
OK:   readCSS from obspy.css.core
OK:   writeCSS from obspy.css.station
OK:   isDATAMARK from obspy.datamark.core
OK:   readDATAMARK from obspy.datamark.core
OK:   mergePreviews from obspy.db.client
OK:   createPreview from obspy.db.indexer
OK:   parseMappingData from obspy.db.util
FAIL: getMenu from obspy.earthworm.client   ('module' object has no attribute 'getMenu')
FAIL: readWaveServerV from obspy.earthworm.client   ('module' object has no attribute 'readWaveServerV')
OK:   getMenu from obspy.earthworm.waveserver
OK:   getNumpyType from obspy.earthworm.waveserver
OK:   getSockBytes from obspy.earthworm.waveserver
OK:   getSockCharLine from obspy.earthworm.waveserver
OK:   readWaveServerV from obspy.earthworm.waveserver
OK:   sendSockReq from obspy.earthworm.waveserver
OK:   tracebuf2 from obspy.earthworm.waveserver
OK:   tracebufs2obspyStream from obspy.earthworm.waveserver
OK:   isGSE1 from obspy.gse2.core
OK:   isGSE2 from obspy.gse2.core
OK:   readGSE1 from obspy.gse2.core
OK:   readGSE2 from obspy.gse2.core
OK:   writeGSE2 from obspy.gse2.core
OK:   readHeader from obspy.gse2.libgse1
OK:   readIntegerData from obspy.gse2.libgse1
FAIL: verifyChecksum from obspy.gse2.libgse1   ()
OK:   isGse2 from obspy.gse2.libgse2
OK:   readHeader from obspy.gse2.libgse2
OK:   verifyChecksum from obspy.gse2.libgse2
OK:   writeHeader from obspy.gse2.libgse2
OK:   readPaz from obspy.gse2.paz
OK:   MT2Axes from obspy.imaging.beachball
OK:   MT2Plane from obspy.imaging.beachball
OK:   plotDC from obspy.imaging.beachball
OK:   plotMT from obspy.imaging.beachball
OK:   Pol2Cart from obspy.imaging.beachball
OK:   StrikeDip from obspy.imaging.beachball
OK:   TDL from obspy.imaging.beachball
OK:   isMSEED from obspy.mseed.core
OK:   readMSEED from obspy.mseed.core
OK:   writeMSEED from obspy.mseed.core
OK:   is_ndk from obspy.ndk.core
OK:   read_ndk from obspy.ndk.core
OK:   getProperty from obspy.neic.util
OK:   isPDAS from obspy.pdas
OK:   readPDAS from obspy.pdas
OK:   isPDAS from obspy.pdas.core
OK:   readPDAS from obspy.pdas.core
OK:   isMchedr from obspy.pde.mchedr
OK:   readMchedr from obspy.pde.mchedr
FAIL: SacIO from obspy.sac   ('module' object has no attribute 'SacIO')
OK:   isSAC from obspy.sac.core
OK:   isSACXY from obspy.sac.core
OK:   readSAC from obspy.sac.core
OK:   readSACXY from obspy.sac.core
FAIL: SacIO from obspy.sac.core   ()
OK:   writeSAC from obspy.sac.core
OK:   writeSACXY from obspy.sac.core
OK:   write_SACPZ from obspy.sac.sacpz
OK:   isSEG2 from obspy.seg2.seg2
OK:   readSEG2 from obspy.seg2.seg2
OK:   isSEGY from obspy.segy.core
OK:   isSU from obspy.segy.core
OK:   readSEGY from obspy.segy.core
OK:   readSEGYrev1 from obspy.segy.core
OK:   readSUFile from obspy.segy.core
OK:   readSU from obspy.segy.core
OK:   writeSEGY from obspy.segy.core
OK:   writeSU from obspy.segy.core
OK:   readSEGY from obspy.segy.segy
OK:   readSU from obspy.segy.segy
OK:   isSEISAN from obspy.seisan.core
OK:   readSEISAN from obspy.seisan.core
OK:   fromUTCDateTime from obspy.sh.core
OK:   isASC from obspy.sh.core
OK:   isQ from obspy.sh.core
OK:   readASC from obspy.sh.core
OK:   readQ from obspy.sh.core
OK:   writeASC from obspy.sh.core
OK:   writeQ from obspy.sh.core
OK:   arPick from obspy.signal
OK:   bandpass from obspy.signal
OK:   bandstop from obspy.signal
OK:   bwith from obspy.signal
OK:   carlSTATrig from obspy.signal
OK:   centroid from obspy.signal
OK:   cfrequency from obspy.signal
OK:   classicSTALTA from obspy.signal
OK:   classicSTALTAPy from obspy.signal
OK:   coincidenceTrigger from obspy.signal
OK:   cornFreq2Paz from obspy.signal
OK:   cosTaper from obspy.signal
OK:   delayedSTALTA from obspy.signal
OK:   domperiod from obspy.signal
OK:   eigval from obspy.signal
OK:   envelope from obspy.signal
OK:   estimateMagnitude from obspy.signal
OK:   highpass from obspy.signal
OK:   instBwith from obspy.signal
OK:   instFreq from obspy.signal
OK:   integerDecimation from obspy.signal
OK:   konnoOhmachiSmoothing from obspy.signal
OK:   logcep from obspy.signal
FAIL: lowpassFIR from obspy.signal   ()
OK:   lowpass from obspy.signal
OK:   normEnvelope from obspy.signal
OK:   pazToFreqResp from obspy.signal
OK:   pkBaer from obspy.signal
OK:   psd from obspy.signal
OK:   recSTALTA from obspy.signal
OK:   recSTALTAPy from obspy.signal
FAIL: remezFIR from obspy.signal   ()
FAIL: rotate_LQT_ZNE from obspy.signal   ()
FAIL: rotate_NE_RT from obspy.signal   ()
FAIL: rotate_RT_NE from obspy.signal   ()
FAIL: rotate_ZNE_LQT from obspy.signal   ()
OK:   seisSim from obspy.signal
OK:   sonogram from obspy.signal
OK:   specInv from obspy.signal
OK:   triggerOnset from obspy.signal
OK:   utlGeoKm from obspy.signal
OK:   utlLonLat from obspy.signal
FAIL: xcorr_3C from obspy.signal   ()
OK:   xcorr from obspy.signal
OK:   xcorrPickCorrection from obspy.signal
OK:   zDetect from obspy.signal
OK:   relcalstack from obspy.signal.calibration
OK:   instBwith from obspy.signal.cpxtrace
OK:   instFreq from obspy.signal.cpxtrace
OK:   normEnvelope from obspy.signal.cpxtrace
OK:   xcorrPickCorrection from obspy.signal.cross_correlation
OK:   bwith from obspy.signal.freqattributes
OK:   cfrequency from obspy.signal.freqattributes
OK:   cfrequency_unwindowed from obspy.signal.freqattributes
OK:   domperiod from obspy.signal.freqattributes
OK:   logbankm from obspy.signal.freqattributes
OK:   logcep from obspy.signal.freqattributes
OK:   mper from obspy.signal.freqattributes
OK:   pgm from obspy.signal.freqattributes
FAIL: seisSim from obspy.signal.freqattributes   ()
OK:   calculateSmoothingMatrix from obspy.signal.konnoohmachismoothing
OK:   konnoOhmachiSmoothing from obspy.signal.konnoohmachismoothing
OK:   konnoOhmachiSmoothingWindow from obspy.signal.konnoohmachismoothing
OK:   arPick from obspy.signal.trigger
OK:   carlSTATrig from obspy.signal.trigger
OK:   classicSTALTA from obspy.signal.trigger
OK:   classicSTALTAPy from obspy.signal.trigger
OK:   coincidenceTrigger from obspy.signal.trigger
OK:   delayedSTALTA from obspy.signal.trigger
OK:   pkBaer from obspy.signal.trigger
OK:   plotTrigger from obspy.signal.trigger
OK:   recSTALTA from obspy.signal.trigger
OK:   recSTALTAPy from obspy.signal.trigger
OK:   triggerOnset from obspy.signal.trigger
OK:   zDetect from obspy.signal.trigger
OK:   nearestPow2 from obspy.signal.util
OK:   prevpow2 from obspy.signal.util
FAIL: stationxml from obspy.station   ('module' object has no attribute 'stationxml')
FAIL: Angle from obspy.station.stationxml   ()
FAIL: Azimuth from obspy.station.stationxml   ()
FAIL: ClockDrift from obspy.station.stationxml   ()
FAIL: CoefficientsTypeResponseStage from obspy.station.stationxml   ()
FAIL: CoefficientWithUncertainties from obspy.station.stationxml   ()
FAIL: ComplexWithUncertainties from obspy.station.stationxml   ()
FAIL: Dip from obspy.station.stationxml   ()
FAIL: Distance from obspy.station.stationxml   ()
FAIL: FilterCoefficient from obspy.station.stationxml   ()
FAIL: FIRResponseStage from obspy.station.stationxml   ()
FAIL: FloatWithUncertaintiesAndUnit from obspy.station.stationxml   ()
FAIL: Frequency from obspy.station.stationxml   ()
OK:   is_StationXML from obspy.station.stationxml
FAIL: Latitude from obspy.station.stationxml   ()
FAIL: Longitude from obspy.station.stationxml   ()
FAIL: PolesZerosResponseStage from obspy.station.stationxml   ()
FAIL: PolynomialResponseStage from obspy.station.stationxml   ()
OK:   read_StationXML from obspy.station.stationxml
FAIL: ResponseListResponseStage from obspy.station.stationxml   ()
FAIL: ResponseStage from obspy.station.stationxml   ()
FAIL: SampleRate from obspy.station.stationxml   ()
FAIL: validate_StationXML from obspy.station.stationxml   ()
OK:   write_StationXML from obspy.station.stationxml
OK:   isWAV from obspy.wav.core
OK:   readWAV from obspy.wav.core
OK:   writeWAV from obspy.wav.core
OK:   Blockette34Lookup from obspy.xseed.utils
OK:   compareSEED from obspy.xseed.utils
OK:   DateTime2String from obspy.xseed.utils
OK:   formatRESP from obspy.xseed.utils
OK:   getXPath from obspy.xseed.utils
OK:   LookupCode from obspy.xseed.utils
OK:   setXPath from obspy.xseed.utils
OK:   toString from obspy.xseed.utils
OK:   toTag from obspy.xseed.utils
OK:   uniqueList from obspy.xseed.utils
OK:   isY from obspy.y.core
OK:   readY from obspy.y.core
OK:   isZmap from obspy.zmap.core
OK:   readZmap from obspy.zmap.core
OK:   writeZmap from obspy.zmap.core
```

**Comment by krischer** [comment]
That looks pretty good. I already fixed a couple of these and forgot to push it. We don't reroute most things from `obspy.core.util` as its mostly internal things and a pain to reroute.

Others like `verifyChecksum` are not valid as they are actually imports from other files and I don't think we have to reroute these.

Here is a modified script that tests all imports: https://gist.github.com/krischer/c71f1e7ac302f00e3490
Its a cleaned up version of all possible imports from 0.10.2.

**Comment by krischer** [comment]
I would like to merge this ASAP as its really big and touches almost every file. It should be easier to rebase other PRs on top of this as vice versa.

I'm not sure if anyone feels to thoroughly reviews this branch, so here are a the things it does:

* Restores all (relevant) imports that were possible in `0.10.2` with a mix of dynamic import hackery and plain deprecation helper functions. I consider [this](https://gist.github.com/krischer/c71f1e7ac302f00e3490) to be the authoritative test for that behavior. Can some others please test on their systems?
* Passes `flake8` with the `pep8-naming` plug-in installed. Its a fairly big change in some parts of our code base but now is the right time to do this and we do gain in the long run.
* Added `pep8-naming` to travis so we don't run into this again.
* Cleaned up `obspy-runtests` output - no more underflow and other warnings and weird printed text.
* More useful message in `obspy-runtests` if a module could not be tested.
* `obspy-runtests` was missing a couple of modules.
* MiniSEED errors and warnings are now raised in the correct context and can thus be caught.
* A couple of other small things.

**Comment by megies** [comment]
I agree, @krischer, @QuLogic, we should not merge anything until after this one is merged. :+1:

**Comment by QuLogic** [comment]
I will trust that the listing you have is correct. However, I'm not sure why you have listed several modules from the standard library?

It's too bad the TauP models had to be regenerated another time.

**Comment by QuLogic** [comment]
Here's a list of standard library packages I could find, if you wish to remove them:
```
obspy.arclink.client;time
obspy.core.utcdatetime;datetime
obspy.core.utcdatetime;time
obspy.core.util.misc;itertools
obspy.imaging.maps;datetime
obspy.imaging.spectrogram;M
obspy.imaging.waveform;datetime
obspy.mseed.util;datetime
obspy.neic.util;datetime
obspy.ndk.core;itertools
obspy.seedlink.client.seedlinkconnection;select
obspy.seedlink.client.seedlinkconnection;time
obspy.seishub.client;datetime
obspy.seishub.client;time
obspy.signal.invsim;M
obspy.signal.util;M
obspy.xseed.parser;datetime
```

I assume you can find the private names yourself easily.

**Comment by krischer** [comment]
The list was auto-generated by some code from @megies. I only had a more detailed look at the failures and removed those that obviously made no sense. Great if it passes for you too :-) We should remember to test once again before we tag the final 1.0 release.

The list does not include methods of classes so we might still need to add some more reroutes...

**Comment by megies** [comment]
> The list was auto-generated by some code from @megies.

..with this gist I think.. https://gist.github.com/megies/af7c092f1214d834159c

**Comment by megies** [comment]
> The list does not include methods of classes so we might still need to add some more reroutes...

Good point.. :/

**Comment by megies** [comment]
So what about rerouting for methods? I guess we don't have it at all, so far? I just tried some of my scripts and I'm hitting some errors on renamed methods..

**Comment by megies** [comment]
@krischer obspy.taup `VelocityModel.getDisconDepths` was renamed to `get_discontinuity_depth`, which should have a `s` at the end, I think. I guess it should be renamed, but then we have to rebuild the model npz again, I guess?

**Comment by krischer** [comment]
No that should be fine. They only have to be rebuilt when the variable names change.

**Comment by megies** [comment]
Yeah.. right

**Comment by megies** [comment]
Here's some gists concerning method renames..
 * [get list of all methods on objects exposed by 0.10.2](https://gist.github.com/megies/24582c5996ee8ccd9be1)
 * [..corresponding output, not cleaned up](https://gist.github.com/megies/f6af7faeea8c3ffcb6eb)
 * [..corresponding import test on master](https://gist.github.com/98a9f5304d36b6056288)
 * ..aaand, [list of failing import, i.e. renames, including new names](https://gist.github.com/megies/2c47cf2748ec329fa407)

Here's the list:
```
obspy.core.event;WaveformStreamID;getSEEDString;get_seed_string
obspy.core.stream;Stream;getGaps;get_gaps
obspy.core.stream;Stream;printGaps;print_gaps
obspy.core.trace;Trace;getId;get_id
obspy.core.utcdatetime;UTCDateTime;formatArcLink;format_arclink
obspy.core.utcdatetime;UTCDateTime;formatFissures;format_fissures
obspy.core.utcdatetime;UTCDateTime;formatIRISWebService;format_iris_web_service
obspy.core.utcdatetime;UTCDateTime;formatSEED;format_seed
obspy.core.utcdatetime;UTCDateTime;formatSeedLink;format_seedlink
obspy.db.indexer;WaveformFileCrawler;getFeatures;get_features
obspy.db.indexer;WaveformFileCrawler;getPatterns;get_patterns
obspy.db.indexer;WaveformFileCrawler;hasPattern;has_pattern
obspy.db.scripts.indexer;WaveformIndexer;getFeatures;get_features
obspy.db.scripts.indexer;WaveformIndexer;getPatterns;get_patterns
obspy.db.scripts.indexer;WaveformIndexer;hasPattern;has_pattern
obspy.earthworm.waveserver;tracebuf2;getObspyTrace;get_obspy_trace
obspy.earthworm.waveserver;tracebuf2;parseData;parse_data
obspy.earthworm.waveserver;tracebuf2;parseHeader;parse_header
obspy.earthworm.waveserver;tracebuf2;readTB2;read_tb2
obspy.imaging.waveform;WaveformPlotting;plotDay;plot_day
obspy.imaging.waveform;WaveformPlotting;plotSection;plot_section
obspy.imaging.waveform;WaveformPlotting;plotWaveform;plot_waveform
obspy.kinemetrics.evt;EvtHeader;makeobspydico;make_obspy_dict
obspy.kinemetrics.evt_base;EvtVirtual;setdico;set_dict
obspy.kinemetrics.evt_base;EvtVirtual;unsetdico;unset_dict
obspy.mseed.msstruct;_MSStruct;filePosFromRecNum;file_pos_from_rec_num
obspy.mseed.msstruct;_MSStruct;fileinfo;file_info
obspy.mseed.msstruct;_MSStruct;getEnd;get_end
obspy.mseed.msstruct;_MSStruct;getOffset;get_offset
obspy.mseed.msstruct;_MSStruct;getStart;get_start
obspy.mseed.msstruct;_MSStruct;setOffset;set_offset
obspy.realtime.rtmemory;RtMemory;updateInput;update_input
obspy.realtime.rtmemory;RtMemory;updateOutput;update_output
obspy.realtime.rttrace;RtTrace;getId;get_id
obspy.realtime.rttrace;RtTrace;registerRtProcess;register_rt_process
obspy.realtime.rttrace;RtTrace;rtProcessFunctionsToString;rt_process_functions_to_string
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;addStream;add_stream
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;checkVersion;check_version
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;checkslcd;check_slcd
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;configLink;config_link
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;doTerminate;do_terminate
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;getInfoString;get_info_string
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;getKeepAlive;get_keep_alive
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;getNetDelay;get_net_delay
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;getNetTimout;get_net_timeout
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;getSLAddress;get_sl_address
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;getState;get_state
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;getStreams;get_streams
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;isConnected;is_connected
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;isConnectedImpl;is_connected_impl
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;negotiateMultiStation;negotiate_multi_station
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;negotiateStation;negotiate_station
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;negotiateUniStation;negotiate_uni_station
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;parseStreamlist;parse_stream_list
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;readStreamList;read_stream_list
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;receiveData;receive_data
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;recoverState;recover_state
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;requestInfo;request_info
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;saveState;save_state
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;sayHello;say_hello
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;sendData;send_data
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;sendInfoRequest;send_info_request
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;setBeginTime;set_begin_time
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;setEndTime;set_end_time
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;setKeepAlive;set_keep_alive
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;setLastpkttime;set_last_pkt_time
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;setNetDelay;set_net_delay
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;setNetTimout;set_net_timeout
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;setSLAddress;set_sl_address
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;setStateFile;set_state_file
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;setUniParams;set_uni_params
obspy.seedlink.client.seedlinkconnection;SeedLinkConnection;updateStream;update_stream
obspy.seedlink.client.slnetstation;SLNetStation;appendSelectors;append_selectors
obspy.seedlink.client.slnetstation;SLNetStation;getSLTimeStamp;get_sl_time_stamp
obspy.seedlink.client.slnetstation;SLNetStation;getSelectors;get_selectors
obspy.seedlink.client.slstate;SLState;appendBytes;append_bytes
obspy.seedlink.client.slstate;SLState;bytesRemaining;bytes_remaining
obspy.seedlink.client.slstate;SLState;getPacket;get_packet
obspy.seedlink.client.slstate;SLState;incrementSendPointer;increment_send_pointer
obspy.seedlink.client.slstate;SLState;isEnd;is_end
obspy.seedlink.client.slstate;SLState;isError;is_error
obspy.seedlink.client.slstate;SLState;packDataBuffer;pack_data_buffer
obspy.seedlink.client.slstate;SLState;packetAvailable;packet_available
obspy.seedlink.client.slstate;SLState;packetIsInfo;packet_is_info
obspy.seedlink.slclient;SLClient;packetHandler;packet_handler
obspy.seedlink.slclient;SLClient;parseCmdLineArgs;parse_cmd_line_args
obspy.seedlink.slclient;SLClient;printUsage;print_usage
obspy.seedlink.slpacket;SLPacket;freeMSRecord;free_ms_record
obspy.seedlink.slpacket;SLPacket;getMSRecord;get_ms_record
obspy.seedlink.slpacket;SLPacket;getSequenceNumber;get_sequence_number
obspy.seedlink.slpacket;SLPacket;getStringPayload;get_string_payload
obspy.seedlink.slpacket;SLPacket;getTrace;get_trace
obspy.seedlink.slpacket;SLPacket;getType;get_type
obspy.seg2.seg2;SEG2;parseFreeForm;parse_free_form
obspy.seg2.seg2;SEG2;parseNextTrace;parse_next_trace
obspy.seg2.seg2;SEG2;readFile;read_file
obspy.seg2.seg2;SEG2;readFileDescriptorBlock;read_file_descriptor_block
obspy.seishub.client;Client;testAuth;test_auth
obspy.taup.slowness_model;SlownessModel;addSlowness;add_slowness
obspy.taup.slowness_model;SlownessModel;approxDistance;approx_distance
obspy.taup.slowness_model;SlownessModel;coarseSample;coarse_sample
obspy.taup.slowness_model;SlownessModel;createSample;create_sample
obspy.taup.slowness_model;SlownessModel;depthInFluid;depth_in_fluid
obspy.taup.slowness_model;SlownessModel;depthInHighSlowness;depth_in_high_slowness
obspy.taup.slowness_model;SlownessModel;depthIncCheck;depth_inc_check
obspy.taup.slowness_model;SlownessModel;distanceCheck;distance_check
obspy.taup.slowness_model;SlownessModel;findCriticalPoints;find_critical_points
obspy.taup.slowness_model;SlownessModel;findDepth_from_depths;find_depth_from_depths
obspy.taup.slowness_model;SlownessModel;findDepth_from_layers;find_depth_from_layers
obspy.taup.slowness_model;SlownessModel;fixCriticalPoints;fix_critical_points
obspy.taup.slowness_model;SlownessModel;getMinRayParam;get_min_ray_param
obspy.taup.slowness_model;SlownessModel;getMinTurnRayParam;get_min_turn_ray_param
obspy.taup.slowness_model;SlownessModel;getNumLayers;get_num_layers
obspy.taup.slowness_model;SlownessModel;getSlownessLayer;get_slowness_layer
obspy.taup.slowness_model;SlownessModel;layerNumberAbove;layer_number_above
obspy.taup.slowness_model;SlownessModel;layerNumberBelow;layer_number_below
obspy.taup.slowness_model;SlownessModel;layerTimeDist;layer_time_dist
obspy.taup.slowness_model;SlownessModel;ray_paramIncCheck;ray_param_inc_check
obspy.taup.slowness_model;SlownessModel;splitLayer;split_layer
obspy.taup.slowness_model;SlownessModel;toSlowness;to_slowness
obspy.taup.tau_branch;TauBranch;calcTimeDist;calc_time_dist
obspy.taup.tau_branch;TauBranch;createBranch;create_branch
obspy.taup.tau_branch;TauBranch;shiftBranch;shift_branch
obspy.taup.tau_model;TauModel;calcTauIncFrom;calc_tau_inc_from
obspy.taup.tau_model;TauModel;findBranch;find_branch
obspy.taup.tau_model;TauModel;getBranchDepths;get_branch_depths
obspy.taup.tau_model;TauModel;getTauBranch;get_tau_branch
obspy.taup.tau_model;TauModel;loadFromDepthCache;load_from_depth_cache
obspy.taup.tau_model;TauModel;splitBranch;split_branch
obspy.taup.velocity_model;VelocityModel;depthAtBottom;depth_at_bottom
obspy.taup.velocity_model;VelocityModel;depthAtTop;depth_at_top
obspy.taup.velocity_model;VelocityModel;evaluateAbove;evaluate_above
obspy.taup.velocity_model;VelocityModel;evaluateBelow;evaluate_below
obspy.taup.velocity_model;VelocityModel;fixDisconDepths;fix_discontinuity_depths
obspy.taup.velocity_model;VelocityModel;getDisconDepths;get_discontinuity_depths
obspy.taup.velocity_model;VelocityModel;layerNumberAbove;layer_number_above
obspy.taup.velocity_model;VelocityModel;layerNumberBelow;layer_number_below
obspy.taup.velocity_model;VelocityModel;readTVelFile;read_tvel_file
obspy.taup.velocity_model;VelocityModel;readVelocityFile;read_velocity_file
obspy.xseed.blockette.blockette;Blockette;getFields;get_fields
obspy.xseed.blockette.blockette;Blockette;getSEED;get_seed
obspy.xseed.blockette.blockette;Blockette;getXML;get_xml
obspy.xseed.blockette.blockette;Blockette;parseSEED;parse_seed
obspy.xseed.blockette.blockette;Blockette;parseXML;parse_xml
obspy.xseed.fields;Field;getSEED;get_seed
obspy.xseed.fields;Field;getXML;get_xml
obspy.xseed.fields;Field;parseSEED;parse_seed
obspy.xseed.fields;Field;parseXML;parse_xml
obspy.xseed.fields;FixedString;getSEED;get_seed
obspy.xseed.fields;FixedString;getXML;get_xml
obspy.xseed.fields;FixedString;parseSEED;parse_seed
obspy.xseed.fields;FixedString;parseXML;parse_xml
obspy.xseed.fields;Float;getSEED;get_seed
obspy.xseed.fields;Float;getXML;get_xml
obspy.xseed.fields;Float;parseSEED;parse_seed
obspy.xseed.fields;Float;parseXML;parse_xml
obspy.xseed.fields;Integer;getSEED;get_seed
obspy.xseed.fields;Integer;getXML;get_xml
obspy.xseed.fields;Integer;parseSEED;parse_seed
obspy.xseed.fields;Integer;parseXML;parse_xml
obspy.xseed.fields;Loop;getSEED;get_seed
obspy.xseed.fields;Loop;getXML;get_xml
obspy.xseed.fields;Loop;parseSEED;parse_seed
obspy.xseed.fields;Loop;parseXML;parse_xml
obspy.xseed.fields;VariableString;getSEED;get_seed
obspy.xseed.fields;VariableString;getXML;get_xml
obspy.xseed.fields;VariableString;parseSEED;parse_seed
obspy.xseed.fields;VariableString;parseXML;parse_xml
obspy.xseed.parser;Parser;rotateToZNE;rotate_to_zne
```

Sooo, I guess we should go over the code and in some automated fashion inject static deprecation reroute-methods for each of these? Shouldn't be too hard to do..

**Pull request merged**
