### PR TITLE
Skipping empty and incomplete StationXML channels

### LINKED ISSUE #1839: read_inventory fails on bad station metadata
For some reason which I have not figured out yet, station IV.LATE (INGV, Latera) caused the ``read_inventory`` function to fail with an ``AttributeError: 'NoneType' object has no attribute 'strip'`` 

Traceback:

```python
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/inventory/inventory.py", line 72, in read_inventory
    format=format)[0]
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/util/base.py", line 462, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 155, in _read_stationxml
    networks.append(_read_network(network, _ns))
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 201, in _read_network
    stations.append(_read_station(station, _ns))
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 242, in _read_station
    channels.append(_read_channel(channel, _ns))
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 312, in _read_channel
    longitude=longitude, elevation=elevation, depth=depth)
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/inventory/channel.py", line 129, in __init__
    self.location_code = location_code
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/inventory/channel.py", line 207, in location_code
    self._location_code = value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

After some debugging, I realised that in the ``_read_channel`` function, all values (longitude, latitude, elevation, depth, code, and location_code) are ``None`` and that causes the ``Channel.__init__`` to fail.

Currently, my workaround is to wrap line 237 in ``obspy/io/stationxml/core.py`` in a ``try/except`` statement:

```python
    channels = []
    for channel in sta_element.findall(_ns("Channel")):
        try:
            channels.append(_read_channel(channel, _ns))
        except AttributeError:
            warnings.warn('No channels available for station:\n'
                          '{}'.format(str(station)))
        # channels.append(_read_channel(channel, _ns))
    station.channels = channels
```

This results in a station entry in the inventory object with 0 channels.

I don't know if this is the preferred behavior but for now it works for me.

### PR DESCRIPTION
**Pull request by krischer**
Fixes #1839.

### CODE REVIEW

**Comment by krischer** [comment]
Completely empty channels are silently skipped, channels with unset coordinates are also skipped but a warning is raised.

**Comment by Jollyfant** [comment]
I would hoist the raised message to the _read_station level and put the station name in the user warning. 

    if cha is not None:
        channels.append(cha)
    else:
        warnings.warn(..., UserWarning)

**Comment by megies** [comment]
> I would hoist the raised message to the _read_station level

:+1: We could raise a custom exception on channel level that gets caught on station level to show the warning..

**Comment by krischer** [comment]
@Jollyfant Done. Sorry for the delay.

The internal `_read_channel()` method will now return `None` if, and only if, one of the coordinates is not set. That triggers the warning to be raised by the `_read_station()` method. This is not as clean as raising and catching a custom exception but that seemed a bit over-engineering to be me and it all happens only deep down in some internal functions.

**Comment by Jollyfant** [comment]
I'm happy feel free to merge 🐻

**Pull request merged**
