### PR TITLE
Fix 2238

### PR DESCRIPTION
**Pull request by LMurrayBergquist**
Thank your for contributing to ObsPy!

!! Please check that you select the **correct base branch** (details see below link) !!

Before submitting a PR, please review the pull request guidelines:
https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-a-pull-request

Also, please make sure you are following the ObsPy branching model:
https://github.com/obspy/obspy/wiki/ObsPy-Git-Branching-Model

### PR Checklist
- [ ] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
@LMurrayBergquist I'm sorry, @ThomasLecocq was working on the wildcard thing and doing a bit more by generalizing the reading across waveforms/events/stations as well in #2326, so this is superseded by #2326 

I'll talk to you next week about next things to work on.

**Comment by megies** [comment]
@LMurrayBergquist we're currently pushing a new release btw: https://gitter.im/obspy/obspy

**Comment by LMurrayBergquist** [comment]
> @LMurrayBergquist I'm sorry, @ThomasLecocq was working on the wildcard thing and doing a bit more by generalizing the reading across waveforms/events/stations as well in #2326, so this is superseded by #2326
> 
> I'll talk to you next week about next things to work on.

Ok, that's fine, good to get the hang of pushing things to Github anyway, I'll take a look at the other bugs that you sent earlier!

**Comment by megies** [comment]
> Ok, that's fine, good to get the hang of pushing things to Github anyway, I'll take a look at the other bugs that you sent earlier!

Which ones were that? Just to make sure they're not being worked on already..

**Comment by LMurrayBergquist** [comment]
> > Ok, that's fine, good to get the hang of pushing things to Github anyway, I'll take a look at the other bugs that you sent earlier!
> 
> Which ones were that? Just to make sure they're not being worked on already..
True, of the ones that are still open, it looks like these two might have people working on them:
https://github.com/obspy/obspy/issues/1932
https://github.com/obspy/obspy/issues/2288
But maybe this one is still free?
https://github.com/obspy/obspy/issues/1750

**Comment by megies** [comment]
#1932 and #1750 are safe to work on right now :+1:

**Comment by LMurrayBergquist** [comment]
> #1932 and #1750 are safe to work on right now 👍

Ok,  great!

**Pull request closed without merging**
