### PR TITLE
fix some map plotting issues with cartopy and local projection

### LINKED ISSUE #2193: Cartopy local projection for south hemisphere.
Hi, 
There is a misbehavior on the local projection option on the South hemisphere using cartopy:

Test code as follow:

```
import matplotlib.pyplot as plt
import obspy
from obspy.clients.fdsn import Client
auspass = Client("http://auspass.edu.au:8080")
station = auspass.get_stations(network='*',station='*',starttime=obspy.UTCDateTime('1950-01-01'),endtime=obspy.UTCDateTime())
station.plot(projection='local', color_per_network=True)
```

**The fix is the following:**
In obspy/imaging/maps.py (line 618 --  620)
```
        proj_kwargs['central_latitude'] = lat_0
        proj_kwargs['central_longitude'] = lon_0
        proj_kwargs['standard_parallels'] = [lat_0,lat_0] #Line to add to have the same behavior than Basemap
        proj = ccrs.AlbersEqualArea(**proj_kwargs)
```

Thanks

Sebastien

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Fixes #2193

### Why was it initiated?  Any relevant Issues?

See #2193

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
@seballgeyer thanks for reporting the issue and providing the patch. Should you not want to be included in contributors list just let me know.

**Comment by megies** [comment]
I'm inclined to merge this, any other opinions, maybe @QuLogic?

**Comment by QuLogic** [comment]
TBH, I don't know much about this projection, but it does seem like Basemap does this sort of thing automagically from what I could tell on a quick read.

**Comment by megies** [comment]
Alright, I'll just merge this now. It fixes a bad plot we know about and should it worsen other scenarios I guess we just have to deal with it later on again.

**Pull request merged**
