### PR TITLE
More taup models

### PR DESCRIPTION
**Pull request by krischer**
#1197 enables the creation of two more models for TauP.

They are once again taken from the Java TauP variant.

### CODE REVIEW

**Comment by megies** [comment]
Guess, I was too fast merging that earlier PR..

**Comment by QuLogic** [comment]
Probably should wait for #1199 here at least, and maybe #1200.

**Comment by krischer** [comment]
Should wait on #1224 and the `.npz` files have to be rebuilt once it is done.

**Comment by QuLogic** [comment]
I'd like to add the alternate AK135 models as well.

**Comment by krischer** [comment]
Which one do you mean? AFAIK the AK135-f model is the normal AK135 with some density and Q values but I think we don't use these for the taup calculations.

**Comment by QuLogic** [comment]
I'm not sure they're exactly the same; the depths above 120 seem a bit different. Also, I'd like an `ak135f_no_mud` to be able to produce something compatible with specfem3d_globe.

**Comment by krischer** [comment]
Sounds good.

**Comment by QuLogic** [comment]
I'd like this in 1.0.0 so I can use it ;) I'll rebase and update later tonight.

**Comment by QuLogic** [comment]
So it turns out it won't be possible to support AK135-f since the top layer has 0 S velocity, and the original Java implementation does not support that. I added the table anyway for if it becomes possible in the future, but didn't (and can't) build the model.

**Comment by megies** [comment]
Is this ready to merge?

**Comment by QuLogic** [comment]
Fine from my side, @krischer?

**Comment by krischer** [comment]
I rebased against the latest master and rebuilt the first two models I added with the latest master taup version. @qulogic I guess you also did this but better safe than sorry ;-)

If CI passes I'll merge.

**Comment by megies** [comment]
> If CI passes I'll merge.

Need to force geographiclib<1.46 temporarily if Travis' nod is necessary..

**Comment by QuLogic** [comment]
I did rebuild earlier, and added a couple small tests, so AppVeyor should probably be enough this time.

**Comment by krischer** [comment]
Passes on appveyor. Merging.

**Pull request merged**
