### PR TITLE
Wrong underside reflections in obspy.taup

### PR DESCRIPTION
**Pull request by QuLogic**
The `P^410P`, `P660P`, ... phases are not reflected at the proper interface. They instead come back as `PP` phases. The same is true for s phases.

```python
>>> from obspy.taup import TauPyModel
>>> m = TauPyModel("ak135")
>>> print(m.get_ray_paths(source_depth_in_km=10, distance_in_degree=90.0,
                          phase_list=["P^410P", "PP"]))
2 arrivals
	PP phase arrival at 992.616 seconds
	P^410P phase arrival at 992.616 seconds
```

### CODE REVIEW

**Comment by QuLogic** [comment]
Travis failure is unrelated `future` problem.

**Comment by QuLogic** [comment]
:ship: :question:

**Comment by krischer** [comment]
I added test. I'll merge as soon as CI passes. Sorry for taking so long.

**Comment by megies** [comment]
@QuLogic, the Py2.6 fail is unrelated? Good to merge then I guess..

**Comment by QuLogic** [comment]
Yep, that's just the `future` stuff.

**Comment by megies** [comment]
Well.. then

**Pull request merged**
