### PR TITLE
5x speed-up for trace.id / trace.get_id()

### PR DESCRIPTION
**Pull request by flixha**
### What does this PR do?
This PR makes retrieving the seed-id of a trace 4 times quicker than previously.

While it wasn't particularly slow, when looping through many traces the change can still be noticeable and is very simple. The previous syntax was nicely succinct, but relatively slow compared to alternatives.

### Why was it initiated?  Any relevant Issues?
I noted that I could speed up [`trace.get_id`](https://github.com/obspy/obspy/blob/49b8b411ff10593ce9583f90d6fbbb582dc07fc9/obspy/core/trace.py#L875-L876) with this tiny change. See code below for a quick comparison for the run times (in python 3.11):

```python
from obspy import read
st = read()
tr = st[0]

# original code: 1200 ns
%timeit out = "%(network)s.%(station)s.%(location)s.%(channel)s"; out % (tr.stats) 
# Alt 1: 350 ns 
%timeit "{}.{}.{}.{}".format( tr.stats.network, tr.stats.station, tr.stats.location, tr.stats.channel)
# Alt 2: 274 ns
%timeit (tr.stats.network + '.' + tr.stats.station + '.' + tr.stats.location + '.' + tr.stats.channel)
# Alt 3: 222 ns
%timeit '.'.join((tr.stats.network, tr.stats.station, tr.stats.location, tr.stats.channel))
```

### PR Checklist
- [X] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [X] This PR is not directly related to an existing issue (which has no PR yet).
~- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds~
~- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.~
~- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.~
- [X] All tests still pass.
~- [ ] Any new features or fixed regressions are covered via new tests.~
~- [ ] Any new or changed features are fully documented.~
- [X] Significant changes have been added to `CHANGELOG.txt` .
~- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .~
~- [ ] If the changes affect any plotting functions you have checked that the plots~
      ~from all the CI builds look correct. Add the "upload_plots" tag so that plotting~
      ~outputs are attached as artifacts.~
~- [ ] New modules, add the module to `CODEOWNERS` with your github handle~
- [ ] Add the `ready for review` tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by filefolder** [comment]
fwiw here they all are on my py3.11 as well

```
%timeit out = "%(network)s.%(station)s.%(location)s.%(channel)s"; out % (tr.stats)
    1.32 µs ± 4.75 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

%timeit "{}.{}.{}.{}".format( tr.stats.network, tr.stats.station, tr.stats.location, tr.stats.channel)
    342 ns ± 6.93 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

%timeit (tr.stats.network + '.' + tr.stats.station + '.' + tr.stats.location + '.' + tr.stats.channel)
    267 ns ± 2.87 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

%timeit '.'.join((tr.stats.network, tr.stats.station, tr.stats.location, tr.stats.channel))
    232 ns ± 1.05 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each) 

```

**Comment by flixha** [comment]
> Can you try timing:
> 
> ```python
> %timeit '.'.join((tr.stats.network, tr.stats.station, tr.stats.location, tr.stats.channel))
> ```
> 
> For me it is about 20% faster than the current implementation (# Alt 2) and is quite a bit shorter/clearer.

222 ns for me, so indeed the fastest with 20 % faster than Alt 2 - very good!. Updated times above.

**Review by megies — APPROVED** [review]
:rocket:

**Comment by heavelock** [comment]
Just for sake of completeness I run those benchmarks plus an f-string solution.

```python 
%timeit out = "%(network)s.%(station)s.%(location)s.%(channel)s"; out % (tr.stats)
1.72 µs ± 36.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

%timeit "{}.{}.{}.{}".format( tr.stats.network, tr.stats.station, tr.stats.location, tr.stats.channel)
512 ns ± 1.49 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

%timeit (tr.stats.network + '.' + tr.stats.station + '.' + tr.stats.location + '.' + tr.stats.channel)
379 ns ± 2.07 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

%timeit '.'.join((tr.stats.network, tr.stats.station, tr.stats.location, tr.stats.channel))
296 ns ± 0.939 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

%timeit f"{tr.stats.network }.{tr.stats.station}.{tr.stats.location}.{tr.stats.channel}"
278 ns ± 0.958 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

It seems that the f-string is even faster :D

**Pull request merged**
