### PR TITLE
the great seiscomp 0.11/0.12 amalgam PR

### PR DESCRIPTION
**Pull request by filefolder**
My attempt at combining #2124, #2284, and #2695 which add compatibility with the seiscomp XML 0.11 (and now also 0.12) schema which have been out for some years now. I think the original PRs have all been abandoned at this point so my apologies if overstepping. 

Current Status: everything works, all tests pass

comments / opinions on the below?

- Dropped support for schemas 0.3 and 0.5. The last seiscomp3 schema was 0.10 and we still support 0.9-0.6. Seiscomp 4 has now been out for over two years. 

- (related) began to change descriptions from "sc3ml" to "scxml" as this seems to be the official new way to go, or even "scml" I have seen now at Gempa. Have not changed any function names for fear of breaking anything, and the actual schema they publish still have "seiscomp3" in it so left that alone. It would be nice to implement an optional format="SCXML" or "SCML" option parallel to "SC3ML" when writing a catalog but I couldn't see where this was done.

- there is a gross warning `UserWarning: ResponseIIR is not fully tested in ObsPy. Please be cautious` when loading anything with a z-transform, is this still an unknown? Seems to load fine and it also removes the response as expected.

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
thanks @filefolder , this is already a lot of work. I hope to have time this week to work on it. Could you allow me as collaborator to your branch ?

**Comment by filefolder** [comment]
I've added both of you as collaborators. If you find it's easier to edit from this branch, feel free, if you prefer to start over yourself or were halfway through I totally understand as it's a huge mess. 

I hope to give it a second go this week as well.

**Comment by filefolder** [comment]
quick update but I found the bug stopping the response stages from being read.

as far as I can tell this PR is now fully functional, just needs to update the testing segment (i will get around to this next) and clear these checks. 

it would be good if we could get some additional tests with 0.10 & 0.11.

**Comment by d-chambers** [comment]
@filefolder any idea on the CI tests fails?

**Comment by filefolder** [comment]
thanks for having a look at this. there was one bug the testing caught involving a None paz and another when there was a trailing space in the coefficient field but they should be fixed now.

https://tests.obspy.org/118645/

otherwise it looks like there is a path error typo (where is "/event/to/iris_events" introduced?) and probably some glitch where 0.11 and 0.12 scxml files are being compared to each other causing all the "False is not True" errors i need to look into. i have also uploaded a few example 0.12 catalog and inventory files to implement more tests with, but to be honest i am not very familiar with how the testing is set up and could probably use some help. 

all in all seems just about there

**Comment by filefolder** [comment]
OK all tests (related to this anyway) should be passing now. I've added one new 0.12 event catalog version but have left the previous inventory data test data (EB_response_sc3ml) more or less as it was. Forgive the excessive amount of tiny commits.

**Comment by ThomasLecocq** [comment]
@filefolder still one test failing (related to loading a response, I think): https://tests.obspy.org/118806/

**Comment by filefolder** [comment]
yeah i've been trying to figure out what is going on there, or why it works on 3.7 but nothing else. 

as far as I can tell the example data `BW.KW1._.EHZ.D.2011.090_downsampled.asc.gz` or anything related to this hasn't been irritated nor is this PR relevant to the function below. Test also works on my machine running this branch so I'm a bit stumped. 

Will have to look into whatever issue 1216 was 

```
    def test_issue1216(self):
        tr, paz = _get_sample_data()
        st = Stream([tr])
        ppsd = PPSD(tr.stats, paz, db_bins=(-200, -50, 0.5))
        ppsd.add(st)
        # After adding data internal representation of hist stack is None
        assert ppsd._current_hist_stack is None
        # Accessing the current_histogram property calculates the default stack
        assert ppsd.current_histogram is not None
        assert ppsd._current_hist_stack is not None
        # Adding the same data again does not invalidate the internal stack
        # but raises "UserWarning: Already covered time spans detected"
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter('always', UserWarning)
            ppsd.add(st)
            assert len(w) == 4
            for w_ in w:
                assert str(w_.message).startswith(
                    "Already covered time spans detected")
        assert ppsd._current_hist_stack is not None
        # Adding new data invalidates the internal stack
        tr.stats.starttime += 3600
        st2 = Stream([tr])
        # raises "UserWarning: Already covered time spans detected"
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter('always', UserWarning)
            ppsd.add(st2)
            assert len(w) == 2  #<<<<<<<<<<<<<<<<<<<<<<<<<<<< github giving 4?
            for w_ in w:
                assert str(w_.message).startswith(
                    "Already covered time spans detected")
        assert ppsd._current_hist_stack is None
        # Accessing current_histogram again calculates the stack
        assert ppsd.current_histogram is not None
        assert ppsd._current_hist_stack is not None
```

**Comment by ThomasLecocq** [comment]
> yeah i've been trying to figure out what is going on there, or why it works on 3.7 but nothing else.
> 
> as far as I can tell the example data `BW.KW1._.EHZ.D.2011.090_downsampled.asc.gz` or anything related to this hasn't been irritated nor is this PR relevant to the function below. Test also works on my machine running this branch so I'm a bit stumped.
> 
> Will have to look into whatever issue 1216 was
> 
> ```
>     def test_issue1216(self):
>         tr, paz = _get_sample_data()
>         st = Stream([tr])
>         ppsd = PPSD(tr.stats, paz, db_bins=(-200, -50, 0.5))
>         ppsd.add(st)
>         # After adding data internal representation of hist stack is None
>         assert ppsd._current_hist_stack is None
>         # Accessing the current_histogram property calculates the default stack
>         assert ppsd.current_histogram is not None
>         assert ppsd._current_hist_stack is not None
>         # Adding the same data again does not invalidate the internal stack
>         # but raises "UserWarning: Already covered time spans detected"
>         with warnings.catch_warnings(record=True) as w:
>             warnings.simplefilter('always', UserWarning)
>             ppsd.add(st)
>             assert len(w) == 4
>             for w_ in w:
>                 assert str(w_.message).startswith(
>                     "Already covered time spans detected")
>         assert ppsd._current_hist_stack is not None
>         # Adding new data invalidates the internal stack
>         tr.stats.starttime += 3600
>         st2 = Stream([tr])
>         # raises "UserWarning: Already covered time spans detected"
>         with warnings.catch_warnings(record=True) as w:
>             warnings.simplefilter('always', UserWarning)
>             ppsd.add(st2)
>             assert len(w) == 2  #<<<<<<<<<<<<<<<<<<<<<<<<<<<< github giving 4?
>             for w_ in w:
>                 assert str(w_.message).startswith(
>                     "Already covered time spans detected")
>         assert ppsd._current_hist_stack is None
>         # Accessing current_histogram again calculates the stack
>         assert ppsd.current_histogram is not None
>         assert ppsd._current_hist_stack is not None
> ```

it's not your PR, it's also in master #2977 , no worries

**Comment by ThomasLecocq** [comment]
I just scrolled through all the changes and nothing seemed strange. I'll checkout this branch and test on some of my own SCXML from different machines (old SC3, new SC4, etc) and see how it goes, but looks good!

**Comment by filefolder** [comment]
just a quick update for anyone wondering, this is synced up as of this post and i think it's ready to go. really hope it can get into 1.3 as obspy has otherwise been incompatible with SC for over three years now.

**Comment by megies** [comment]
This PR is massive, so I can't really proper review this for the release, but I'd be willing to just go ahead and merge it in.
If I understand correctly, we lost read support for older seiscomp xml versions, @filefolder ? I'm assuming there's a reason for that, because in general being able to read old legacy formats is one of our strong points.

**Comment by filefolder** [comment]
> This PR is massive, so I can't really proper review this for the release, but I'd be willing to just go ahead and merge it in. If I understand correctly, we lost read support for older seiscomp xml versions, @filefolder ? I'm assuming there's a reason for that, because in general being able to read old legacy formats is one of our strong points.

that's correct, booted <= 0.5 just to clear up space/tests. i suppose there's always an argument to keep the ancient stuff but i figured it was time to move on for the same reason obspy is dropping arclink, earthworm, etc. version 0.11 which coincides with the release of SC4 is now 3+ years old, so I think 0.5 may predate the "Potsdam" version in 2010. 

worst case scenario is someone just uses the xslt files included with seiscomp to convert whatever decades-old xml files they like.

otherwise sorry about the size of this, most edits are redundant or minor due to me doing this mostly via web instead of the sane way. i expect additional finer tuning and aesthetic choices with fully changing over to the "scxml" or "scml" convention may happen later.

**Comment by megies** [comment]
Gotcha. In the future I'd vote for not dropping read support for older files unless it's a serious hassle, but I guess we can live with it this time. :+1:

**Review by megies — APPROVED** [review]
Should be fine, if anything really should come up we'll just handle it later  :laughing:

**Comment by trichter** [comment]
I pushed the button.

**Pull request merged**
