### PR TITLE
Exception raised while comparing stream objects read from big and little endian SEG-Y files

### PR DESCRIPTION
**Pull request by krischer**
Linux, Obspy 1.0.2 installed via pip

Hi trying to compare the stream objects read from two SEGY files (both were created using obspy), which only differ by endianess I get the following exception: 

    Python 2.7.12 (default, Jul 01 2016, 15:36:53) [GCC] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from obspy import read
    >>> sl = read("littleEndian.sgy")
    >>> s = read("bigEndian.sgy")   
    >>> s == sl
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python2.7/site-packages/obspy/core/stream.py", line 595, in __eq__
        if self_sorted.traces != other_sorted.traces:
      File "/usr/lib64/python2.7/site-packages/obspy/core/trace.py", line 298, in __eq__
        if not self.stats == other.stats:
      File "/usr/lib64/python2.7/_abcoll.py", line 426, in __eq__
        return dict(self.items()) == dict(other.items())
      File "/usr/lib64/python2.7/_abcoll.py", line 426, in __eq__
        return dict(self.items()) == dict(other.items())
      File "/usr/lib64/python2.7/_abcoll.py", line 426, in __eq__
        return dict(self.items()) == dict(other.items())
      File "/usr/lib64/python2.7/_abcoll.py", line 414, in items
        return [(key, self[key]) for key in self]
      File "/usr/lib64/python2.7/site-packages/obspy/io/segy/core.py", line 721, in __getitem__
        return super(AttribDict, self).__getitem__(name)
      File "/usr/lib64/python2.7/_abcoll.py", line 377, in __getitem__
        raise KeyError
    KeyError

Indicating that not all attributes are properly set in reading one of the files. The files read can be found in attached zip file [segy_files.zip](https://github.com/obspy/obspy/files/878843/segy_files.zip)

### CODE REVIEW

**Comment by krischer** [comment]
Now a PR with a fix. There were a bit two many loops to jump when inheriting from AttribDict - it should now work fine. It will of course still not compare equal with two different byte orders but that is a different issue and IMHO likely not that crucial in practice.

**Comment by krischer** [comment]
CI failure are unrelated.

**Comment by megies** [comment]
Docker testbot says 👍

Fails are just because I had some new Debian 9 Stretch images lying around that have mpl 2.0 fails, so they can be ignored.

**Comment by megies** [comment]
Travis fails are also unrelated.

**Comment by krischer** [comment]
@paitor Thanks for your comment. I fixed it.

From my side this is ready to merge if all tests pass.

**Pull request merged**
