### PR TITLE
more verbose TypeErrors in trace.__add__

### PR DESCRIPTION
**Pull request by ThomasLecocq**
### What does this PR do?
Just adds some verbosity in the sanity checks done in the __add__ method of traces.

### Why was it initiated?  Any relevant Issues?
It's soooooo frustrating to debug 
```TypeError("Data type differs") ```

### PR Checklist
- [x] All tests still pass.
- [X] Significant changes have been added to `CHANGELOG.txt`  (is this significant? don't think so)

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
wtf? appveyor?

**Comment by QuLogic** [comment]
Change "matplotlib<2" to "matplotlib<1.9" since conda seems to think 2.0.0rc2 is not yet 2 and installs it.

**Comment by ThomasLecocq** [comment]
> Change "matplotlib<2" to "matplotlib<1.9" since conda seems to think 2.0.0rc2 is not yet 2 and installs it.

I just based this on master, so you're saying we need to change master .appveyor.yml ?

**Comment by megies** [comment]
> Change "matplotlib<2" to "matplotlib<1.9" since conda seems to think 2.0.0rc2 is not yet 2 and installs it.

Ah.. right, and that's actually correct according to [PEP 440](https://www.python.org/dev/peps/pep-0440/#development-release-separators)

> I just based this on master, so you're saying we need to change master .appveyor.yml ?

Since this PR is ready to merge already, you can just add it to this PR so the change will be in master within days.

**Pull request merged**
