### PR TITLE
Fix pep8 builds against newer flake8.

### PR DESCRIPTION
**Pull request by QuLogic**
This should fix the `AttributeError: 'module' object has no attribute 'DEFAULT_CONFIG'` error that is raised with latest `flake8`.

`flake8` 2.5.5 sets `pep8.USER_CONFIG` itself without passing `config_file` instead.

### CODE REVIEW

**Comment by krischer** [comment]
`flake8` 3.x which is also already out unfortunately changed the API once again. How about we handle it like here:

https://github.com/krischer/mtspec/blob/master/mtspec/tests/test_code_formatting.py

It will just skip the code formatting tests for flake8 versions < 3.0. We'd just have to make sure to install the lastest flake8 with pip in the CI runners.

**Comment by megies** [comment]
> How about we handle it like here:
> 
> https://github.com/krischer/mtspec/blob/master/mtspec/tests/test_code_formatting.py
> 
> It will just skip the code formatting tests for flake8 versions < 3.0. We'd just have to make sure to install the lastest flake8 with pip in the CI runners.

I really only care about CI running flake8, everything else doesn't matter for me.
So, totally :+1: as soon as CI can run flake8 3.x (I don't see it in anaconda cloud yet?).

**Comment by krischer** [comment]
pypi already has `flake8` 3.0.3. We can just use `pip` to install it - no need to use `conda`.

**Comment by krischer** [comment]
More work then I would have done but looks good to me. Do we still use the pep8 checker during docs building?

**Comment by QuLogic** [comment]
Yes, PEP8 results are posted [here](https://docs.obspy.org/pep8/index.html).

**Pull request merged**
