### PR TITLE
add codeowners file

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Adds `CODEOWNERS` file, in order to..
 - get automatic pings/review requests out to people when parts of the code get touched that they have an involvement of sorts with
 - to make it easier/faster for core devs to find out who to ask for feedback on pull requests on specific parts of the code

### Why was it initiated?  Any relevant Issues?

compare #3074 

### PR Checklist
- [ ] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] Add the `ready for review` tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
> OK with me. We can try this out. It probably won't work to automatically notify people without write access.

Yes I saw that, I might add some more people to developer team just for that, in some other cases I think it's OK and we can just use it as a place to look things up

**Comment by megies** [comment]
@crotwell @chad-iris are you OK to get added to developer team, just so you can get automatic notifications when things happen in parts of the code you might be interested in?

**Comment by crotwell** [comment]
Yep, as long as you don't actually expect me to do anything! :)

**Comment by chad-iris** [comment]
Ha!  Same for me, no problem with an add.

**Pull request merged**
