### PR TITLE
obspy-scan: allow fnmatch wildcards when selecting specific SEED IDs during plotting

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Allow fnmatch wildcards when selecting specific SEED IDs during plotting so one can e.g. select only "[EH]H*" channels for a plot after scanning an SDS tree.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [x] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [x] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

Just needs a short test basically..

### CODE REVIEW

**Comment by megies** [comment]
Rebased on current master and force-pushed so that we have fresh CI results tomorrow.

**Comment by ThomasLecocq** [comment]
Where is the aaaamaaaazing test case?

**Comment by megies** [comment]
Should be good now, lets wait for CI

**Comment by megies** [comment]
Test fail unrelated.

**Pull request merged**
