### PR TITLE
Fix citation for Wood Anderson zeros and poles

### PR DESCRIPTION
**Pull request by barsch**
see https://discourse.obspy.org/t/where-does-obspy-wood-anderson-zeros-and-poles-information-come-from/1191/2

### CODE REVIEW

**Comment by claudiodsf** [comment]
Why not citing the new version, which has a DOI (https://doi.org/10.2312/GFZ.NMSOP-2) and publicly available PDF?

Poles and zeros are here: https://gfzpublic.gfz-potsdam.de/rest/items/item_257075/component/file_367181/content (table 11.3)

The magnification factor of 2080 is here: https://gfzpublic.gfz-potsdam.de/rest/items/item_43489/component/file_56102/content (page 2)

**Comment by claudiodsf** [comment]
oops, I checked only the poles 🙄

**Comment by claudiodsf** [comment]
Actually in table 11.3 ("Zeros and poles corresponding to the displacement transfer functions") they are:

Seismograph | Zeros | Poles
-- | -- | --
WA | (0.0, 0.0)<br>(0.0, 0.0) | (-6.2832, -4.7124)<br>(-6.2832, 4.7124)

While in table 11.5 ("Poles and zeros of the simulation filters required for simulating standard seismograms" they are:

Seismograph | Zeros | Poles
-- | -- | --
WA | (-3.6743E-02, -3.6754E-02)<br>(-3.6743E-02, 3.6754E-02) | (-6.2832, -4.7124)<br>(-6.2832, 4.7124)<br>(0.0, 0.0)

And, on page 58, one can read:

> Note that the poles and zeros given in Tabs. 11.3 and 11.4 are valid only if the input signal to the considered seismographs is ground displacement (amplitude Ad). Consequently, the values in Tab. 11.3 are not suitable for simulating the responses of the classical seismographs if the input signal to the filter is not displacement.

**Comment by barsch** [comment]
I don't know about the implementation details - I didn't write that code - if its wrong it needs fixing.

However, those lines were committed on Mar 28, 2011
(https://github.com/obspy/obspy/commit/e790bee691da190e3686f99bfd9ec2dab11ea980) - and there was no NMSOPv2 in 2011  - this PR just adds the full citation.

**Comment by aringler-usgs** [comment]
I don't know if this helps, but using the correction from Uhrhammer and Collins (1990), they recommend 2 0s at 0 and a complex conjugate pole at -5.49779+/-5.60886*1j.  See the following (Table 1) from IASPEI: [link](http://www.iaspei.org/commissions/commission-on-seismological-observation-and-interpretation/Summary_WG_recommendations_20130327.pdf)

**Comment by claudiodsf** [comment]
> I don't know about the implementation details - I didn't write that code - if its wrong it needs fixing.
> 
> However, those lines were committed on Mar 28, 2011 ([e790bee](https://github.com/obspy/obspy/commit/e790bee691da190e3686f99bfd9ec2dab11ea980)) - and there was no NMSOPv2 in 2011 - this PR just adds the full citation.

Ok, so I'm going accept this PR. If someone (@aringler-usgs ?) wants to dive deeper into the most correct way of simulating a Wood-Anderson please open an issue or a PR.

**Review by claudiodsf — APPROVED** [review]

**Pull request merged**
