### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by foobarbecue**
CONNNECTIONS --> CONNECTIONS

### CODE REVIEW

**Comment by megies** [comment]
Oh.. @foobarbecue I just noticed this should've been based on `maintenance_1.1.x`. Since you made your edit in the online editor, I'm assuming you probably don't want to do the rebasing yourself? Just let me know, I can also just cherry-pick your commit.

**Comment by megies** [comment]
@foobarbecue I just cherry-picked your commit on maintenance branch and pushed, see 8e820523ee134e8b11a0a76565d99ea9a3a2e5c0.

Thanks, and again just let me know if you want to be on the contributors list.

**Comment by foobarbecue** [comment]
Thanks @megies ! I don't feel I deserve contributors list for fixing a typo! Hopefully I will find time to make real contributions soon.

**Comment by megies** [comment]
Alright, your call. Looking forward to more contributions then, @foobarbecue  :+1:

**Pull request closed without merging**
