### PR TITLE
remove_response(): add plot option ...

### PR DESCRIPTION
**Pull request by megies**
… to plot individual steps of instrument correction in frequency domain.

(replaces of #1105)

```python
from obspy import read, read_inventory

st = read("/path/to/IU_ULN_00_LH1_2015-07-18T02.mseed")
tr = st[0]
inv = read_inventory("/path/to/IU_ULN_00_LH1.xml")
tr.attach_response(inv)

pre_filt = [0.001, 0.005, 10, 20]
tr.remove_response(pre_filt=pre_filt, output="DISP",
                   water_level=60, plot=True)
```
trace_remove_response

### CODE REVIEW

**Comment by megies** [comment]
Everything should be in place, can be merged when CI says yeah.

**Comment by QuLogic** [comment]
Unfortunately, it did not...

**Comment by QuLogic** [comment]
Whoa, Travis really broke suddenly. Maybe a rebase to get those changes you made recently?

**Comment by megies** [comment]
Forgot one test image update.. rebased.

**Pull request merged**
