### PR TITLE
Use reviewdog to post flake8 violations to PRs.

### PR DESCRIPTION
**Pull request by QuLogic**
### What does this PR do?

Like matplotlib/matplotlib#17143, this posts flake8 violations as Checks directly to PRs. They appear on the diffs instead of having to look at the build log.

### Why was it initiated?  Any relevant Issues?

See https://github.com/obspy/obspy/pull/2706#issuecomment-683385658

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by QuLogic** [comment]
Seems to have timed out or something on tests; is there a reason we use checkout@v1 instead of checkout@v2?

**Comment by megies** [comment]
Probably not, but I'm not in the details of the new gh-actions setup. I'd say, go ahead and make changes as you see fit @QuLogic

**Comment by d-chambers** [comment]
>is there a reason we use checkout@v1 instead of checkout@v2?

I was just following a template that used checkout v1, I don't see why we cant use v2.

**Review by megies — APPROVED** [review]
CI looks to be running fine, so let's get this into master. Thanks!

**Pull request merged**
