### PR TITLE
Non-verbose error message using invalid FDSN request for PY3

### PR DESCRIPTION
**Pull request by megies**
Anaconda installation of ObsPy 1.0.3 on Linux

Script:
```
from obspy.core import UTCDateTime as UTC
from obspy.clients.fdsn import Client as FSDNClient

kw = {'starttime': UTC('2005-04-01'), 'endtime': UTC('2005-05-01'),
      'minmagnitude': 1.5, 'maxmagnitude': 3.5,
      'minlatitude': 25, 'maxlatitude': 49.5,
      'minlongitude': -124, 'maxlongitude': -67,
      'maxdepth': 40,
      'catalog': 'ANF'}
client = FSDNClient()
events = client.get_events(**kw)
```

Output of `python2`:
```
  File "bug_client.py", line 16, in <module>
    events = client.get_events(**kw)
  File "/home/eule/anaconda/envs/dev2/lib/python2.7/site-packages/obspy/clients/fdsn/client.py", line 419, in get_events
    data_stream = self._download(url)
  File "/home/eule/anaconda/envs/dev2/lib/python2.7/site-packages/obspy/clients/fdsn/client.py", line 1363, in _download
    server_info)
obspy.clients.fdsn.header.FDSNException: Service responds: Internal server error
Detailed response of server:

Error 500: ERROR: invalid input value for enum catalog_: "ANF"
Request:
http://service.iris.edu/fdsnws/event/1/query?endtime=2015-09-01T00%3A00%3A00.000000&maxlongitude=-67.0&includearrivals=false&minlongitude=-124.0&maxlatitude=49.5&catalog=ANF&maxmagnitude=3.5&maxdepth=40.0&starttime=2005-04-01T00%3A00%3A00.000000&minmagnitude=1.5&minlatitude=25.0
Request Submitted:
2017/04/12 11:24:33 UTC
Service version:
Service: fdsnws-event  version: 1.1.7
```

Output using `python3`:

```
Traceback (most recent call last):
  File "bug_client.py", line 16, in <module>
    events = client.get_events(**kw)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.5/site-packages/obspy/clients/fdsn/client.py", line 415, in get_events
    data_stream = self._download(url)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.5/site-packages/obspy/clients/fdsn/client.py", line 1359, in _download
    server_info)
obspy.clients.fdsn.header.FDSNException: Service responds: Internal server error
```
(No detailed response displayed)

By the way: Does anybody know where I can download the ANF event catalog (via FDSN webservice) wich was formerly available via IRIS?

### CODE REVIEW

**Comment by megies** [comment]
Converted this into a PR fixing the issue, sorry for hijacking your OP, strange github API change that changes user of OP when coverting to a PR..

**Comment by krischer** [comment]
> Converted this into a PR fixing the issue, sorry for hijacking your OP, strange github API change that changes user of OP when coverting to a PR..

Yea this is really strange - maybe we should restrain from converting other peoples issues and just open a new PR until it is resolved?

**Comment by megies** [comment]
> Yea this is really strange - maybe we should restrain from converting other peoples issues and just open a new PR until it is resolved?

I think it's worth messing up the user of OP in order to avoid duplicated tickets but I'm fine either way..  It's just really strange that github made this change on an API feature that has been marked as deprecated for as long as I can remember (and an API feature that is sorely needed, IMHO -- no idea why github never made this accessible through the web interface, really)

**Comment by trichter** [comment]
No problem for hijacking.

Thanks, this solved the issue, a proper message is displayed!

**Pull request merged**
