### PR TITLE
Adding py39 to the test matrix

### PR DESCRIPTION
**Pull request by ThomasLecocq**
### What does this PR do?

Adds python 3.9 (to start with) to the github action test matrix (aims at replacing #2722 )

### Why was it initiated?  Any relevant Issues?

About time... But I fear the tests will be loooooooong lasting.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests still pass.
- [x] Significant changes have been added to `CHANGELOG.txt` .

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
Currently fails, mostly due to Win10 solving.

Something I plan to test here is what I just did for MSNoise: caching the created envrionments daily, so that activating them requires only an untar of a cached folder:

https://github.com/ROBelgium/MSNoise/commit/05d5bca398f48f4beab0e824aea22a8a990b8c57

it reduces by some minutes the test time, that's already something ...

Any thoughts in favor/against ? @d-chambers @claudiodsf

**Comment by claudiodsf** [comment]
> Any thoughts in favor/against ? @d-chambers @claudiodsf

Caching seems a good idea and I cannot see big drawbacks.

One thing that would be nice is the ability to clear the cache to debug failing tests, but it seems that it is a feature not yet implemented: https://github.com/actions/cache/issues/2 

But, yes, go for it!

**Comment by ThomasLecocq** [comment]
OK, right. So , first things first, have the 3.9 matrix running properly in master !

**Comment by ThomasLecocq** [comment]
almost done, the python 3.9 errors are linked to ImageComparison (which I'll investigate later)

Only remaining 🔴 is python 3.9 + windows , I've re-pinned numpy<1.22 for now

**Comment by ThomasLecocq** [comment]
image
Happy me :-)

but ! this comes at a price, of some ugly temporary stuff:

- currently 3 different environment files for the 3 versions tested
- awful hack in:
  - obspy/core/tests/test_util_base.py
  - obspy/core/util/testing.py
  - obspy/signal/tests/test_spectral_estimation.py

I think it's still good to merge in master, and I'll immediately open a new Issue with the Todos for those actions, including:
- saving the "baseline", "computed" & "difference" images to a local folder of the runner
- if not empty, zipping that folder and providing it as an artifact for each test run (or upload it somewhere as 1 file)
- therefore removing the imgur uploads which are not very practical
- then with those, find out how bad/strong most of the images are on all platforms & why (e.g. for some it's only xlabels, but for some others, e.g. response information, there are significant shape change, e.g. https://i.imgur.com/L1d4DNF.png

so, now, if OK for you, I'll merge so we have py39 tests on master

**Comment by ThomasLecocq** [comment]
DO NOT MERGE yet, I have to adapt the master tests too !

**Review by d-chambers — APPROVED** [review]
Ya, this is a bit hinky, and we certainly don't want to leave it this way long-term. We need to spend some time thinking about how we do image comparisons but that is for a future day.

**Comment by ThomasLecocq** [comment]
ok, good to merge 🟢

**Pull request merged**
