### PR TITLE
clients.neic: Make NEIC client socket blocking

### PR DESCRIPTION
**Pull request by jmfee-usgs**
### What does this PR do?

This removes the call `socket.setblocking(0)` in the NEIC client.

### Why was it initiated?  Any relevant Issues?

Excessive CPU usage has been observed on systems using this client.

A `setblocking(0)` call is commented out in the seedlink client, but is otherwise not referenced within obspy for any other socket handling.  Using a blocking socket waits for data to be available instead of endlessly looping.

The python documentation states:
> You have (of course) a number of choices. You can check return code and error codes and generally drive yourself crazy. If you don’t believe me, try it sometime. Your app will grow large, buggy and **suck CPU**.
> https://docs.python.org/2/howto/sockets.html#non-blocking-sockets

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [x] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:clients.neic"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
@ketchum-usgs : fyi

**Comment by megies** [comment]
I'm not personally using the NEIC client, so I'm totally ready to just merge this without much looking into.

However, this should go either into `maintenance_1.2.x` or `master`. I'll change the base branch of the PR, git should be able to figure it out, since only more (unrelated) commits will pop up in between.

Also.. we'll want a one-liner in the Changelog

**Comment by megies** [comment]
Ok, so this actually needs tweaking, since we added a `with` context around the part of the code this line sits in @jmfee-usgs 

You can either rebase locally and force push after, or just reset your branch to maintenance_1.2.x and then redo the commit. Let me know if anything unclear @jmfee-usgs

**Comment by jmfee-usgs** [comment]
I'll update this, originally had it against master and then switched to the maintenance branch referenced in CONTRIBUTING.md:
https://github.com/obspy/obspy/blame/master/CONTRIBUTING.md#L32

**Comment by jmfee-usgs** [comment]
@megies : I think is should be ready, let me know if this needs any other changes

**Comment by megies** [comment]
+TESTS:clients.neic

will restart Travis so that the neic tests are run on it

**Comment by megies** [comment]
NEIC tests passed, adjusted changelog and will merge now, thanks @jmfee-usgs

**Pull request merged**
