### PR TITLE
fix matplotlib_date tests for matploltib>=3.3, skip basemap tests upon ImportError (due to incompatible matplotlib - basemap version combinations)

### LINKED ISSUE #2690: Test fails in UTCDateTime.matplotlib_date
Current master, see https://tests.obspy.org/111684/#3 and #2689 

e.g.
```
File "/home/runner/work/obspy/obspy/obspy/core/trace.py", line 2536, in obspy.core.trace.Trace.times
Failed example:
tr.times("matplotlib")
Expected:
array([ 733643.01392361, 733643.01392373, 733643.01392384, ...,
733643.01427049, 733643.0142706 , 733643.01427072])
Got:
array([ 14480.01392361, 14480.01392373, 14480.01392384, ...,
14480.01427049, 14480.0142706 , 14480.01427072])
```

### PR DESCRIPTION
**Pull request by trichter**
### What does this PR do?

fixes #2690
by checking the matplotlib version.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] ~~All tests still pass.~~ All tests now pass on travis for python>=3.6.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
Well need to remember to check if we need to migrate the changes you're doing to Travis to the new CI setup in master with github-actions..

**Comment by trichter** [comment]
Yeah, you are right. Anyway, `basemap>=1.2.2` conflicts with other setup requirements (see [ci result](https://travis-ci.org/github/obspy/obspy/jobs/723028982)). I'll use the skipIf decorator for the failing tests and drop the last commit 58f7253.

**Comment by trichter** [comment]
This PR now also skips the basemap tests upon ImportError. Looks ready.

**Review by megies — APPROVED** [review]
Looks good to me thanks!

**Comment by megies** [comment]
Merged into master too @trichter

**Comment by trichter** [comment]
Thanks!

**Pull request merged**
