### PR TITLE
sac read/write fixes: swapping bytes, missing header field. (cleanup)

### PR DESCRIPTION
**Pull request by claudiodsf**
This PR replaces #850, hopefully cleaning up the commit history.
It fixes some sac-related code:

  - byte swapping should work correctly now;
  - a header field was missing in the `IDICT`dictionary, implying that this field was aways written to disk as `0`;
  - a test in `tes_core.py` was pointless.

There is still a test failing (see https://github.com/obspy/obspy/pull/850#issuecomment-51202404).
I'm trying to figure this out (any help welcome :wink: )

### CODE REVIEW

**Comment by mbyt** [comment]
@claudiodsf we are on gitter, in case you would like to join: https://gitter.im/obspy/obspy

**Comment by claudiodsf** [comment]
A possible solution to failing test is this one:
https://gist.github.com/claudiodsf/24a640950555681a1348

(look at lines [57](https://gist.github.com/claudiodsf/24a640950555681a1348#file-test_waveform_plugins-py-L57) and [119](https://gist.github.com/claudiodsf/24a640950555681a1348#file-test_waveform_plugins-py-L119))

What do you think?

**Comment by mbyt** [comment]
Yes, let's go this way. Can you commit?

**Comment by claudiodsf** [comment]
Good to merge for me :wink:

**Comment by mbyt** [comment]
travis passed, great!

In it goes.

**Comment by claudiodsf** [comment]
Great, thanks!

**Pull request merged**
