### PR TITLE
Mission "clean test logs" - handles all kind of userwarnings/deprecation warnings

### PR DESCRIPTION
**Pull request by barsch**
WIP

### CODE REVIEW

**Comment by megies** [comment]
This is such a pain to fix, I know. Awesome that you're working on it.

I think at some point we need some check that makes sure no PR adds any more of such crap stdout output..

**Comment by barsch** [comment]
IMHO good to review

two remaining issues:
1. ```UserWarning``` which I can't reproduce on Windows:
    ```
    /home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/obspy/io/xseed/parser.py:1374: UserWarning: Epoch TW.TATO..BHE [1994-10-01T00:00:00.000000Z - 2599-12-31T23:59:59.000000Z]: Response stage 7 does not end with blockette 58. Proceed at your own risk.
    
      warnings.warn(_epoch_warn_msg(msg))```
    see https://travis-ci.org/obspy/obspy/jobs/275014003

2. something related to Imgur? which I also can't reproduce
    ```
    C:\Miniconda36-x64\envs\test\lib\socket.py:657: ResourceWarning: unclosed <socket.socket fd=2988, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.104', 1083), raddr=('151.101.184.193', 443)>
      self._sock = None```
    see https://ci.appveyor.com/project/obspy/obspy/build/1.0.5146-master/job/xpj9cfn2a2t5wxuw

**Comment by krischer** [comment]
I rebased on master and fixed the first warning which I could reproduce.

I also cannot reproduce the second one:

> something related to Imgur? which I also can't reproduce
> 
> C:\Miniconda36-x64\envs\test\lib\socket.py:657: ResourceWarning: unclosed <socket.socket fd=2988, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.104', 1083), raddr=('151.101.184.193', 443)>
>   self._sock = None
> 
> see https://ci.appveyor.com/project/obspy/obspy/build/1.0.5146-master/job/xpj9cfn2a2t5wxuw

**Comment by barsch** [comment]
good to merge?

**Pull request merged**
