### PR TITLE
Fix to stop conversion of None to 'None' in sc3ml read inventory

### PR DESCRIPTION
**Pull request by Jollyfant**
Raises ValueError when `read_inventory(format="sc3ml")` is issued for a file that is not the supported SC3ML version. Includes test coverage.

See #1536

### CODE REVIEW

**Comment by megies** [comment]
Hmm.. we usually don't do that. This would prevent users from forcing a data format during reading that is not properly recognized (by `_is_...`) but still readable (by `_read_...`)..

**Comment by Jollyfant** [comment]
If a file is readable through `_read_...` but not properly recognized by `_is_...` that is a problem that needs to be addressed in the latter function surely? 

If there are exceptions, we can add it in `_is_...`. However, the XML format must be according to some schema, and exceptions shouldn't exist in the first place.

**Comment by megies** [comment]
> If a file is readable through _read_... but not properly recognized by _is_... that is a problem that needs to be addressed in the latter function surely?

Yes, absolutely. But while it is (hopefully) being addressed in `master` (i.e. in the dynamic developer regime), users with the latest (or other) release version installed (i.e. in the static user regime) can not read the file simply because it is prevented in the reading routine although it might work. Remember, the `_read_XXX` function are only ever called if..
 - the `_is_XXX` detects the file format during plugin traversal in autodetection and prompts the read routine, or..
 - the `_read_XXX` is *explicitly` requested by the user (be it by specifying `format="XXX"` or by tinkering with low-level routine itself).

In the second case this is an *explicit* call and as such should not be prevented by hard coding, IMHO.

**Comment by Jollyfant** [comment]
Ok, I get what you are saying now..

Users would normally not specify `format="SC3ML"` or `format="stationXML"` during a read and let the auto-detection do its job. And if someone wants to be stubborn and import stationXML as SC3ML we let them.

**Comment by megies** [comment]
> Users would normally not specify format="SC3ML" or format="stationXML" during a read and let the auto-detection do its job. And if someone wants to be stubborn and import stationXML as SC3ML we let them.

Exactly. And it's not about being stubborn in some cases but just the `_is` routine being buggy but the `_read` routine working properly at the same time. We had cases like that already..



> Btw, I do not understand what you mean with static vs dynamic developer regime.

Just saying, if you hardcode it like here, a user has no chance to force the reading without either tinkering in the installed codes or installing a developer snapshot -- which is usually unwanted and even impossible for some unsavvy users.

**Comment by Jollyfant** [comment]
I agree with your philosophy and will revert the change, and use this pull to make a different small bug fix as demonstrated in the last commit.

**Comment by Jollyfant** [comment]
Modified test for better coverage. If they pass this can be reviewed and merged.

**Comment by krischer** [comment]
I manually cherry-picked 61c93a4d589a504dcadaf0f40242e4cfea03e065 and 68a75e4bef8716ca2cd70aa2bbfb99aa714d36f2 on top of the `maintenance_1.0.x` branch.

**Pull request closed without merging**
