### PR TITLE
HTTP for the examples

### PR DESCRIPTION
**Pull request by krischer**
As we currently have an expired certificate and this results in most CI failing I changed all the examples to use the HTTP version of our examples server. I don't see any harm in that but maybe I am mistaken.

### CODE REVIEW

**Comment by megies** [comment]
This currently also crashes our docs builds, I'm also 👍 for HTTP..

**Comment by megies** [comment]
Gonna merge this for now, so that current docs can be built again.. if anybody's opposing this change please open a follow-up.

**Comment by QuLogic** [comment]
I don't particularly like that the documentation links were changed too.

**Comment by krischer** [comment]
Fair enough - now that it works again I'd be fine with reverting this whole PR. We had to change this as doc building also no longer works.

**Pull request merged**
