### PR TITLE
.clients.fdsn: update INGV entry in URL mapping

### PR DESCRIPTION
**Pull request by petrrr**
### What does this PR do?

Minor update of the FDSN endpoint URL.

### Why was it initiated?  Any relevant Issues?

The recommended  URL was changed, the old URL is deprecated.

### PR Checklist
- [X] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

I believe most of these are rather irrelevant for this minor change.

### CODE REVIEW

**Comment by megies** [comment]
You'll also have to adjust the FDSN `__init__.py` doctest, I think, line 43.

**Comment by megies** [comment]
+TESTS:clients.fdsn

Travis is just not failing right now because fdsn wasn't tested, see above comment.

**Comment by megies** [comment]
Merging.

**Comment by petrrr** [comment]
@megies: I just realized that there is one more occurrence in the test. How should we fix this?

```
--- a/obspy/clients/fdsn/tests/test_client.py
+++ b/obspy/clients/fdsn/tests/test_client.py
@@ -97,7 +97,7 @@ class ClientTestCase(unittest.TestCase):
         test_urls_valid += [
             "http://arclink.ethz.ch",
             "http://example.org",
-            "https://webservices.rm.ingv.it",
+            "https://webservices.ingv.it",
             "http://localhost:8080/test/",
             "http://93.63.40.85/",
             "http://[::1]:80/test/",
```

**Comment by megies** [comment]
Uhm.. you're looking at the diff of the commit that I added in order to fix this (and I pointed this out earlier in my first comment)?

**Comment by petrrr** [comment]
It's a different file. The diff above is for `obspy/clients/fdsn/tests/test_client.py`. In 907d72d  you corrected fixed  `obspy/clients/fdsn/__init__.py`.

But I now realize that this is not really relevant. These URLs are just used to test a regex which validates URLs, but they are fake anyway. Sorry for the fuss.

**Comment by megies** [comment]
Ah, OK, missed the fact that was from a different file. But yeah, if they're just used for this other regex test than  it doesn't matter. :-)

**Pull request merged**
