### PR TITLE
Update to libmseed 2.16

### PR DESCRIPTION
**Pull request by QuLogic**
https://seiscode.iris.washington.edu/news/37

### CODE REVIEW

**Comment by mbyt** [comment]
Seems like 9969ee0546d349e16e7ba7cb3dab73455520aed1 breaks windows compatibility:
```
cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DWIN32=1 -IC:\conda\envs\test\lib\site-packages\numpy\core\include -IC:\conda\envs\test\include -IC:\conda\envs\test\PC /Tcobspy\io\mseed\src\obspy-readbuffer.c /Fobuild\temp.win-amd64-2.7\Release\obspy\io\mseed\src\obspy-readbuffer.obj
obspy-readbuffer.c
c:\projects\obspy\obspy\io\mseed\src\libmseed\lmplatform.h(51) : fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory
error: Command "cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DWIN32=1 -IC:\conda\envs\test\lib\site-packages\numpy\core\include -IC:\conda\envs\test\include -IC:\conda\envs\test\PC /Tcobspy\io\mseed\src\obspy-readbuffer.c /Fobuild\temp.win-amd64-2.7\Release\obspy\io\mseed\src\obspy-readbuffer.obj" failed with exit status 2
Command exited with code 1
```

**Comment by ThomasLecocq** [comment]
isn't it becuase of ``-DWIN32=1``  on your x64 machine ?

**Comment by mbyt** [comment]
Unfortunately I do not have a windows machine available. The above output is just a paste from the failing appveyor build (https://github.com/obspy/obspy/pull/1044#), while the build recipe was not touched in the PR.

**Comment by ThomasLecocq** [comment]
I'm on windows, how do I run the test/build?

**Comment by mbyt** [comment]
The actual problem is that `inttypes.h` are not available on windows or at least in our appveyor setup.

**Comment by mbyt** [comment]
Just checkout the PR and run python setup.py develop. I assume this will fail already.

**Comment by ThomasLecocq** [comment]
uhmmm... "check out the PR"... looking how to do that :)

**Comment by ThomasLecocq** [comment]
works on my machine... but I have TDM-GCC (gcc & others for windows, with more support (openmp etc) than the gcc provided with anaconda) installed so I'm not sure if that is the cause.

**Comment by ThomasLecocq** [comment]
A difference between AppVeyor and my machine is:

AppVeyor
´´´
writing manifest file 'obspy.egg-info\SOURCES.txt'
running build_ext
No module named msvccompiler in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
building 'libgse2_Windows_64bit_py27' extension
compiling C sources
´´´

My box:
´´´
writing manifest file 'obspy.egg-info\SOURCES.txt'
running build_ext
Looking for python27.dll
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
building 'libgse2_Windows_64bit_py27' extension
compiling C sources
´´´

visibly the msvccompiler stuff is absent.. could be an issue (meaning headers etc have to be used), where the .h are not used on my box it seems...

**Comment by mbyt** [comment]
Good to hear. This means that this issue is specific to MSVC.

@CTrabant any idea how to deal with this? We could ship our own `inttypes.h` or we need a C pre-processor directive like
```C
#if defined(_MSC_VER)
  typedef signed char int8_t;
  typedef unsigned char uint8_t;
  typedef signed short int int16_t;
  typedef unsigned short int uint16_t;
  typedef signed int int32_t;
  typedef unsigned int uint32_t;
  typedef signed __int64 int64_t;
  typedef unsigned __int64 uint64_t;
#else
  #include <inttypes.h>
#endif
```
Not sure though if `_MSC_VER` is the correct define for MSVC.

**Comment by QuLogic** [comment]
MSVC sucks at C support; I don't think it's even close to C99 yet. You could use [this](https://code.google.com/p/msinttypes/), maybe.

**Comment by CTrabant** [comment]
> Good to hear. This means that this issue is specific to MSVC.
> @CTrabant <https://github.com/CTrabant> any idea how to deal with this? We could ship our own inttypes.h or we need a C pre-processor directive like
> 
Do we know what version of MSVC is running on AppVeyor?

We should be able to create a define for those types for older MSVC versions that need it.  I was really hoping to avoid that.

> On May 10, 2015, at 5:06 PM, Elliott Sales de Andrade <notifications@github.com> wrote:
> MSVC sucks at C support; I don't think it's even close to C99 yet. You could use this <https://code.google.com/p/msinttypes/>, maybe.
> 

Indeed.

I believe the integer type headers are included in MSVC 2010 and later, that's something at least.

**Comment by megies** [comment]
> Do we know what version of MSVC is running on AppVeyor?

http://www.appveyor.com/docs/build-phase#caveats

Seems there is control over MSVC version in Appveyor?

**Comment by QuLogic** [comment]
Based on [this post](http://herbsutter.com/2012/05/03/reader-qa-what-about-vc-and-c99/), it seems that MSVC 2010 would have C99 features, but _only_ if you compile with the C++ compiler. MSVC 2013 seems to have [nearly full support for C99 library bits](http://blogs.msdn.com/b/vcblog/archive/2013/07/19/c99-library-support-in-visual-studio-2013.aspx). Based on [ffmpeg build instructions](https://www.ffmpeg.org/platform.html#Microsoft-Visual-C_002b_002b-or-Intel-C_002b_002b-Compiler-for-Windows), it seems that 2013 is sufficient to build in C99 mode (at least for what's in libmseed.) Moving further along, it seems like MS had an about-face on C99+ support...

I've set the environment variables that @megies found to MSVC 2013; let's see how it does this time.

**Comment by ThomasLecocq** [comment]
fails...

I really think the problem is https://ci.appveyor.com/project/obspy/obspy/build/1.0.494-master#L223 , this doesn't occur on my machine. So there must be some path/thing issue linked to that!

**Comment by krischer** [comment]
For Python there really is not much choice on windows. If building against the official Python 2.7 windows distribution, this here must be used: http://www.microsoft.com/en-us/download/details.aspx?id=44266

Anaconda might be different, but we will have to support the aforementioned compiler.

**Comment by QuLogic** [comment]
Of course, setting that environment variables was only useful if running AppVeyor's own MSBuild scripts. I don't seem to have much luck overriding it yet.

@krischer I was hoping that only applied to "real" extensions, i.e., one's that actually use Python API...

**Comment by QuLogic** [comment]
Well, it worked, but maybe we should check with our Windows packagers about this one... It'll be a pain for anyone who builds from source to get both MSVC versions.

**Comment by krischer** [comment]
Can we not just add the previously mentioned defines?

**Comment by mbyt** [comment]
See:
* https://docs.python.org/devguide/setup.html#windows
* https://github.com/cython/cython/wiki/CythonExtensionsOnWindows#using-windows-sdk-cc-compiler-older-method

To sum up. Python extensions for python 2.7 shall be build with MSVC 2008 (the download link @krischer) provided.

All other versions are not guaranteed to work. As far as I remember, this is what @barsch told me, too.

I do not see a reason why to break this guaranteed compatibility and risk hard to trace bugs.

Therefore, I propose to revert  de5283269727e44e391fd486b88d23bd254287d2 and try to get the defines upstream. I this is not an option I'd vote for locally patch libmseed, as we will probably need to support python 2.7 a few more years.

**Comment by CTrabant** [comment]
> I really think the problem is https://ci.appveyor.com/project/obspy/obspy/build/1.0.494-master#L223 <https://ci.appveyor.com/project/obspy/obspy/build/1.0.494-master#L223> , this doesn't occur on my machine. So there must be some path/thing issue linked to that!

The output indicates MS Visual Studio 9.0, aka probably Visual C++ 2008, which we should not expect to have C99 defines.  Bummer.

I would be willing to roll a change into the source lmplatform.h for older versions of MSVC based on the value of _MSV_VER (http://sourceforge.net/p/predef/wiki/Compilers/#microsoft-visual-c).  But I do not have immediate access to a Windows box for testing.

If someone is willing to try out the patch to libmseed/lmplatform.h below and provide feedback it would be appreciated.

-------------------------

--- lmplatform.h.orig	2015-05-12 11:58:08.000000000 -0700
+++ lmplatform.h	2015-05-12 12:05:56.000000000 -0700
@@ -48,7 +48,6 @@
 #include <stdlib.h>
 #include <stdio.h>
 #include <stdarg.h>
-#include <inttypes.h>
 #include <time.h>
 #include <string.h>
 #include <ctype.h>
@@ -59,16 +58,19 @@
   #define LMP_GLIBC2 1 /* Deprecated */
 
   #include <unistd.h>
+  #include <inttypes.h>
 
 #elif defined(__sun__) || defined(__sun)
   #define LMP_SOLARIS 1
 
   #include <unistd.h>
+  #include <inttypes.h>
 
 #elif defined(__APPLE__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__)
   #define LMP_BSD 1
 
   #include <unistd.h>
+  #include <inttypes.h>
 
 #elif defined(WIN32) || defined(WIN64)
   #define LMP_WIN 1
@@ -77,6 +79,20 @@
   #include <windows.h>
   #include <sys/types.h>
 
+  /* For pre-MSVC 2010 define standard int types, otherwise use inttypes.h */
+  #if _MSC_VER < 1600
+    typedef signed char int8_t;
+    typedef unsigned char uint8_t;
+    typedef signed short int int16_t;
+    typedef unsigned short int uint16_t;
+    typedef signed int int32_t;
+    typedef unsigned int uint32_t;
+    typedef signed __int64 int64_t;
+    typedef unsigned __int64 uint64_t;
+  #else
+    #include <inttypes.h>
+  #endif
+
   #if defined(_MSC_VER)
     #define snprintf _snprintf
     #define vsnprintf _vsnprintf

**Comment by QuLogic** [comment]
> Can we not just add the previously mentioned defines?

Oh, of course, we should do that; just waiting to see what sort of change @CTrabant applies upstream.

> To sum up. Python extensions for python 2.7 shall be build with MSVC 2008 (the download link @krischer) provided.

Yes, but technically, we do not build Python _extensions_. They are simply regular DLLs that happen to be loaded by Python.

**Comment by QuLogic** [comment]
> If someone is willing to try out the patch to libmseed/lmplatform.h below and provide feedback it would be appreciated.

Our quickest hope is to try it out on AppVeyor, most likely.

**Comment by mbyt** [comment]
7cc9ad1feb99eebffd5e624d6a08defef8a7adce introduces the patch CTrabant provided in https://github.com/obspy/obspy/pull/1044#issuecomment-101391115.

Let's see what appveyor says.

**Comment by QuLogic** [comment]
That patch forgot the `printf` identifiers that are also in `inttypes.h`...

**Comment by mbyt** [comment]
The error message is:
```
cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DWIN32=1 -IC:\conda\envs\test\lib\site-packages\numpy\core\include -IC:\conda\envs\test\include -IC:\conda\envs\test\PC /Tcobspy\io\mseed\src\libmseed\fileutils.c /Fobuild\temp.win-amd64-2.7\Release\obspy\io\mseed\src\libmseed\fileutils.obj
fileutils.c
obspy\io\mseed\src\libmseed\fileutils.c(337) : warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Include\string.h(157) : see declaration of 'strncpy'
obspy\io\mseed\src\libmseed\fileutils.c(346) : warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Include\stdio.h(237) : see declaration of 'fopen'
obspy\io\mseed\src\libmseed\fileutils.c(348) : warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Include\string.h(126) : see declaration of 'strerror'
obspy\io\mseed\src\libmseed\fileutils.c(360) : warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Include\string.h(126) : see declaration of 'strerror'
obspy\io\mseed\src\libmseed\fileutils.c(379) : warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Include\string.h(126) : see declaration of 'strerror'
obspy\io\mseed\src\libmseed\fileutils.c(423) : error C2146: syntax error : missing ')' before identifier 'PRId64'
obspy\io\mseed\src\libmseed\fileutils.c(424) : error C2059: syntax error : ')'
obspy\io\mseed\src\libmseed\fileutils.c(475) : error C2146: syntax error : missing ')' before identifier 'SCNd64'
obspy\io\mseed\src\libmseed\fileutils.c(475) : error C2059: syntax error : ')'
obspy\io\mseed\src\libmseed\fileutils.c(484) : error C2146: syntax error : missing ')' before identifier 'PRId64'
obspy\io\mseed\src\libmseed\fileutils.c(507) : error C2146: syntax error : missing ')' before identifier 'PRId64'
obspy\io\mseed\src\libmseed\fileutils.c(521) : error C2146: syntax error : missing ')' before identifier 'PRId64'
obspy\io\mseed\src\libmseed\fileutils.c(586) : error C2146: syntax error : missing ')' before identifier 'PRId64'
obspy\io\mseed\src\libmseed\fileutils.c(589) : error C2146: syntax error : missing ')' before identifier 'PRId64'
obspy\io\mseed\src\libmseed\fileutils.c(600) : error C2146: syntax error : missing ')' before identifier 'PRId64'
obspy\io\mseed\src\libmseed\fileutils.c(673) : error C2146: syntax error : missing ')' before identifier 'PRId64'
obspy\io\mseed\src\libmseed\fileutils.c(676) : error C2146: syntax error : missing ')' before identifier 'PRId64'
obspy\io\mseed\src\libmseed\fileutils.c(979) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
error: Command "cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DWIN32=1 -IC:\conda\envs\test\lib\site-packages\numpy\core\include -IC:\conda\envs\test\include -IC:\conda\envs\test\PC /Tcobspy\io\mseed\src\libmseed\fileutils.c /Fobuild\temp.win-amd64-2.7\Release\obspy\io\mseed\src\libmseed\fileutils.obj" failed with exit status 2
Command exited with code 1
```

**Comment by CTrabant** [comment]
Thanks for the testing @mbyt and Elliot.  Willing to try again?

New patch for lmplatform.h to define the PRId64 and SCNd64 macros missing from older MSVC.

Also a small cast in fileutils.c to squash a warning.

===================================================================
--- lmplatform.h	(revision 12302)
+++ lmplatform.h	(working copy)
@@ -48,7 +48,6 @@
 #include <stdlib.h>
 #include <stdio.h>
 #include <stdarg.h>
-#include <inttypes.h>
 #include <time.h>
 #include <string.h>
 #include <ctype.h>
@@ -59,16 +58,19 @@
   #define LMP_GLIBC2 1 /* Deprecated */
 
   #include <unistd.h>
+  #include <inttypes.h>
 
 #elif defined(__sun__) || defined(__sun)
   #define LMP_SOLARIS 1
 
   #include <unistd.h>
+  #include <inttypes.h>
 
 #elif defined(__APPLE__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__)
   #define LMP_BSD 1
 
   #include <unistd.h>
+  #include <inttypes.h>
 
 #elif defined(WIN32) || defined(WIN64)
   #define LMP_WIN 1
@@ -77,7 +79,28 @@
   #include <windows.h>
   #include <sys/types.h>
 
+  /* For pre-MSVC 2010 define standard int types, otherwise use inttypes.h */
+  #if _MSC_VER < 1600
+    typedef signed char int8_t;
+    typedef unsigned char uint8_t;
+    typedef signed short int int16_t;
+    typedef unsigned short int uint16_t;
+    typedef signed int int32_t;
+    typedef unsigned int uint32_t;
+    typedef signed __int64 int64_t;
+    typedef unsigned __int64 uint64_t;
+  #else
+    #include <inttypes.h>
+  #endif
+
   #if defined(_MSC_VER)
+    #if !defined(PRId64)
+      #define PRId64 "I64d"
+    #endif
+    #if !defined(SCNd64)
+      #define SCNd64 "I64d"
+    #endif
+
     #define snprintf _snprintf
     #define vsnprintf _vsnprintf
     #define strcasecmp _stricmp

===================================================================
--- fileutils.c	(revision 12302)
+++ fileutils.c	(working copy)
@@ -976,7 +976,7 @@
 {
   int read = 0;
   
-  read = fread (buf, size, num, stream);
+  read = (int) fread (buf, size, num, stream);
   
   if ( read <= 0 && size && num )
     {

**Comment by QuLogic** [comment]
> + read = (int) fread (buf, size, num, stream);
> if ( read <= 0 && size && num )

I don't think `fread` returns an int, or negative number, so I'm not sure about this one?

**Comment by QuLogic** [comment]
Actually, I'm not really sure why `ms_fread` exists. It is only called in one place, and that caller checks the return value and `feof` too. Maybe it's left-over from something else?

**Comment by QuLogic** [comment]
One other thing, `#if _MSC_VER < 1600` when `_MSC_VER` is undefined will be true, but I _think_ you would prefer to just use the `inttypes.h` header with MinGW, wouldn't you?

**Comment by CTrabant** [comment]
> On May 12, 2015, at 2:58 PM, Elliott Sales de Andrade <notifications@github.com> wrote:
> 
> read = (int) fread (buf, size, num, stream); if ( read <= 0 && size && num )
> I don't think fread returns an int, or negative number, so I'm not sure about this one?
> 
fread() returns a size_t but the read variable is an int, the cast tells the compiler that we know the conversion is happening, do not complain.  In this code base fread() should never be called to read a number of bytes greater than can be represented by a signed 32-bit integer (aka 2 GiB), in fact the read size cannot be larger than MAXRECLEN (currently 1 MiB).  So converting the potentially larger size_t to int is safe.

Yes, the test for negative values is not needed on perfectly compliant systems, but it doesn't hurt.

**Comment by QuLogic** [comment]
I understand the cast; I just don't think it's necessary at that point. Checking for negative values is not a problem in itself, but the check doesn't seem correct. An error (or EOF) occurred if `read < num`, not if `read == 0`. The _one_ caller of `ms_fread` correctly checks this condition, so again, I'm not sure why the `ms_fread` function is necessary.

**Comment by QuLogic** [comment]
BTW, build is passing with new patch!

**Comment by CTrabant** [comment]
> One other thing, #if _MSC_VER < 1600 when _MSC_VER is undefined will be true, but I think you would prefer to just use the inttypes.h header with MinGW, wouldn't you?
> 
Good catch, thanks.  Below is an updated patch to avoid that pitfall.

I tried out the MS Visual C++ 2008 compiler for Python and it seems to work fine and also tried MinGW, Cygwin, MSVC 2013, Open Watcom.

===================================================================
--- lmplatform.h	(revision 12302)
+++ lmplatform.h	(working copy)
@@ -48,7 +48,6 @@
 #include <stdlib.h>
 #include <stdio.h>
 #include <stdarg.h>
-#include <inttypes.h>
 #include <time.h>
 #include <string.h>
 #include <ctype.h>
@@ -59,16 +58,19 @@
   #define LMP_GLIBC2 1 /* Deprecated */
 
   #include <unistd.h>
+  #include <inttypes.h>
 
 #elif defined(__sun__) || defined(__sun)
   #define LMP_SOLARIS 1
 
   #include <unistd.h>
+  #include <inttypes.h>
 
 #elif defined(__APPLE__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__)
   #define LMP_BSD 1
 
   #include <unistd.h>
+  #include <inttypes.h>
 
 #elif defined(WIN32) || defined(WIN64)
   #define LMP_WIN 1
@@ -77,7 +79,28 @@
   #include <windows.h>
   #include <sys/types.h>
 
+  /* For pre-MSVC 2010 define standard int types, otherwise use inttypes.h */
+  #if defined(_MSC_VER) && _MSC_VER < 1600
+    typedef signed char int8_t;
+    typedef unsigned char uint8_t;
+    typedef signed short int int16_t;
+    typedef unsigned short int uint16_t;
+    typedef signed int int32_t;
+    typedef unsigned int uint32_t;
+    typedef signed __int64 int64_t;
+    typedef unsigned __int64 uint64_t;
+  #else
+    #include <inttypes.h>
+  #endif
+
   #if defined(_MSC_VER)
+    #if !defined(PRId64)
+      #define PRId64 "I64d"
+    #endif
+    #if !defined(SCNd64)
+      #define SCNd64 "I64d"
+    #endif
+
     #define snprintf _snprintf
     #define vsnprintf _vsnprintf
     #define strcasecmp _stricmp

**Comment by celso-iris** [comment]
Meant to add: I will roll that last patch into a new libmseed release after confirmation that it works for ObsPy.

**Comment by CTrabant** [comment]
> On May 12, 2015, at 3:34 PM, Elliott Sales de Andrade <notifications@github.com> wrote:
> I understand the cast; I just don't think it's necessary at that point. Checking for negative values is not a problem in itself, but the check doesn't seem correct. An error (or EOF) occurred if read < num, not if read == 0. The one caller of ms_fread correctly checks this condition, so again, I'm not sure why the ms_fread function is necessary.
> 
The cast is intended to quiet the MSVC warning about converting the size_t to an int and potentially overflowing.  I never saw that warning in my own tests, I'm guessing it comes up in the 64-bit build where size_t is much bigger than int (my Windows test environment is 32-bit).

ms_fread() exists for historical reasons, it used to be called from multiple places and in already complicated code.  In its current form it correctly checks for errors, when read == 0 and non-zero was requested (size and num are non-zero), and then logs an error.  It leaves the determination of a short read (getting back less than requested) up to the caller.  Why?  The caller knows and can print the byte offset from which the read started which can be very useful when looking at corrupt miniSEED.  The thing this logic is missing is any error message on a short reads when the end of the file has been reached, any such incomplete trailing data is quietly ignored.

If the test in ms_fread() was changed to read != num it would then trap any short reads, and the logged message would not include the byte offset.  It could be rearranged to put this logic all back into the now single caller.  I have not done this because the code is stable and function overhead is probably nothing as most compilers probably inline ms_fread().  Maybe someday.

BTW, I think we are now off topic for an ObsPy list.  You're testing and scrutiny are welcome and you may send feedback to me directly or submit tickets at:
https://seiscode.iris.washington.edu/projects/libmseed

**Comment by QuLogic** [comment]
I think we're on the same page regarding its utility. Stability reasons are usually a good reason not to touch stuff. :wink:

**Comment by QuLogic** [comment]
Looks like everything's clear now.

**Comment by CTrabant** [comment]
libmseed 2.16m released with the tested changes:
https://seiscode.iris.washington.edu/news/43

Download:
https://seiscode.iris.washington.edu/projects/libmseed/files

**Comment by QuLogic** [comment]
It doesn't look like there's any reason not to merge this one.

**Pull request merged**
