### PR TITLE
SDS: Continue get_all_stations() when invalid channel codes are encountered

### PR DESCRIPTION
**Pull request by FMassin**
### What does this PR do?

Adding `TypeError` in `get_all_stations` allows to have weird channels name in filenames like `1967/XX/WEIRD/D-6.D` without crashing ...

### Why was it initiated?  Any relevant Issues?

Because I have a channel code called `D-6` and it crashes `obspy-sds-report`.

### PR Checklist
- [ ] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
Since this is failing in the (network, station) lookup routine another option would be to make the lookup in there only try to match those two, then you could lookup the station without bothering about the "invalid" channel code.

If sticking to this approach I'll add a small change to be a little more specific in catching the exception

**Comment by FMassin** [comment]
> Since this is failing in the (network, station) lookup routine another option would be to make the lookup in there only try to match those two, then you could lookup the station without bothering about the "invalid" channel code.

That sounds like a good design idea, but then the risk is to consider stations that actually don't have any valid seedids... please do as you want, maybe I should have open an issue instead of trying to fix the code myself. 

> If sticking to this approach I'll add a small change to be a little more specific in catching the exception

I wouldn't feel ashamed if you decide to follow your own way. This should be called a "Pull suggestion" instead of a request :)

**Comment by megies** [comment]
@FMassin nah, all good, I'm fine with it is right now.

**Comment by megies** [comment]
I guess this could actually go into maintenance branch, actually

**Comment by FMassin** [comment]
Anything I should do?

**Comment by megies** [comment]
I did it real quick

**Comment by megies** [comment]
I'd say ready to merge when CI looks ok

**Pull request merged**
