### PR TITLE
Hacky fix for reading SC3 ArclinkXML where publicID has slash instead…

### LINKED ISSUE #2552: UnboundLocalError while reading an inventory
Hi ! 

I loaded some station.xml files from a datacenter using Arclink, and I got an error while loading them with obspy.

Here is the code: 

```python
from obspy import read_inventory
read_inventory("data/UB.XXXX.xml")
```

Here is the error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\decorator.py:decorator-gen-45>", line 2, in read_inventory
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\core\util\decorator.py", line 301, in _map_example_filename
    return func(*args, **kwargs)
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\core\inventory\inventory.py", line 98, in read_inventory
    format=format, *args, **kwargs)[0]
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\core\util\base.py", line 459, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\io\arclink\inventory.py", line 151, in _read_inventory_xml
    networks.append(_read_network(root, net_element))
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\io\arclink\inventory.py", line 217, in _read_network
    stations.append(_read_station(inventory_root, sta_element))
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\io\arclink\inventory.py", line 272, in _read_station
    channels.append(_read_channel(inventory_root, channel))
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\io\arclink\inventory.py", line 460, in _read_channel
    response_element, cha_element,
UnboundLocalError: local variable 'response_element' referenced before assignment
```

This error happens with obspy 1.1.0 and 1.1.1, python 3.5 and 3.7.
I was able to load Station XML files from GEOSCOPE network. 

It seems that the error would come from my XML file, I do not know what are the next debug steps to follow. 

Here is the file: https://framabin.org/p/?63afac071754cd9d#RyZL4euIFktS6l2RgYP5hqk3VxMyp+TCEBnK7dLfGkg=

Do you have any idea ? Could my XML be in a special format that is not handle by obspy ? 

Thank you !

### PR DESCRIPTION
**Pull request by Jollyfant**
… of shebang

### What does this PR do?

Fixes #2552 where PublicID is delimited by `/` instead of `#`.

### Why was it initiated?  Any relevant Issues?

*Please fill in*

### PR Checklist
- [ ] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by Jollyfant** [comment]
Have some problems running `io.arclink` tests with storage format change. Not sure what causes that regression.

**Comment by megies** [comment]
Can you please add a changelog one-liner? Otherwise good to go looks like.

**Comment by Jollyfant** [comment]
This should go in to master and make it for 1.2.0rc4 right

**Comment by megies** [comment]
> This should go in to master and make it for 1.2.0rc4 right

Yes

**Pull request merged**
