### PR TITLE
Precision issue of floating point second (i.e. microsecond) initialization in UTCDateTime

### PR DESCRIPTION
**Pull request by krischer**
Before:

```python
>>> from obspy import UTCDateTime
>>> d1 = UTCDateTime(2011,  1, 25, 15, 32, 12.26)
>>> d2 = UTCDateTime("2011-01-25T15:32:12.26")
>>> print(d1.formatIRISWebService())
2011-01-25T15:32:12.259
>>> print(d2.formatIRISWebService())
2011-01-25T15:32:12.260
```

After:

```python
>>> from obspy import UTCDateTime
>>> d1 = UTCDateTime(2011,  1, 25, 15, 32, 12.26)
>>> d2 = UTCDateTime("2011-01-25T15:32:12.26")
>>> print(d1.formatIRISWebService())
2011-01-25T15:32:12.260
>>> print(d2.formatIRISWebService())
2011-01-25T15:32:12.260
```

### CODE REVIEW

**Comment by megies** [comment]
:+1: for above fix.

But.. problem exists for different methods as well:
```python
d1 = UTCDateTime(2011,01,25,15,32,12.26,  precision = 2)
d2 = UTCDateTime("2011-01-25T15:32:12.26", precision = 2)
print d1.format_seed()
print d1.isoformat()
print d2.format_seed()
print d2.isoformat()
```
```python
2011,025,15:32:12.2599
2011-01-25T15:32:12.259999
2011,025,15:32:12.2600
2011-01-25T15:32:12.260000
```

**Comment by megies** [comment]
I've dug into this and I think the original fix was only fixing a symptom of an underlying issue (as suspected earlier). @krischer if you agree, the original fix and its revert should be removed in a rebase (changelog/doc can be squashed).

**Comment by megies** [comment]
Rebased, so that CI can work on this..

**Comment by megies** [comment]
@krischer, CI says yeah, so I'm gonna rebase/squash and merge this PR. If anything else comes up can be fixed directly on `releases` afterwards.

**Comment by megies** [comment]
Travis fail unrelated, see PythonCharmers/python-future#162.

**Comment by krischer** [comment]
:+1: Thanks for this. Logic looks sound and definitely a better solution than mine.

**Pull request merged**
