### PR TITLE
Fixed a bug where there were no zeros in a xml file.

### PR DESCRIPTION
**Pull request by aringler-usgs**
### What does this PR do?

This fixes a seiscomp station xml parsing issue where the poles and zeros might be empty.

It says there is a flake8 issue, but when I run flake8 I don't see anything.

```
======================================================================
FAIL: test_flake8 (obspy.core.tests.test_code_formatting.CodeFormattingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aringler/Documents/src/check_xml/obspy/obspy/core/tests/test_code_formatting.py", line 90, in test_flake8
    assert report.total_errors == 0
AssertionError

----------------------------------------------------------------------
```

### Why was it initiated?  Any relevant Issues?

This is the PR for ticekt #2633 

### PR Checklist
- [ X] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [X ] This PR is not directly related to an existing issue (which has no PR yet).
- [ X] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ X] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by aringler-usgs** [comment]
Shoot!  Did I mess up again with the branches?  Why am I soooo bad at git?  I only changed about 10 lines of code and it says I changed a whole bunch.

**Comment by heavelock** [comment]
You branched out from the current masters, that's the reason. No biggie to be honest. Just `git rebase  maintenance_1.2.x` and force push

**Comment by heavelock** [comment]
If you will have problems with potential conflicts, then it might be easier to cherry-pick. 

```
git fetch
git switch maintenance_1.2.x
git switch -c  fix_xmlzeros_second
git cherry-pick 5061314
git push
```
I wrote those without testing so there might be some syntax erros. Also, `switch` is quite recent, so you might want to use `checkout` and `checkout -b`

**Comment by aringler-usgs** [comment]
@heavelock  @jholland-usgs thanks for the git help.  I appear to have it fixed now.

**Comment by heavelock** [comment]
The code looks okay. How about adding a test case for that?

**Comment by aringler-usgs** [comment]
@heavelock Good call.  I pushed a simple one.  Let me know if you think this should include more cases or be different.  Thanks for looking at this.

**Comment by heavelock** [comment]
I think it's testing enough that problem. However, the test file is almost 100K, which is a bit too much for the test files. I butchered by hand that file and left one station with one stream, removing some excessive coefficients (also renaming the station to be obviously test case).

 The total weight is 5K now. Could you test if everything still works? Also, I renamed the test file to be test case specific. 

[zero_poles_and_zeros.zip](https://github.com/obspy/obspy/files/4835681/zero_poles_and_zeros.zip)

**Comment by heavelock** [comment]
O, and one more thing, could you add a one liner to the changelog.

**Comment by megies** [comment]
Good catch on the file size. Bonus points if you get the big file out of history, when replacing with the new file. You can do that in multiple ways. If the filename will be the same, then just commit the smaller file, then `git rebase -i maintenance_1.2.x` and move the new commit under the commit with the big file and select "fixup" for the commit with the reduced size and it'll combine the two together and the big file will vanish from history.

**Comment by aringler-usgs** [comment]
@heavelock thanks.  I will take care of this later today...  @megies why does "bonus points" give me the feeling that I have git exercise in front of me?  Thanks for all the help!

**Comment by megies** [comment]
>  @megies why does "bonus points" give me the feeling that I have git exercise in front of me?

:wink: don't worry, if its too much hassle i can fix it at the end before merging

**Comment by aringler-usgs** [comment]
@megies @heavelock I *think* I removed the file.  I might have messed something else up.  I apologize for messing this up.  The smaller file works.  Thanks for all the help!

**Comment by megies** [comment]
This branch looks really weird now, don't think I've ever seen this before. :rofl:  I'll clean it up and force push

**Comment by megies** [comment]
CI looks OK

**Pull request merged**
