### PR TITLE
Remove dynamic import rerouting, deprecated methods,  etc

### PR DESCRIPTION
**Pull request by megies**
It's time to get rid of all this dynamic import rerouting, deprecated methods, etcpp.

See #842, #999, #1039, #1246.

(-3530 lines ;-))

### CODE REVIEW

**Comment by krischer** [comment]
So much work and now its all gone again ;-) But YES! Get rid of that stuff!

**Comment by krischer** [comment]
Might also be a new record in files changes per commit ^^

**Comment by megies** [comment]
Not sure what this means: https://travis-ci.org/obspy/obspy/jobs/110591352#L654-L679

(taup/taup.py was removed)
screenshot from 2016-02-20 16 27 03

**Comment by krischer** [comment]
There was still a reference to the old `taup` wrapper in the `__init__.py`. I removed it as well as the test for the wrapper.

**Comment by QuLogic** [comment]
We don't really have a simple replacement for those two TauP functions. Also, don't forget the documentation; there are definitely some gallery examples of it.

**Comment by QuLogic** [comment]
Yea, that's fine actually, but the `travelTimePlot` seems nice anyway.

**Comment by krischer** [comment]
True. Let's rename it and but it somewhere else.

**Comment by megies** [comment]
Rebased + force-pushed.

**Comment by megies** [comment]
> True. Let's rename it and but it somewhere else.

Anything that still needs to be done here @krischer?

**Comment by krischer** [comment]
Yes I still have a number of things. I'm a bit short on time right now but I'll try to get it done this week.

**Comment by krischer** [comment]
Done. If CI passes it can IMHO be merged.

**Comment by megies** [comment]
What about the discussion around `getTravelTimes` and `travelTimePlot`? Any TODOs left there?

**Comment by megies** [comment]
Rebased + force-pushed

**Comment by QuLogic** [comment]
I'm not sure the `travelTimePlot` was restored?

**Comment by megies** [comment]
Uhm, sorry, thought everything was good to go..

**Pull request merged**
