### PR TITLE
reftek: fix putting together all traces in files with more than one "event" / fix VPU header field

### PR DESCRIPTION
**Pull request by megies**
Follow up to https://github.com/obspy/obspy/pull/1628#issuecomment-270989179.

Fixes reading files with multiple "events" in it. No changelog needed as reftek support is new in master.

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
@megies I can't send you the multiplexed "events" "continuous" data yet, it's not mine and I have to "anonymise" it first (remove location name, add fake coordinates, at least)...

Will try to do asap.

**Comment by megies** [comment]
Probably we don't even need new files.. if we combine the existing test data  with the new test data for #1628 (https://github.com/obspy/obspy/pull/1628/files#diff-42f5a46e126431083df7c2b32be14c5a) we might be able to concatenate the two during testing (in a BytesIO object).. (not sure if two different encodings in one read operation are covered yet though)

**Comment by kbouk** [comment]
Hello and sorry for the late response. I tested the PR release mentioned in #1628 and it works. However i tested also another reftek data source and i get the following errors:

File "<stdin>", line 1, in <module>
  File "<decorator-gen-31>", line 2, in read
  File "/opt/anaconda2/lib/python2.7/site-packages/obspy/core/util/decorator.py", line 294, in _map_example_filename
    return func(*args, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/obspy/core/stream.py", line 231, in read
    st.extend(_read(file, format, headonly, **kwargs).traces)
  File "<decorator-gen-32>", line 2, in _read
  File "/opt/anaconda2/lib/python2.7/site-packages/obspy/core/util/decorator.py", line 204, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/obspy/core/stream.py", line 273, in _read
    headonly=headonly, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/obspy/core/util/base.py", line 466, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/obspy/io/reftek/core.py", line 102, in _read_reftek130
    verbose=verbose)
  File "/opt/anaconda2/lib/python2.7/site-packages/obspy/io/reftek/core.py", line 239, in to_stream
    eh = EHPacket(eh_packets[0])
  File "/opt/anaconda2/lib/python2.7/site-packages/obspy/io/reftek/packet.py", line 145, in __init__
    data = converter(data)
  File "/opt/anaconda2/lib/python2.7/site-packages/obspy/io/reftek/util.py", line 120, in _16_tuple_int
    result.append(int(chars))
  File "/opt/anaconda2/lib/python2.7/site-packages/future/types/newint.py", line 76, in __new__
    return super(newint, cls).__new__(cls, val)
ValueError: invalid literal for long() with base 10: '2.400'

I am attaching the corresponding data (one day). Let me know if you want more data, there is no problem.
[reftek_test_data_noa.tar.gz](https://github.com/obspy/obspy/files/693833/reftek_test_data_noa.tar.gz)

Thank you and best regards,

Kostas Boukouras

**Comment by megies** [comment]
> and i get the following errors:

I overlooked a detail in the reftek 130 packet descriptions. Some fields are specified as `ASCII digits` and most of the times that is equivalent with integer values, but sometimes there's a `FP` in the value description, standing for "floating point". Could have been specified more obvious by the manual..

I'll add that fix to this PR, although it's unrelated..

**Comment by megies** [comment]
@kbouk, should work now..

**Comment by megies** [comment]
Should be good to merge, any double checks welcome of course.

**Pull request merged**
