### PR TITLE
Refactor basemap plots to be able to plot into an Axes instance

### PR DESCRIPTION
**Pull request by megies**
Mainly to be able to add a location plot to Event plots currently being set up in #1192.
This makes e.g. the following possible now:
```python
from obspy import read_events
import matplotlib.pyplot as plt

cat = read_events()

fig = plt.figure(figsize=(14, 7))

ax = fig.add_subplot(121)
cat.plot(projection="ortho", fig=ax, colorbar=True, show=False)

ax = fig.add_subplot(222)
cat.plot(projection="global", fig=ax, title="", colorbar=False, show=False)

ax = fig.add_subplot(224)
cat.plot(projection="local", fig=ax, title="", colorbar=False, show=True)
```
bmap

### CODE REVIEW

**Comment by megies** [comment]
This makes the *internal* part diverge a bit between matplotlib/cartopy.. but it should not be a big issue, @QuLogic? And I'm raising a `NotImplementedError` if an `Axes` is passed on to `Catalog.plot(method="cartopy", ...)`.

**Comment by megies** [comment]
Reusing `fig` kwarg to allow passing in an `Axes` might be a bit dirty.. but I feel it might be still better than introducing yet another plotting related kwarg (see the various issues open right now concerned with the topic..).

**Comment by MMesch** [comment]
another possibility that could work is that it plots in the currently active ax like basemap does. Maybe this avoids some of the issues with the kwargs?

**Comment by QuLogic** [comment]
No, it is better for libraries to be explicit rather then depending on Matplotlib's interactive API.

**Comment by megies** [comment]
Rebased + force-pushed.

**Pull request merged**
