### PR TITLE
add FDSNWS at http://auspass.edu.au:8080/ to URL mappings

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Add url mapping for FDSN WS at http://auspass.edu.au:8080/, see #2193

### Why was it initiated?  Any relevant Issues?

see #2193

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] +TESTS:clients.fdsn
- [ ] All tests still pass.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by Jollyfant** [comment]
Technically the FDSNWS specification mandates that the services are available on `:80`. It may be that some institutional firewalls block access to another port. We should at least recommend to change it.

**Comment by megies** [comment]
> Technically the FDSNWS specification mandates that the services are available on `:80`. It may be that some institutional firewalls block access to another port. We should at least recommend to change it.

CC @seballgeyer

**Comment by seballgeyer** [comment]
Hi Tobias,

We had that discussion with IRIS's people last week.  We are investigating
the possibilities. It can be a good idea to stop this pull until we have a
solution on our end.

-- Sebastien

**Comment by megies** [comment]
OK, let's close this PR then, let us know when there are any definitive news, we can add it on top of maintenance branch then..

**Pull request closed without merging**
