### PR TITLE
Add unittests for all possible SAC header fields?

### PR DESCRIPTION
**Pull request by jkmacc-LANL**
Follow-up to #1345. See https://github.com/obspy/obspy/issues/1345#issuecomment-199855827. No hurry, but as a reminder.

### CODE REVIEW

**Comment by jkmacc-LANL** [comment]
This issue is now a PR, implementing tests for `SACTrace` headers.  **This is a WIP**. Class properties are swapped for descriptors, and tests for `SACTrace` headers are added.

## TODO:

* [ ] Fix bytestring/Unicode issues for string headers.
* [ ] Finish implementing `stringheader` descriptor.
* [ ] Finish header descriptors for calculated header values.

**Comment by jkmacc-LANL** [comment]
@krischer or @megies Should this be against master, or maintenance?  It's a reimplementation of headers as descriptors, and header tests.

**Comment by krischer** [comment]
`master` - There is currently no active maintenance branch - there will be one once we finally release 1.1.

**Comment by jkmacc-LANL** [comment]
Thanks!  So, I'm doing a `git rebase master`.  When conflicts in files I didn't change in `sactrace_descriptors` pop up, I should choose the versions _not_ in my `HEAD` right?  Because the versions in `HEAD` came from `maintenance_##`, and I'm trying to make it look like `sactrace_descriptors` branched from `master`?

**Comment by krischer** [comment]
Yes - you want to only add changes you made. Best just make a copy of the current branch with `git branch BACKUP` before doing the rebase. Then you can always go back :)

**Comment by jkmacc-LANL** [comment]
Thanks.  It mostly worked.  I don't know how this (below) happened; is it OK if I just manual revert the change with a new commit?:

```
sac:$ git diff master ../../clients/seishub/tests/test_client.py
diff --git a/obspy/clients/seishub/tests/test_client.py b/obspy/clients/seishub/tests/test_client.py
index 8894f8396..adc9cf3fc 100644
--- a/obspy/clients/seishub/tests/test_client.py
+++ b/obspy/clients/seishub/tests/test_client.py
@@ -52,9 +52,7 @@ class ClientTestCase(unittest.TestCase):
         Test fetching waveforms from the server
         """
         t = UTCDateTime(2012, 1, 1, 12)
-        st = self.client.waveform.get_waveforms('GR', 'FUR', '', 'BH*',
-                                                t, t + 5)
-        st.sort(reverse=True)
+        st = self.client.waveform.get_waveforms('GR', 'FUR', '', 'BH*', t, t+5)
         self.assertEqual(len(st), 3)
         for tr, cha in zip(st, ('BHZ', 'BHN', 'BHE')):
             self.assertEqual(tr.stats.network, 'GR')
```

**Comment by krischer** [comment]
of course

**Comment by jkmacc-LANL** [comment]
This PR is no longer a WIP.  I'm satisfied with the changes and looking for a review.  @claudiodsf Interested in peeking at this?

* Most, but not all, `SACTrace` headers were converted from properties to descriptors.  Properties were easier to wrap my mind around for some headers.
* Tests were added for all classes of headers (`FloatHeader`, `IntHeader`, `StringHeader`, etc.).

Many thanks.

**Comment by jkmacc-LANL** [comment]
Thanks.  There certainly isn't _less_ code, but at least there is less repetition and more reuse..

**Comment by krischer** [comment]
Feel free to merge this at your leisure!

**Comment by jkmacc-LANL** [comment]
OK.  I was hoping @claudiodsf would weigh in, but it has been a week.  I'll go ahead.  Thanks!

**Pull request merged**
