### PR TITLE
fdsn: try to fix regression introduced by #3306, see #3320

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Aims to fix some internal handling of what info we get back from server in case of errors in FDSN requests.
No changelog needed since this regression is not yet in a released version.

### Why was it initiated?  Any relevant Issues?

 - Fixes a regression introduced by #3306 and..
 - should solve an issue reported in https://github.com/obspy/obspy/issues/3320#issuecomment-1706809150 and..
 - in principal should also fix the original potential bug reported in #3320 (even though I can not reproduce the original report and thus can not be sure)

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] New modules, add the module to `CODEOWNERS` with your github handle
- [x] Add the yellow `ready for review` label when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by crotwell** [comment]
This is just a guess, but if the server incorrectly sets the Content-Type HTTP header to a binary type, like `application/vnd.fdsn.mseed` before the error occurs, then python may think that the response is not actually text, and hence returns bytes.

It would be really useful to get the actual URL that obspy is generating to test against the server using curl to see exactly what is being returned.

Otherwise, it seems like being defensive about parsing the returned error message is wise.

**Comment by filefolder** [comment]
can confirm this fixes both the 401 bad auth error and the 204 no data error.

if one wanted to try a wget test, the actual link can often be manually created via the direct fdsnws implementation (e.g. server.com/fdsnws) at most FDSN centers. for GFZ it is here: https://geofon.gfz-potsdam.de/fdsnws/station/1/builder

here's an example for a non-existing network: https://geofon.gfz-potsdam.de/fdsnws/station/1/query?network=HH&format=text&nodata=404

**Review by filefolder — APPROVED** [review]
confirmed works. for the second part i might have done this

```
if not isinstance(server_info,str):
    server_info = server_info.decode('ASCII', errors='ignore')
```

**Review by jsaul — APPROVED** [review]
Fixes the issue for me.

**Comment by megies** [comment]
> for the second part i might have done this
> 
> ```
> if not isinstance(server_info,str):
>     server_info = server_info.decode('ASCII', errors='ignore')
> ```

I agree that might be cleaner.. I think all the fragile ugliness in the Py2+3 transition phase when it came to `isinstance(..., (str, new_str, ...))` has made me avoid that construct for checking for `str` once and for all :sweat_smile:

**Comment by megies** [comment]
So after looking at #3320 again on this branch, it looked like the original "string decode" problem was fixed here but we still ran into another problem running the example code from #3320 original post:

```python
File ~/git/obspy/obspy/clients/fdsn/client.py:1482, in Client._download(self, url, return_string, data, use_gzip, content_type)
   1480 if content_type:
   1481     headers['Content-Type'] = content_type
-> 1482 code, data = download_url(
   1483     url, opener=self._url_opener, headers=headers,
   1484     debug=self.debug, return_string=return_string, data=data,
   1485     timeout=self.timeout, use_gzip=use_gzip)
   1486 raise_on_error(code, data)
   1487 return data

File ~/git/obspy/obspy/clients/fdsn/client.py:1902, in download_url(url, opener, timeout, headers, debug, return_string, data, use_gzip)
   1900 # Catch HTTP errors.
   1901 except urllib_request.HTTPError as e:
-> 1902     error_data = e.read()
   1903     if debug is True:
   1904         msg = "HTTP error %i, reason %s, while downloading '%s': %s" % \
   1905               (e.code, str(e.reason), url, error_data)

File ~/miniconda3/envs/master/lib/python3.10/tempfile.py:477, in _TemporaryFileWrapper.__getattr__(self, name)
    473 def __getattr__(self, name):
    474     # Attribute lookups are delegated to the underlying file
    475     # and cached for non-numeric results
    476     # (i.e. methods are cached, closed and friends are not)
--> 477     file = self.__dict__['file']
    478     a = getattr(file, name)
    479     if hasattr(a, '__call__'):

KeyError: 'file'
```

some kind of weird behavior of the `HTTPError` acting like a file-like object (built on tempfile?!) but then failing to read anything because probably no extra information in this case. Hope the above commit fixes it.

**Comment by megies** [comment]
Tried even harder to get more details into error message after the above example from our forum didn't show proper details. Here's an example that is improved with last commit:

```python
from obspy.clients.fdsn import Client
from obspy import UTCDateTime

client = Client("EMSC")

starttime = UTCDateTime("2023-09-08T00:00:00")
endtime = starttime + 86400

coords = (-10000.3, 29.7, -6.6, 32.2)
cat = client.get_events(starttime=starttime, endtime=endtime, minlatitude=-100000.123)
```

**Comment by megies** [comment]
Should be good to go

**Pull request merged**
