### PR TITLE
Fix bibliography building with pybtex 0.22+

### PR DESCRIPTION
**Pull request by QuLogic**
### What does this PR do?

Exactly as the title says.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes (I assume we aren't making any more 1.1.x releases.)
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+DOCS"
- [N/A] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [N/A] Any new features or fixed regressions are be covered via new tests.
- [N/A] Any new or changed features have are fully documented.
- [N/A] Significant changes have been added to `CHANGELOG.txt` .
- [N/A] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
@QuLogic In case you're relying on the docs buildbot.. it has a static environment and it has pybtex 0.19

**Comment by QuLogic** [comment]
Yes, that's just to check I didn't break the existing version.

**Comment by QuLogic** [comment]
So it seems we have other dependency issues...

**Comment by QuLogic** [comment]
This was merged in #2662.

**Pull request closed without merging**
