### PR TITLE
support reading WIN32 format

### PR DESCRIPTION
**Pull request by seisman**
This PR adds basic support for reading WIN32 format. It's a little similar to obspy.io.datamark. It works under Python 3.5 but fails under Python 2.7, since I know nothing about Python 2/3 compatibility. :cry: 

It still need further revisions to make it compatible and I open this PR to see if you have any suggestions.

### CODE REVIEW

**Comment by seisman** [comment]
As far as I can see, there are at least four differences between datamark and win32:

1. win32 has a 4 bytes file header, which is always equals to '0x00000000'; datamark seems to has no file header;
2. win32 use 8 bytes to store starttime, and datarmark use 6 bytes;
3. for each one-second block, both win32 and datamark have a block header, but the sizes of block header are different;
4. the header for each channel seems a little different, too. win32 block header contains more information;

Maybe the datamark can be extended to support win32 format by adding several if-elif-else statements.

**Comment by megies** [comment]
Please compare #1072..

**Comment by ThomasLecocq** [comment]
@krischer so datamark is actually the name of the datalogger and should have been called "win" since the beginning. Now win32 is a slightly evolved version. @megies and others, I could try to have a look at it in the coming months...

**Comment by megies** [comment]
This PR looks pretty good already, great work @seisman!

A couple of things..
 - please check out the [adding a new submodule page](), e.g. docs skeleton and plugin integration in setup.py is missing
 - assuming that win32 is a special format of "win" maybe we should rename the new submodule to "win" and rename "core.py" to "win32.py".. just a thought, I don't know details of these formats, CC @ThomasLecocq (maybe the full pdf document from which you cropped the win32 section might give some answers as to the different flavors of win?)
 - all py files need our common "future import" header, see https://travis-ci.org/obspy/obspy/jobs/207036477#L1133 and just copy paste the top import lines from any other py file in the repo

**Comment by krischer** [comment]
Should we also rename `io.datamark` to `io.win` and maybe somehow merge the win and win32 data format if they share a lot of characteristics. Would be easier to maintain in the long run.

**Comment by krischer** [comment]
Sorry -- accidentially closed it by pressing the wrong button.

**Comment by megies** [comment]
> Should we also rename io.datamark to io.win and maybe somehow merge the win and win32 data format if they share a lot of characteristics. Would be easier to maintain in the long run.

see #1072

**Comment by barsch** [comment]
is the datamark logger the only device producing win/win32 format? if so I would almost prefer to leave it as datamark as win/win32 clashes a bit with a name of a certain os and it may be confusing ...

**Comment by megies** [comment]
@seisman pasted a wrong link, but I guess you found it.. ;-)
https://github.com/obspy/obspy/wiki/How-to%3A-add-a-new-submodule

> is the datamark logger the only device producing win/win32 format? if so I would almost prefer to leave it as datamark as win/win32 clashes a bit with a name of a certain os and it may be confusing ...

good point..

**Comment by ThomasLecocq** [comment]
> is the datamark logger the only device producing win/win32 format? if so I would almost prefer to leave it as datamark as win/win32 clashes a bit with a name of a certain os and it may be confusing ...

AFAIK yes, the file format name is win and win32. And yes, it's a terrible name... 

see the docs attached to the format:
https://github.com/obspy/obspy/blob/master/obspy/io/datamark/docs/Re__DataMark_format_description.eml

**Comment by megies** [comment]
Hmm.. since this format was supposedly developed by ERI, from what I understand, maybe use `ERI_WIN` or `ERI_WIN32` as names to avoid having to use `WIN` etc.?

**Comment by seisman** [comment]
According to [FAQ09 on the Hi-net website](http://www.hinet.bosai.go.jp/faq/?LANG=en#Q09), win32 format is extended by NIED, not by ERI.

> NIED extended the Japanese popular seismic waveform data format "WIN" developed by the University of Tokyo. We named this extended format as "WIN32".

And according to [FAQ07](http://www.hinet.bosai.go.jp/faq/?LANG=en#Q07), it seems that I can't redistribute the win32 format datas downloaded from Hi-net website. Maybe I should remove the sample win32 files under `io/win32/tests/data`.
> You are prohibited from redistributing the data and/or graphical images provided by the NIED Hi-net website in any form. When announcing your original results obtained by using the downloaded data, this rule does not applied. In that case, however, you are obliged to indicate that the use of the NIED Hi-net (or F-net) data. For the data provided by other organizations such as the Japan Meteorological Agency or universities, you are required to use them only in accordance with each organization's rule.

**Comment by megies** [comment]
> Maybe I should remove the sample win32 files under io/win32/tests/data

If you have other (free) test data better remove it (completely, also from history.. squash out, rebase+force-push), if not just ask for permission, I can't see how anybody would not allow inclusion as test data (assuming it's very short waveform snippets).

**Comment by megies** [comment]
> NIED extended the Japanese popular seismic waveform data format "WIN" developed by the University of Tokyo. We named this extended format as "WIN32".

hmm.. so no idea how to best name it.. -_-

**Comment by barsch** [comment]
so essentially two different formats: so if there are no efforts for merging both formats we just should roll with io.win and io.win32 - those modules shouldn't called directly anyway

**Comment by barsch** [comment]
btw: we have another PR with a existing win32 sample file: https://github.com/obspy/obspy/pull/1494 in case we can't use the existing one

**Comment by seisman** [comment]
I contacted Hi-net to ask for a permission one week ago. There is no reply yet...

**Comment by ThomasLecocq** [comment]
just use those files: https://github.com/obspy/obspy/pull/1494/files

**Comment by claudiodsf** [comment]
My two cents: I personally work with HiNet data and I know many people who use it. They all know that the file format is "win32" (even if that name may sound a terrible choice), but nobody knows about "datamark". So, I think we should stick with `io.win32`.

**Comment by ThomasLecocq** [comment]
>My two cents: I personally work with HiNet data and I know many people who use it. They all know that the file format is "win32" (even if that name may sound a terrible choice), but nobody knows about "datamark". So, I think we should stick with io.win32.

@claudiodsf : I renamed datamark to `win` in #1717 and this one here should be called `io.win32` indeed.

**Comment by seisman** [comment]
Two bad news:

1. My request is rejected.

>Thank you for accessing our website. 
> This is the NIED Hi-net/F-net/V-net administrator.
>
> We prohibit any redistribution of data from our webpage. No data is
currently allowed to be included in your module. We will consider releasing
a freely redistributable sample data as a request for a future update.
>
> Sincerely yours,
> NIED Hi-net/F-net/V-net administrator

2. The win32 files in #1494 have a network code of `0101`, which means these files are produced by Hi-net, too.

**Comment by barsch** [comment]
after this answer from "NIED Hi-net/F-net/V-net administrator" I almost tend to not support this format at all - tztzt

anyway, @seisman can you produce some own test data you can use - where you know exactly it is working as expected - once NIED decides to release freely redistributable samples we can add them too

**Comment by ThomasLecocq** [comment]
I've also asked someone I know at ERI if we can have de-classified data officially !

**Comment by megies** [comment]
> Two bad news:
> 
>     My request is rejected.
> 
>>     Thank you for accessing our website.
>>     This is the NIED Hi-net/F-net/V-net administrator.
> 
>>    We prohibit any redistribution of data from our webpage. No data is

This must be a misunderstanding.. did you make clear that this is just about an example test file with ~1000 samples, i.e. a couple of seconds of data?

**Comment by seisman** [comment]
I think I have made it clear that I only need a one-minute sample data of three channels. 

> Dear NIED/Hi-net administrators,
> 
> I'm a PhD student majoring in geophysics. Recently I'm trying to write a Python module which allows reading win32 format data in Python.This module will be included into ObsPy as a submodule in the future.
> 
> ObsPy (http://docs.obspy.org ) is an open-source project (licensed under the LGPL v3.0) dedicated to provide a Python framework for processing seismological data. It supports reading and writing several common file formats used in seismology, e.g., SAC, mseed and segy. However, it does not support win32 yet. I think it will benefit many users if obspy can support reading win32 format.
> 
> When writing this module, I need to include a sample win32 data into this module to test the codes. And this sample win32 data will be distributed by ObsPy licensed under the LGPL v3.0. However, according to the NIED/Hi-net policy, I have no right to redistribute any waveform data obtained from Hi-net website. 
> 
> So I'm writing this e-mail to ask if you can give a permission to allow me include a small piece of win32 data into ObsPy. This sample data will be one-minute long and include only three channels. Thank you.
> 
> Looking forward to your reply.
> 
> Best Regards,

**Comment by megies** [comment]
Yep, perfectly clear in your email.. hard to understand why it should be a problem to give permission ofr inclusion of a small file sample.. they should be happy if software can read their data format and somebody else is doing the work actually..

**Comment by ThomasLecocq** [comment]
I've also received the email address of two persons who would be able to answer "really" and not copy/pasting the faq... in progress.

**Comment by megies** [comment]
We decided to push for 1.1.0 and since I'm assuming this will not be ready by Sunday I'm punting this to 1.2.0. Feel free to push on this if you feel it can be ready by Sunday.

**Comment by megies** [comment]
I'm gonna punt this to 1.3.0 since it doesn't look like there has been progress..

**Comment by megies** [comment]
Well, I don't know though, without a test file even.. is there no other converters somebody could use to make one, or ask again for a sample? It is kinda ridiculous to support a format for which we don't even have a single file

**Comment by megies** [comment]
@ThomasLecocq I suppose we want this merged into the "new" `io.win` that was moved over from `io.datamark` or something?

**Comment by ThomasLecocq** [comment]
> @ThomasLecocq I suppose we want this merged into the "new" `io.win` that was moved over from `io.datamark` or something?

Yes, so Win & Win32 are two different formats, but both made from the same dataloggers (datamark datalogger)/institute

**Comment by megies** [comment]
Done, and over to you @ThomasLecocq

**Pull request closed without merging**
