### PR TITLE
move all files used in the codebase from "submodule"/docs to "submodule"/data

### PR DESCRIPTION
**Pull request by megies**
so that we can just leave out "submodule"/docs in released zipball
generally. also much cleaner.

### CODE REVIEW

**Comment by krischer** [comment]
Can I just manually do this, as I am currently doing the restructuring?
Would be a bit painful to merge this in. Otherwise the idea is good.

**Comment by megies** [comment]
See gitter, our 0.10.0 pypi zip is broken after all, missing files, so we have to do a 0.10.1 with old codebase structure. Want me to merge this into `releases` instead, so that you can do it manually on `master`?

**Comment by krischer** [comment]
Ah ok. Oh well 0.10.1 is also a nice number ;-) Yes, if possible just merge this into `releases`.

**Comment by megies** [comment]
Will have to merge it back from releases into master anyway.. but yeah.. ;)

**Comment by megies** [comment]
Merging this manually into `releases` now.

**Pull request closed without merging**
