### PR TITLE
Separate freq resp. calc from plotting

### PR DESCRIPTION
**Pull request by Jollyfant**
Hey, I needed ObsPy to return frequency response without plotting it. So I considered separating the calculation from the plotting in a new function. However, I'm not sure of the best approach to forward so many variables in the function. I'm using **locals() but myeh..

@megies ideas?

### CODE REVIEW

**Comment by megies** [comment]
Uhm.. we already have `Response.get_evalresp_response_for_frequencies()`..? https://github.com/obspy/obspy/blob/master/obspy/core/inventory/response.py#L1365

**Comment by Jollyfant** [comment]
Hmmmmmmmmmmm

**Comment by Jollyfant** [comment]
@megies this is not in version 1.0.3 right? :think:

**Comment by megies** [comment]
Nope, sorry: https://github.com/obspy/obspy/blob/master/CHANGELOG.txt#L45

When me and @krischer are back from vacation we really need to release 1.1.0..  :tired_face:

**Pull request closed without merging**
