### PR TITLE
getPAZ behavior with multiple blockette 53s

### PR DESCRIPTION
**Pull request by megies**
Hello

I believe there might be an issue with the getPAZ routine, when a response has multiple blockette 53 stages.  An example of this would be: http://service.iris.edu/irisws/resp/1/query?net=II&sta=PFO&loc=00&cha=LHZ&starttime=2015-10-08T16:00:00&endtime=2599-12-31T23:59:59

When I run the following script 
```python
#!/usr/bin/env python

from obspy.xseed import Parser
from obspy.core import UTCDateTime

parser = Parser('/APPS/metadata/SEED/II.dataless')
paz = parser.getPAZ('II.PFO.00.LHZ', UTCDateTime('2016-001T00:00:00.0'))

print(paz)
```

I get the following output:
```
[aringler@igskgacgvmres01 ~]$ python checkII.py 
/usr/lib64/python2.6/site-packages/obspy/xseed/parser.py:1071: UserWarning: More than one Abbreviation Dictionary Control Headers found!
  warnings.warn(msg, UserWarning)
{u'sensitivity': 5641740000.0, u'digitizer_gain': 1.0,
 u'seismometer_gain': 3602.4000000000001, u'zeros': [],
 u'gain': 1.0, u'poles': []}
[aringler@igskgacgvmres01 ~]$ 
```

However, I believe the output should be:
```
{u'sensitivity': 5641740000.0, u'digitizer_gain': 1.0,
 u'seismometer_gain': 3602.4000000000001, u'zeros': [0j, 0j, (-493.48022005446791+0j), (-0.95821225640944263+0j), (-0.95821225640944263+0j)],
 u'gain': 6.2831853071795862, u'poles': [(-0.076039380147752855+0.0718179529533189j), (-0.076039380147752855-0.0718179529533189j), (-0.90191998074738944+0.36210907414497578j), (-0.90191998074738944-0.36210907414497578j), (-248.21699762981297+483.10923974980324j), (-248.21699762981297-483.10923974980324j)]}
[aringler@igskgacgvmres01 ~]$ 
```

I think the declaration of the poles and zeros (lines 581 and 573 of parser.py) needs to be moved up so that they aren't reset as empty lists every time an additional blockette 53 or 60 is found.

If this is in fact an issue, then I would be happy to correct it and make a pull request.  If I am totally missing something than I apologize for confusing people!

Best,
Adam

### CODE REVIEW

**Comment by megies** [comment]
Adam,

thanks for starting a fix. I made this ticket a PR from this branch you started.

I really don't have a strong opinion on these changes (they probably wont touch me), I think as long as the old tests still run (hope they cover most "normal" use cases) and you're happy with the additional tests, that's fine with me.

T

**Comment by megies** [comment]
@aringler-usgs, since no existing tests were changed and CI is all green, I guess this is good to merge?

**Comment by aringler-usgs** [comment]
Yes, I think it all looks okay on my end (a bit surprising given that usually dealing with dataless is a total pain).  

Thanks for your help,
Adam

**Comment by megies** [comment]
Alright, good to hear. I don't see a reason why not to merge this then.. :+1:

**Comment by QuLogic** [comment]
Possibly needs a ChangeLog entry?

**Comment by megies** [comment]
> Possibly needs a ChangeLog entry?

Possibly, yes. On the other hand, I think we have quite some minor bugs fixes for 1.0.1 without changelog entries. I was thinking we can just add this link to the changelog: https://github.com/obspy/obspy/issues?q=milestone%3A1.0.x+is%3Aclosed+label%3Abug (although a static changelog is nicer of course)

**Pull request merged**
