### PR TITLE
try building docset in github actions

### LINKED ISSUE #3307: docs: re-enable building docsets (for dash/zeal)
Would be good to have docsets built again (for macOS "dash" / linux "zeal"), looks like that got scrapped during the transition to github actions.

https://docsets.obspy.org/

Alternatively could see if we can get obspy into the dash build chain, maybe.

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Tries to build docsets for dash/Zeal again, in github actions now

### Why was it initiated?  Any relevant Issues?

closes #3307 

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] New modules, add the module to `CODEOWNERS` with your github handle
- [x] Add the yellow `ready for review` label when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
Looks like docs building in github actions does not kick off if adding the "build_docs" label right when opening the PR. But that's a minor issue

**Comment by megies** [comment]
This is ready pretty much, only thing missing is grabbing the artifacts on our server. I had a very quick look at it @trichter but couldn't immediately figure out how to add grabbing the docset artifacts as well

**Comment by megies** [comment]
The deploy isn't working anymore because it only expects one artifact. Should be easy to fix, we could just filter by artifact name:

```python
r = requests.get(run['artifacts_url'], params={'name': 'obspydoc'}, **RKW)
```

Like in browser: https://api.github.com/repos/obspy/obspy/actions/runs/9064790999/artifacts?name=obspydoc

@trichter the deploybot code isn't under version control looks like? Mind if I make it a git repo out of it and push it to github? Looks like the only thing we want to avoid pushing is that file with the github token in it?

**Comment by trichter** [comment]
> The deploy isn't working anymore because it only expects one artifact. Should be easy to fix, we could just [filter by artifact name](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28)

Perfect, you already solved it.

The deploy code is in folder misc/scripts/docs_deploybot

**Review by trichter — APPROVED** [review]
I finished with the deploy code on the server.

Doc for this pr is [here](https://docs.obspy.org/pr/docsets/).
Docset is [here](https://docs.obspy.org/pr/docsets/obspy-master.docset.tgz) and [here](https://docs.obspy.org/pr/docsets/Obspy.docset).

Let's merge this PR and see if it works with the push to master. If everything works I can add the modified server code in a separate PR.

**Comment by megies** [comment]
> The deploy code is in folder misc/scripts/docs_deploybot

Ah, OK, I didn't see it there :+1: 

> Let's merge this PR and see if it works with the push to master. If everything works I can add the modified server code in a separate PR.

Sounds good :+1: We mostly want the `master` build docsets to keep updating, I guess, and the stable version builds to get stored, but I guess that's probably built in already similar to how it is done with the docs

**Comment by trichter** [comment]
> Sounds good 👍 We mostly want the master build docsets to keep updating, I guess, and the stable version builds to get stored, but I guess that's probably built in already similar to how it is done with the docs

Yes, I changed this server-side.

@megies Can you please have a look at the new master docset: https://docsets.obspy.org/

The name of the master tgz file is a bit different than before. Does it matter? Do I have to adapt it? Also, there is a xml file. I guess this has a special purpose. Do wee need to update it automatically or can we delete it?

**Comment by megies** [comment]
> @megies Can you please have a look at the new master docset: https://docsets.obspy.org/

docset looks ok in zeal, even though now it has the navigation column on every page which isn't ideal but I don't see an easy option to toggle that in `doc2dash` and I don't feel like looking into how to change that..



> The name of the master tgz file is a bit different than before. Does it matter? Do I have to adapt it?

I guess it can stay, or actually we can make the old name a symlink to the new one maybe. The xml file is basically what you add in Zeal as a "feed" and then it checks the version number in there regularly and gives an option to update the local docset copy.

Then we could have another xml file "stable" that links to the current stable docset tgz. We'd just need some routine to rewrite the xml files with new version number every time they get deployed. The version number we'd have to scrape from the `index.html` probably, I fear..

**Comment by trichter** [comment]
OK, so you need the full version number for master:

```
<entry>
    <version>1.2.1.post0+1.g219b24d2ee.obspy.master</version>
    <url>http://docsets.obspy.org/obspy-master.tgz</url>
</entry>
```

It is not enough to do 


```
<entry>
    <version>dev</version>
    <url>http://docsets.obspy.org/obspy-master.tgz</url>
</entry>
```

**Comment by megies** [comment]
I think so, yes. I believe zeal/dash is looking at the xml you provide as "feed URL" to decide if a local docset needs updating. Users can always manually go to the folder where those docsets are locally stored and delete and replace them manually, but otherwise (at least in the Linux "zeal" version) the re is no option to manually supply a docset, it's either through a feed URL or selecting from the official dash repository menu.

**Comment by megies** [comment]
If it is too much hassle though, I think just having them docsets up there on our server is fine

**Comment by megies** [comment]
I could also try to be better at injecting the version number into the "Info.plist" which seems the main file for stuff like this and could be parsed with an xml parser

**Comment by trichter** [comment]
I think it is OK, I can write some ugly code to create these two XML files, obspy-master.xml and obspy-stable.xml

**Comment by megies** [comment]
@trichter I think the docs deploy broke: https://docs.obspy.org/pr/fix_tsindex_feb2024/

Looks like only the docsets got uploaded (which we don't even really need for PRs)

**Comment by trichter** [comment]
Ups, sorry, will fix it.

**Comment by trichter** [comment]
Done. The docset for this PR is available at https://docs.obspy.org/pr/fix_tsindex_feb2024/docsets
We can later change the workflow to not upload the docset artifact for PRs.
Will still need this function to test the xml file.

**Comment by trichter** [comment]
@megies, one more question. Do we need the uncompressed docset (`.docset` folders), or just the `.tgz`, or both?
I ask, because I saw that the xml refers to the `.tgz` archive.

**Comment by megies** [comment]
I think just the tgz is fine. I don't know dash (the original Mac app) and how you can add docsets there (I think mainly through the official dash repository), but in zeal (the Linux clone) you can either enter a "feed URL" (link to that xml with the remote version and tgz location specified) or you can manually put the uncompressed docset in the location where the app locally stores its application data. So probably no use to have it uncompressed on the server, I believe. Not sure why we did it that way.

**Comment by trichter** [comment]
I removed the uncompressed docsets.

**Pull request merged**
