### PR TITLE
Calculate more accurate ray paths in taup

### PR DESCRIPTION
**Pull request by johnrudge**
### What does this PR do?

The ray paths calculated by obspy.taup are often rather inaccurate, in that they miss the receiver by a small, but significant, margin. A simple example of this is:

```
from obspy.taup import TauPyModel
import numpy as np

model = TauPyModel("prem")
arrivals = model.get_ray_paths(source_depth_in_km = 0.0, distance_in_degree = 120.0, phase_list = ['PKIKP'])
arrival = arrivals[0]
diff = (arrival.purist_distance*np.pi/180.0 - arrival.path["dist"][-1])
print(diff*180/np.pi, "degrees")

diff_time = (arrival.time - arrival.path["time"][-1])
print(diff_time, "seconds")
```
which outputs
```
-0.026268729081271754 degrees
-0.05079122889264909 seconds
```
i.e. the path misses the receiver by 0.03 degrees, and has a discrepancy in arrival time of 0.05 seconds. While not terrible, users might expect better accuracy than this, depending their application.

The key bit of logic that controls how accurately the ray paths hit the receiver is the `refine_arrival` method of `SeismicPhase` in `obspy/taup/seismic_phase.py`. This uses a shooting method to determine the ray parameter that brings the arrival closest to the station. A hand-coded false postion (regula falsi) root finding scheme is used to find the ray parameter. This hand-coded scheme terminates either after a set number of iterations (default 5), or when the arrival is within REFINE_DIST_RADIAN_TOL (default is 0.0049 degrees). In the example above the algorithm has terminated because it has done 5 iterations, not because it has reached the desired distance tolerance.

To improve the accuracy, this pull request replaces the hand-coded regula falsi scheme with one of scipy's built-in root-finding routines (`brentq`). This routine gives much faster convergence to the root. The pull request also changes the default tolerance and iteration limit to give much more accurate ray paths by default.

This pull request does have a notable effect on runtime. It roughly doubles the amount of time needed to calculate a ray path, as more calls to `shoot_ray` are made. However, I think this extra runtime is worth the extra accuracy. The current implementation is certainly not doing enough iterations to hit the receiver with the desired accuracy.

A consequence of this pull request is divergence with the Java taup toolkit, which uses an identical regula falsi scheme with the same defaults. This affects the tests in test_tau.py which often compare directly with the output from the java version. With the pull request, subtle differences in `ray_param_sec_degree`, `takeoff_angle`, `incident_angle` in the arrival occur, as well as subtle differences in the ray paths. But these are expected because of the more accurate computation of the ray parameter. To ensure the tests pass this pull request increases the desired test tolerance on comparisons which will change because of the new implementation. It also currently skips the `test_paths_for_crustal_phases` path comparison test.

### Why was it initiated?  Any relevant Issues?

See #1189 for the original discussion of the shoot_ray implementation. 
For the `test_paths_for_crustal_phases` see #1392
#2816 is a current issue that shows an example plot where an arrival does not hit the receiver with sufficent accuracy.

### PR Checklist
- [X] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [X] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [X] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [X] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by johnrudge** [comment]
Ok, I've fixed the minor doctest issues. All over to you @megies to srutinise!

**Review by megies — CHANGES_REQUESTED** [review]
In principle it's a good idea to stay as close to the Java original version as possible, but this change is not a lot of code changes and it's confined to one method. And we definitely want to prioritize for a bit more accuracy even if it's a bit slower, we've seen how people got confused/annoyed with too large discrepancies in those other issues you linked.

So I'm all for it. :+1: 

Two things tho:

1) This adds about a minute on total (non-network) test runtime, doubling the taup submodule test runtime (which already is on the brink):
 - [recent master test](https://tests.obspy.org/123542/)
 - [this PR](https://tests.obspy.org/124013/)

Can we please have the tests run with less accuracy to speed it up? You should be able to set those two constants to lower values at the top of test_tau...*.py or maybe make it some pytest fixture or something (not super familiar with how pytest does things like that best, @trichter?).
Tests should just make sure that the results are reproducible and stable, they don't have to be on point in terms of accuracy of those paths. =)
You can leave 1 or a couple tests with full accuracy though, to have that case covered too.

Screenshot from 2022-05-12 12-55-15

2) We should maybe consider some way to point out to users how to speed up these calculations while sacrificing accuracy. We probably don't want to go all out on this, but maybe we could point out to users in the docs in the respective places that these constants could be changed to tweak it? Dunno.. maybe not necessary

**Comment by megies** [comment]
> One could fiddle with `REFINE_DIST_RADIAN_TOL` in the tests to bring the peformance closer to current master, but I don't think it's worth it.

Well.. that's a hen/egg problem. Are people not caring about test speed because the whole test suite takes ages anyway or does the whole test suite take ages because people were not caring about test speed. :zany_face: 

I know it' rough to spend additional time on speeding some part of the tests up with the whole thing taking so long, but on the other hand, it just gets outta hand more and more if we slack on it. :grimacing: 

> so going around 25% slower

I think we could live with that increase if you don't wanna mess with tweaking tests more

> I think it could be potentially confusing having the tests run with a non-default value of `REFINE_DIST_RADIAN_TOL`

I don't think it would be confusing. A lot of tests just run on some random data, to not have to read in actual real data.
We would just want to make sure to not reduce those constants for doctests (that might produce pics even). But for unittests it really doesn't matter if the results are less accurate, as long as there is like 1-2 tests with the new regular better tolerance.

**Review by megies — APPROVED** [review]

**Comment by johnrudge** [comment]
I don't want to mess with the tests any further. I'm afraid I'll leave that to you!

**Pull request merged**
