### PR TITLE
BUG: Stream.plot(type='section'...) reftime parameter doesn't work

### PR DESCRIPTION
**Pull request by luca-s**
### What does this PR do?

Fix a plotting bug. When type='section' is used in Stream.plot the `reftime` doesn't behave correctly.

### Why was it initiated?  Any relevant Issues?

I couldn't plot my data correctly.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [x] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
Currently all PRs go into `master` since we won't do another 1.1.x bug fix release. I'll try to just change the base branch.

**Comment by luca-s** [comment]
@megies Thanks. Please let me know if you prefer me to do the rebase

**Comment by megies** [comment]
ideally this should have a regression test.. but i don't want it to slow down 1.2.0

**Comment by megies** [comment]
for posterity, here's illustrating the bug

```python
import matplotlib.pyplot as plt
import numpy as np
from obspy import read, UTCDateTime

tr = read()[0]
reftime = UTCDateTime("2009-08-24T00:20:00")
info = 'Trace starts at %s s after reftime' % (tr.stats.starttime - reftime)

fig, (ax1, ax2) = plt.subplots(nrows=2, sharex=True)
fig.suptitle('Trace starts at %s s after reftime' % (tr.stats.starttime - reftime))
times = (np.arange(len(tr)) + (tr.stats.starttime - reftime)) * tr.stats.delta
ax1.plot(times, tr.data)
ax1.set_title('Buggy start relative to reftime')
ax1.grid()
times = (np.arange(len(tr)) * tr.stats.delta + (tr.stats.starttime - reftime))
ax2.plot(times, tr.data)
ax2.set_title('Correct start relative to reftime')
ax2.grid()
plt.show()
```

Figure_1

**Comment by megies** [comment]
I felt free to rebase and force push @luca-s

**Comment by megies** [comment]
Remaining CI test file is unrelated, gonna rebase and merge

**Comment by megies** [comment]
Thanks @luca-s !

**Pull request merged**
