### PR TITLE
Numpy version response bug

### LINKED ISSUE #2434: Trace remove_response() method raises exception when used with numpy 1.17.0
numpy version 1.17 has replaced the internal fftpack module with pocketfft (see release notes here: https://github.com/numpy/numpy/blob/master/doc/release/1.17.0-notes.rst)

This causes an exception to be raised in the following line of code:

https://github.com/obspy/obspy/blob/e97fe91ae99df0154664933102f03405940b86d6/obspy/core/util/misc.py#L614

which has the effect of breaking the remove_response() method of the Trace object, as demonstrated in the test script I've attached (renamed to .txt to make github happy).

The error is:

`AttributeError: module 'numpy.fft' has no attribute 'fftpack'`

[testresp.txt](https://github.com/obspy/obspy/files/3463112/testresp.txt)

OS Version: OSX 10.13.6
Python:  3.6.7
numpy: 1.17.0
obspy: 1.1.1

I created a test environment with conda:
conda create -n testfft python=3.6 obspy

The workaround, I suppose is to not use numpy 1.17 or higher until this is patched in obspy.

### PR DESCRIPTION
**Pull request by aringler-usgs**
### What does this PR do?

This pull-request is a one-line check on the numpy version before the response removal.

### Why was it initiated?  Any relevant Issues?

fixes #2434

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [x] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [x] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by aringler-usgs** [comment]
Hopefully, I did the branching correctly.  I apologize if I didn't (and would like to know what I did wrong if that is the case).  Sometimes doing git correctly is the crux of all of this.

**Comment by QuLogic** [comment]
You made your commit on the `master` branch and are targetting `maintenance_1.1.x`, so no.

Either you need to make the commit starting from `maintenance_1.1.x` or you need to target `master`.

**Comment by aringler-usgs** [comment]
@QuLogic thanks so much for pointing this out.  @amkearns-usgs helped figure out my git problems.  Hopefully this is now on the correct branch.

**Comment by megies** [comment]
@QuLogic @aringler-usgs we don't do anymore releases on 1.1.x, aso everthing goes into master right now. Just force push back to your previous state https://github.com/obspy/obspy/commit/aacaa7f316fb6e6e1bad934fa236d3be6ac4bdc6 and change the base branch ("edit" button top right). I can do it if you need help

**Comment by megies** [comment]
Also @aringler-usgs version comparisons can't be done with plain strings, compare e.g. this:

```python
signal/spectral_estimation.py
40:from obspy.core.util import AttribDict, NUMPY_VERSION
1345:        if NUMPY_VERSION >= [1, 7]:
1436:        if NUMPY_VERSION >= [1, 7]:
```

**Pull request merged**
