### PR TITLE
Pass on control over arclink request forwarding...

### PR DESCRIPTION
**Pull request by yannikbehr**
...to getStations and getNetworks

### CODE REVIEW

**Comment by megies** [comment]
Looks good to merge.. just, here's one more: https://github.com/obspy/obspy/blob/arclink_request_forwarding/obspy/arclink/client.py#L438

Shouldn't that one be passed on from parent as well?

**Comment by yannikbehr** [comment]
Looks like it but the default for  'self.saveWaveform' differs from that for 'self.getInventory'. Not sure if there's a reason for it?

**Comment by megies** [comment]
Not sure.. could be intentional for Inventories.. but then again I don't see a real reason to have a discrepancy there. Maybe somebody else can shed light upon this?

**Comment by megies** [comment]
> 1095 problems were fixed (including 343 errors and 155 code smells).

Aha. Interesting. Nice work.. ;)

**Comment by yannikbehr** [comment]
@krischer Lion, do you know more about this?

**Comment by krischer** [comment]
@yannikbehr about the landscape stuff or arclink?

No clue who did the landscape stuff but we should maybe tell it to not parse the autogenerated code from our docs where most of the problems come from ;-)

I'm also not sure on the Arclink issue. Does not every arclink node have a copy of the master table and could thus provide the inventory information? Therefore there might be no need to actually route? Nonetheless I would also pass the argument to the `getInventory()` method - I don't think it can do any harm.

@barsch You are probably the ObsPy Arclink expert ;-) Any opinion?

**Comment by barsch** [comment]
I added landscape months ago for the "health" badge on https://github.com/obspy/obspy/wiki - however until now it never messed with the commit messages - seems like they changed that yesterday - hell the even spam my mailbox now with health messages :(

concerning arclink: seems like it should be ```route=route``` there too

**Comment by yannikbehr** [comment]
I would've merged this but I have no idea what the failed Travis CI build means. Is it save to merge?

**Comment by barsch** [comment]
IMHO it is fine to merge as the failed test is known to fail on some machines due to timeout and not related to the fix above.

**Comment by megies** [comment]
I'm gonna merge `releases` right away into `master` so that this doesn't get left out of 0.10..

**Comment by QuLogic** [comment]
That failing test is corrected on `master`.

**Pull request merged**
