### PR TITLE
Dockerfile updates

### PR DESCRIPTION
**Pull request by megies**
This PR..
 - remove erroneous geographiclib installs where it's not available, see #1623
 - removes some EOL releases
 - adds new fedora and openSUSE releases

Will try building all images from scratch tomorrow..

### CODE REVIEW

**Comment by QuLogic** [comment]
On a related note, I got [geographiclibadded to conda-forge](https://github.com/conda-forge/staged-recipes/pull/2586) (not available for 3.3 or 3.4 though.)

**Comment by megies** [comment]
> On a related note, I got geographiclibadded to conda-forge (not available for 3.3 or 3.4 though.)

I already saw a package build out there a few days ago.. but didn't investigate who's behind it. Great effort! :rocket:

**Comment by krischer** [comment]
With my small fix I can run test across all images.

**Comment by krischer** [comment]
Travis failure is unrelated. Merging.

**Pull request merged**
