### PR TITLE
Fix a typo in get_stations() and get_events() docs

### PR DESCRIPTION
**Pull request by claudiodsf**
A very small fix in `fdsn.client.Client.get_stations()` and `get_events()` docs.

### CODE REVIEW

**Comment by claudiodsf** [comment]
+DOCS

**Comment by ThomasLecocq** [comment]
the doc build look OK to me, dunno why the ❌ is there @megies ?

**Comment by megies** [comment]
> the doc build look OK to me, dunno why the x is there @megies ?

For purely idealistic and non-realistic reasons. The intention was that we get a clean docs build without warnings at some point, in order to be able to tell sanity of PR's docs-wise directly from CI results, without having to sift through built docs pages.. but yeah.. that never happened, we have tons of warnings in sphinx build, therefore the :x: in each and every docs buildbot message

**Comment by megies** [comment]
Thanks @claudiodsf

**Pull request merged**
