### PR TITLE
.fdsn: add EMSC web service shortcut

### PR DESCRIPTION
**Pull request by petrrr**
This (trivial) PR just adds a shortcut for the EMSC web service.

### CODE REVIEW

**Comment by krischer** [comment]
Do we really need different names for the same endnode? I know we already have that ORFEUS but I think we should remove that as well.

**Comment by megies** [comment]
Well the old name `"NERIES"` might not be super-ideal, but that all results from this strange `seismicportal` web page name..

**Comment by petrrr** [comment]
@krischer: Not sure I understand your comment. 

Are you referring to the `ORFEUS` vs. `ODC` alias? Well, in the context of EIDA we usually use `ODC` (Orfeus data center) when referring to the EIDA node, or even `KNMI` (the hosting organization), but I find the later inappropriate. Orfeus is the European organization. If I would have to pick one I'd rather use `ODC`, but I found `ORFEUS` already around.

`NERIES`: Sorry, I completely missed that this was around and probably wouldn't have associated it with the EMCS catalog immediately. So okay, if you want to avoid aliases, we can close this PR. On the other hand, NERIES refers to a pretty old project (even NERA, the subsequent project is now finished for quite some time).

@megies: I agree that this `seismicportal` webpage, which basically is the product of various projects is misleading.

In any case, I leave it to you to decide ...

**Comment by megies** [comment]
So, EMSC is what actually is behind seismicportal? I'm OK with adding the alias then, maybe we can deprecate the `NERIES` keyword at the same time..

**Comment by megies** [comment]
Ping. @petrrr, would you mind adding a deprecation warning when the old short URL for seismicportal.eu is used? Or what's your view on this? I think having multiple short URLs for one endpoint might get confusing..

**Comment by megies** [comment]
Ping, @petrrr..

**Comment by petrrr** [comment]
@megies: Sorry, for ignoring your ping. To many threads => low responsiveness ...
Sure, I guess deprecating `NERIES` is a valid option. What about `ORFEUS`? I find `ODC` more appropriate, and Orfeus might be reserved to refer to the organization itself, will offer other products in future. So deprecating `ORFEUS` would make sense as well. 

Will update the PR, so you can cherry pick it.

**Comment by krischer** [comment]
I feel like `"ORFEUS"` is too widely used and I would rather not deprecate it. I would actually prefer to remove the `"ODC"` mapping to be honest even though it is not strictly speaking correct.

**Comment by petrrr** [comment]
@krischer: I vote against removing `ODC`. This abbreviation/handle is used quite consistently within the Orfeus EIDA federation to refer to the data center hosted at KNMI, it is used in most documents and on the Orfeus EIDA webpages, in the current mastertable, monitoring, etc. I therefore would argue it should be kept. If you think that `ORFEUS` cannot or should not be deprecated (a was actually not proposing it, just asking), there is probably a good use case for having two aliases.

**Comment by krischer** [comment]
@petrrr Fair enough. That does seem like a legitimate use case for two aliases.

Can you add an entry to the changelog? Then we can merge this.

**Comment by petrrr** [comment]
What happens, is there a merge conflict on `CHANGELOG.txt`? Do I need to rebase or do we merge manually?

**Comment by QuLogic** [comment]
It'd be easier if you rebase.

**Comment by krischer** [comment]
Looks good. Thanks!

**Pull request merged**
