### PR TITLE
Write blockette 100 if accuracy might otherwise be lost

### PR DESCRIPTION
**Pull request by krischer**
This PR causes `obspy.io.mseed` to always write Blockette 100 if sampling rate accuracy might be lost otherwise.

Blockette 100 can store a single precision floating point sampling rate. With this PR ObsPy will always write Blockette 100 if the sampling rate cannot exactly be represented with the sampling rate factor and multiplier in the fixed header.

The test might be a bit strict but it is the correct thing to do and the only price to pay are potentially slightly bigger MiniSEED files. "Clean" sampling rates still will not have Blockette 100.

### CODE REVIEW

**Comment by megies** [comment]
Hmm, yeah. Can be seen as a fix, I guess..

**Comment by krischer** [comment]
@chad-iris Is this a sensible thing to do?

It might also be something `libmseed` might want to do automatically in a future version. ObsPy uses `mst_pack()` to write MiniSEED.

**Comment by megies** [comment]
Hmm.. a fail in SDS tests..? Just checked, using sampling rate `0.1` in there..

**Comment by krischer** [comment]
I added a better comparison. `0.1` works now.

**Comment by megies** [comment]
> Test looks good and comprehensive.

I guess github needs an option to review reviews.

**Comment by chad-iris** [comment]
Seems perfectly sensible to me for ObsPy.  Forced inclusion of a Blockette 100 at the libmseed level is a little heavy handed, need to think through the implications.

In related news I'm adding code in libmseed to handle integer sample rates higher than 32,767 Hz.  So those cases will be handled better using the factor/multiplier representation.  But there are other sample rate ranges that I don't see any good factor/multiplier estimation method for, e.g. huge, non-integer sample rates, so including Blockette 100s is the right thing to do.

**Comment by krischer** [comment]
> In related news I'm adding code in libmseed to handle integer sample rates higher than 32,767 Hz. So those cases will be handled better using the factor/multiplier representation. But there are other sample rate ranges that I don't see any good factor/multiplier estimation method for, e.g. huge, non-integer sample rates, so including Blockette 100s is the right thing to do.

Great :-) While at it: Could you change `ms_genfactmult()` to also return `-1` for very small sampling rates (e.g currently smaller than 1.0 / 32,767)? Right now it just checks if its larger than 0 and smaller than 32,767). Then ObsPy and other third party utils can just use the results of `ms_genfactmult()` to judge whether or not to include Blockette 100 and no longer need custom logic.

**Comment by krischer** [comment]
Merging - `ms_genfactmult()` will change with the new libmseed version which we can take advantage of for when deciding if to use blockette 100 or not. But that has to be done after 2.18 has been released.

**Comment by megies** [comment]
I think this PR might make a good argument to think about releasing 1.0.3

**Pull request merged**
