### PR TITLE
fix mpl epoch issue in array analysis

### PR DESCRIPTION
**Pull request by trichter**
### What does this PR do?

Fix https://github.com/obspy/obspy/issues/2690#issuecomment-686549268

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by heavelock** [comment]
The same could be achieved by adding `matplotlib.dates.EPOCH_OFFSET` instead of `datestr2num`. As unlikely as change of epoch, this would tie us better to their system, I think.

**Comment by trichter** [comment]
> The same could be achieved by adding matplotlib.dates.EPOCH_OFFSET instead of datestr2num. As unlikely as change of epoch, this would tie us better to their system, I think.

I checked it right now, it appears to be cleaner, *but* `EPOCH_OFFSET` always returns the offset of the old mpl epoch.

> And btw, both EPOCH_OFFSET and datestr2num('1970-01-01') return 719163.0 while in our code there is 719163.

That's the same number. If you update your matplotlib installation, EPOCH_OFFSET is still 719163.0 while datestr2num('1970-01-01') is 0.0.

**Comment by heavelock** [comment]
Aaaaah, okay. Now I understand the issue. 

So I think the PR is good to go.

**Review by heavelock — APPROVED** [review]

**Comment by megies** [comment]
Do we need a changelog entry for this? Looks like it might be good to have one

**Comment by trichter** [comment]
OK, I can add a changelog entry.

**Pull request merged**
