### PR TITLE
SEG2 date/time parsing relaxation

### PR DESCRIPTION
**Pull request by janwillembuist**
### What does this PR do?

This PR makes the date/time parsing in the seg2 module less strict. If only the date is provided, it will save at least the date instead of raising an error.

### Why was it initiated?  Any relevant Issues?

I was handling some seg2 data which did not have recorded seconds in their "ACQUISITION_TIME", this resulted in an unwanted error on obspy's side. Therefore I initiated this pull request.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [x] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] New modules, add the module to `CODEOWNERS` with your github handle
- [x] Add the yellow `ready for review` label when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
Thanks for the PR.

If you have a small example file you can share that would be interesting to see, makes it easier to review the changes. Could also be used to set up a test for the new behavior.
If not, I guess existing tests still pass, so it should be OK.

changelog should go to the very top under "master" (ongoing changes for next major release), but that can be fixed later, dont worry about it too much, this will need a rebase and minor cleanup anyway.

**Comment by janwillembuist** [comment]
Hi Tobias,

See attached one of the seg2 files without seconds in it. 

[seg2_file_no_seconds.zip](https://github.com/obspy/obspy/files/11000542/seg2_file_no_seconds.zip)

**Comment by megies** [comment]
@janwillembuist I fixed the branch's history so we can merge this and rebased it. I would recommend to make branches for future PRs directly from `obspy/master` branch, I was confused first but then noticed you used your fork's master branch for a different PR in the past, so its history was out of sync with our master branch.

Personally, I'd recommend to just ignore the master branch from your own fork and add our main repo as a remote (if you don't have it already) and then just make new branches always based on current main repo master or maintenance branches. Hope that makes sense ;)

**Review by megies — APPROVED** [review]
Good to go if CI turns green

**Comment by janwillembuist** [comment]
Thanks a lot! I'm not the biggest git expert but will follow your suggestion if I have some future contributions!

**Comment by megies** [comment]
> Thanks a lot! I'm not the biggest git expert but will follow your suggestion if I have some future contributions!

Yep, no worries and thanks for doing a PR :rocket:

**Pull request merged**
