### PR TITLE
Skipping coverage run for macOS test runner

### PR DESCRIPTION
**Pull request by ThomasLecocq**
this test passed: https://tests.obspy.org/114612/
this not: https://tests.obspy.org/114654/

although very close in time, so maybe setuptools version is culprit?

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is related to #2722 #2489 #2900
- [x] All tests still pass (well, we didn't know some didn't pass (e.g. the windows ones, so... back to work!)
- [x] Significant changes have been added to `CHANGELOG.txt` .

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
I suspect the GCF fails on windows are related to numpy 1.22 and changes in dtypes or else... but that's another story! the tests PASS :-)

**Review by d-chambers — APPROVED** [review]

**Comment by d-chambers** [comment]
Great work @ThomasLecocq!

**Comment by ThomasLecocq** [comment]
Thanks!!! Merged!

**Comment by heavelock** [comment]
@ThomasLecocq Congrats on fixing it!

**Pull request merged**
