### PR TITLE
Restructure parsing of css/wfdisc files in obspy.io.css.core

### PR DESCRIPTION
**Pull request by atwinkelman**
See #1290

### CODE REVIEW

**Comment by QuLogic** [comment]
Sorry, but while you are targetting `maintenance_1.0.x`, you _started_ with `master`. That branch will, in general, contain things that are not bug fixes and are thus not suitable for the 1.0.x line. You should rebase so that you start with `maintenance_1.0.x` and only your commit appears.

Unfortunately, you did not start a branch specifically for this PR, so your `master` will temporarily have to be behind for a bit, but I think that shouldn't be a major problem if you aren't really using the development version.

**Comment by megies** [comment]
To add to the above explanations, if you're working with git on the command line you should `git rebase maintenance_1.0.x` and then force-push (`git push -f`) to this branch.

**Comment by atwinkelman** [comment]
Ah, I was wondering why there were other commits and more than one file changed. Thanks for being patient. If you couldn't tell, I am new to contributing on GitHub. 

Should I open a new PR or can this one be changed appropriately?

**Comment by krischer** [comment]
You can change this one. Just force push, e.g. `git push --force` to it.

**Comment by QuLogic** [comment]
@megies' instructions for rebasing left out the interactive part. You need to do `git rebase --interactive` and then remove the commits you did not make. Otherwise, you will get the same results as now, just without the merge commits.

**Comment by megies** [comment]
Hmm.. and on top of everything.. actually, this now seems to fall more in the new feature direction, right? So the current commit history would actually be OK but the base branch not appropriate (should then be `master`..), which can unfortunately (never got why) not be changed by design on github..

**Comment by atwinkelman** [comment]
I've rebased to maintenance_1.0.x, made the suggested changes as in the latest discussion in #1290 and updated my repo. Let me know if I need to do anything different.

@megies It sure would be easier for my understanding/learning git if I could just change the pull request.

**Comment by krischer** [comment]
I would suggest you close this PR and open a new one to merge these changes into `master`. This is not a bugfix and it actually contains new features.

A couple more things that need to be done:

* The `is_nnsa_kb_core()` and `read_nnsa_kb_core()` functions have to be added to the ObsPy root level `setup.py` file to register them as new plug-ins within ObsPy.
* A small test case to detect and read an NNSA KB core file is needed. Please select an openly available file that is as small as possible (on the order of single kilobytes if possible). Just copy this test case (https://github.com/obspy/obspy/blob/master/obspy/io/css/tests/test_core.py) and repeat the things for an NNSA KB Core file.
* Add an entry to the root level changelog.
* Add yourself to the contributors if you want to.

**Pull request closed without merging**
