### PR TITLE
updated algorithm to split and encode data into blocks and addded test

### PR DESCRIPTION
**Pull request by paitor**
### What does this PR do?
Fixes a BUG in the algorithm to split and encode last few data points into GCF blocks 

### Why was it initiated?  Any relevant Issues?

Issue were brought up in post "MiniSEED to GCF" in discourse.obspy.org forum (https://discourse.obspy.org/t/miniseed-to-gcf/1598)

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [x] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [x] All tests still pass.
- [x] Any new features or fixed regressions are covered via new tests.
- [x] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [x] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [x] New modules, add the module to `CODEOWNERS` with your github handle
- [x] Add the `ready for review` tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Review by megies — CHANGES_REQUESTED** [review]
Needs to be rebased on `maintenance_1.4.x`.

Alternatively you could try something like
 - `git reset --hard maintenance_1.4.x` # caution! will get rid of any unsaved local changes!
 - `git cherry-pick 53bf2ec f0310d5`

**Comment by paitor** [comment]
Seems I'm having a hard time to wrap my head around git so some additional pointers would be appreciated, trying the suggested command yields (adding some additional info):
```
dev@lap:~/dev/obspy/obspy$ git branch -v
* fix_gcf_block_bug f0310d548 updated changelog
  master            49b8b411f Merge pull request #3243 from obspy/energy_ratio_adjustments
dev@lap:~/dev/obspy/obspy$ 
dev@lap:~/dev/obspy/obspy$ git status
On branch fix_gcf_block_bug
Your branch is up-to-date with 'origin/fix_gcf_block_bug'.

nothing to commit, working tree clean
dev@lap:~/dev/obspy/obspy$ git reset --hard maintenance_1.4.x
fatal: ambiguous argument 'maintenance_1.4.x': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
Also the sub-title of this PR is:
 "[paitor](https://github.com/paitor) wants to merge 15 commits into [obspy:maintenance_1.4.x](https://github.com/obspy/obspy/tree/maintenance_1.4.x) from [paitor:fix_gcf_block_bug](https://github.com/paitor/obspy/tree/fix_gcf_block_bug)"
which lead me to believe I had based it of maintenance_1.4x

**Comment by megies** [comment]
> dev@lap:~/dev/obspy/obspy$ git reset --hard maintenance_1.4.x
> fatal: ambiguous argument 'maintenance_1.4.x': unknown revision or path not in the working tree.

Hmm, it might be that git is confused because you do not have a local branch `maintenance_1.4.x` and with multiple remotes it does not know which one you mean. Try this:

```
git reset --hard origin/maintenance_1.4.x
```

..where "origin" would be the name of the obspy main repository in your remotes list (list them with `git remote -v`)

If that still does not work, you do not have that part of the git history in your local copy, try updating with `git fetch --all`.



> Also the sub-title of this PR is:
> "[paitor](https://github.com/paitor) wants to merge 15 commits into [obspy:maintenance_1.4.x](https://github.com/obspy/obspy/tree/maintenance_1.4.x) from [paitor:fix_gcf_block_bug](https://github.com/paitor/obspy/tree/fix_gcf_block_bug)"
> which lead me to believe I had based it of maintenance_1.4x

That's because I changed the PR to be merged into `maintenance_1.4x`, it said `master` before I changed it yesterday.

**Comment by megies** [comment]
@paitor, also if all else fails, you could simply make a new branch, a new PR and just base that branch off of maintenance and cherry pick those two commits

**Comment by paitor** [comment]
That's the thing I thought I had made a new branch, anyway I'll give it a
new try tonight, thanks for the input.

Mvh P

**Comment by paitor** [comment]
So problem turned out to be (my updated current understanding) that I had forked obspy 1.3 and then were working on a clone of this so of course the branch maintenance_1.4.x did not exist. Solution to (delete the fork and) clone the master directly and submit a new PR

**Comment by paitor** [comment]
I.e. continued in #3252

**Comment by megies** [comment]
you can add more remotes with `git remote add ...` e.g. `git remote add obspy git@github.com:obspy/obspy.git` and then after a `git fetch` of `git fetch --all` the missing branch info would've been there =)

**Pull request closed without merging**
