### PR TITLE
fix PPSD time restrictions in stacking, compare >=/<= instead of >/<

### PR DESCRIPTION
**Pull request by megies**
Fix PPSD time restrictions in stacking, compare >=/<= instead of >/<.

### CODE REVIEW

**Comment by megies** [comment]
@ThomasLecocq since this is on your request, could I ask you to double check this change, especially since the test had to be changed. Otherwise we'll have to bump this to 1.0.3.

**Comment by megies** [comment]
Bumping to 1.0.3 because we can get 1.0.2 out then soon.

**Comment by megies** [comment]
Changed base branch to `maintenance_1.1.x`. Should ideally rebase on this base branch, eventually. But waiting for feedback from @ThomasLecocq anyway.. ;-P

**Comment by ThomasLecocq** [comment]
wooooooooooooooooooooow :-) why in the world did I let this one behind ???? 

Now, see, I did remember we already talked about it :-)

**Comment by megies** [comment]
Base branch will have to be changed either to `master` or to `maintenance_1.2.x` once 1.2.0 is released.

**Comment by megies** [comment]
Still waiting for feedback in 2022 @ThomasLecocq :stuck_out_tongue_closed_eyes: 

Gonna probably just merge this for 1.3.1 :wink:

**Pull request merged**
