### PR TITLE
fix azimuth in Taup for distances > 180 and attach to arrival object

### PR DESCRIPTION
**Pull request by MMesch**
see #1278.

Another addition: azimuth is attached to the arrival object as well

### CODE REVIEW

**Comment by MMesch** [comment]
@QuLogic can you rerun AppVeyor somehow? It didn't work because of basemap ...

**Comment by QuLogic** [comment]
Can you rebase anyway? There are conflicts, and the new flake8 is going to cause the build to fail without the fixed items.

**Comment by megies** [comment]
Good to merge I guess?

**Comment by MMesch** [comment]
from my side yes!

**Pull request merged**
