### PR TITLE
earthworm client: Streamline trace cleanup

### PR DESCRIPTION
**Pull request by tparker-usgs**
Migrated from #1711 

Merge adjacent traces as they are received from the server.

### CODE REVIEW

**Comment by megies** [comment]
Looks good from a first glance.. thanks @tparker-usgs! The change is simple enough, changing over to numpy arrays would have been much more work. Curious.. what's the speedup of this fix, did you do some simple benchmarks/comparisons?

**Comment by tparker-usgs** [comment]
Thanks for the positive comments!

The speedup is pretty dramatic, especially as the request size grows. I sent 10 requests each of various lengths to a my nearby wave server. The mean times are:

| Request Length (hours) |  1.0.3 Run Time (s) | New Run Time (s) |
|:-----------------------:|:-----------------:|:----------------:| 
| 1 | 6.19 | 0.79 |
| 2 | 13.61 | 1.85 |
| 6 | 48.06 | 7.14 |
| 12 | 125.71 | 9.61 |

**Comment by megies** [comment]
+TESTS:clients.earthworm  to see how existing tests fare with this PR

**Comment by megies** [comment]
At least existing tests still pass on Linux: http://tests.obspy.org/?pr=1762&node=travis-ci
(Strange why Travis didn't execute earthworm tests on MacOS...)

**Comment by krischer** [comment]
Thanks for this! I rebased no `master` and added a changelog entry.

**Comment by tparker-usgs** [comment]
Thank you!

**Pull request merged**
