### PR TITLE
Allow 60s and NaN magnitude in PHA format

### LINKED ISSUE #2627: Bug in hypodd PHA read
HypoDD PHA read does not read a catalog file that I downloaded from the OOI website: http://axial.ocean.washington.edu/#name6 because it could not handle "NaN" as a magnitude
nor seconds outside the range of 0..59.  Neither of these are explicitly allowed (or disallowed) 
in the HypoDD docs I found, but the file is of general interest and the solution simple.  Here is
the code that reproduces the error, using the files attached in [error_example.zip](https://github.com/obspy/obspy/files/4756520/error_example.zip):

```python
#!/bin/env python3
from obspy.core.inventory.inventory import read_inventory
from obspy.core.event.catalog import read_events

inv = read_inventory('OO_SP_stationonly.xml')
cat = read_events('ph2dt_example_errors.dat', 'HYPODDPHA', inventory=inv,
                  id_default='OO.{}.00.EH{}')
print(cat)
```
which results in:
```
Traceback (most recent call last):
  File "error_example.py", line 7, in <module>
    id_default='OO.{}.00.EH{}')
  File "<decorator-gen-46>", line 2, in read_events
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/catalog.py", line 812, in read_events
    return _generic_reader(pathname_or_url, _read, format=format, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/base.py", line 701, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "<decorator-gen-47>", line 2, in _read
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/catalog.py", line 821, in _read
    **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/base.py", line 469, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 112, in _read_pha
    for block in text.split('#')[1:]]
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 112, in <listcomp>
    for block in text.split('#')[1:]]
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 51, in _block2event
    magnitude = Magnitude(mag=mg, resource_id="smi:local/magnitude/" + id_)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/base.py", line 405, in __init__
    **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/base.py", line 226, in __init__
    setattr(self, key, value)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/base.py", line 391, in __setattr__
    raise ValueError(msg)
ValueError: On Magnitude object: Value 'nan' for 'mag' is not a finite floating point value.
```
To make it work, I had to change the first lines in `io/hypodd/pha.py:_block2event()`
Original:
```python
    lines = block.strip().splitlines()
    yr, mo, dy, hr, mn, sc, la, lo, dp, mg, eh, ez, rms, id_ = lines[0].split()
    time = UTCDateTime(int(yr), int(mo), int(dy), int(hr), int(mn), float(sc))
```
Final:
```python
    lines = block.strip().splitlines()
    yr, mo, dy, hr, mn, sc, la, lo, dp, mg, eh, ez, rms, id_ = lines[0].split()
    if mg == 'NaN':
        mg = None
    time = UTCDateTime(int(yr), int(mo), int(dy), int(hr), int(mn)) + float(sc)
```
(there is probably a smarter "if" statment that covers other possible problems).

The code now returns:
```
18 Event(s) in Catalog:
2015-03-04T01:59:55.413000Z | +45.950, -129.986 | 0.0 None
2015-03-04T02:00:35.871000Z | +45.984, -129.993 | None None
...
2015-03-29T22:40:10.109000Z | +45.927, -129.997 | -0.0 None
2015-03-29T22:40:20.110000Z | +45.953, -129.983 | -0.3 None
To see all events call 'print(CatalogObject.__str__(print_all=True))'
```
If I change only  the lines with `mg` I get the following error:
```
Traceback (most recent call last):
  File "error_example.py", line 7, in <module>
    id_default='OO.{}.00.EH{}')
  File "<decorator-gen-46>", line 2, in read_events
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/catalog.py", line 812, in read_events
    return _generic_reader(pathname_or_url, _read, format=format, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/base.py", line 701, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "<decorator-gen-47>", line 2, in _read
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/catalog.py", line 821, in _read
    **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/base.py", line 469, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 114, in _read_pha
    for block in text.split('#')[1:]]
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 114, in <listcomp>
    for block in text.split('#')[1:]]
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 31, in _block2event
    time = UTCDateTime(int(yr), int(mo), int(dy), int(hr), int(mn), float(sc))
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/utcdatetime.py", line 466, in __init__
    dt = datetime.datetime(*args, **kwargs)
ValueError: second must be in 0..59
```
I have attached a version of `pha.py` with these modifications

obspy version = 1.2.1, installed using Anaconda

### PR DESCRIPTION
**Pull request by trichter**
### What does this PR do?

Fixes #2627 in the maintenance branch.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [x] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
I was checking the CI results in http://tests.obspy.org/?pr=2658, looks like `io.hypodd` never was run by `obspy-runtests` so far..

**Comment by megies** [comment]
@trichter, there seems to be a change in a doctest. I don't understand since it seems there was a valid magnitude value and now it looks like the magnitude is omitted: 
 - http://tests.obspy.org/111152/#1
 - http://tests.obspy.org/?pr=2658

**Comment by trichter** [comment]
Yes, my fault. I changed the test data file in the first commit. I will deal with the error.

**Comment by megies** [comment]
can you do a "git rebase maintenance_1.2.x" or maybe "git rebase -i maintenance_1.2.x", that should get rid of that merge commit

**Comment by trichter** [comment]
Yes, I rebased the branch.

**Pull request merged**
