### PR TITLE
Taup geo bug

### PR DESCRIPTION
**Pull request by MMesch**
this fixes a little bug in taup_geo. If the distance is larger than 180 degrees, the azimuth points in the wrong direction. Not sure if the fix works for distances > 360 degrees though. It is just a proposition without extensive testing.

### CODE REVIEW

**Comment by QuLogic** [comment]
Is this a bug fix that should go in 1.0.x?

**Comment by MMesch** [comment]
well right now the lon/lat paths are wrong for distances > 180 degrees. So I think as soon as possible but I don't know how you handle such things in obspy...

**Comment by QuLogic** [comment]
Can you add a test as well?

**Comment by MMesch** [comment]
ok here is a test. It doesn't test the pierce points ! I have no idea how to do that easily ...

**Comment by megies** [comment]
@MMesch for future PRs: If it's a bug, it should go into `maintenance_0.10.x` (and branched off of it too, of course), see https://github.com/obspy/obspy/wiki/ObsPy-Git-Branching-Model.

But it's not a big deal here because `master` and `maintenance_0.1.x` haven't diverged significantly.. yet.

Since the base branch of a PR can not be changed after opening it, I would recommend the following (in order to not have another duplicate issue, with discussion split up among different tickets..):
 * continue fixing this issue here on your branch based on master
 * when ready to merge:
   * don't merge this into master
   * checkout another branch based on this branch (e.g. `taup_bug2`)
   * rebase that branch on `maintenance_1.0.x`
   * merge into `maintenance_1.0.x`
   * merge `maintenance_1.0.x` into `master`
   * close this PR

That way also the diff view in this PR is not lost.

**Comment by megies** [comment]
Also, if this is something that might puzzle people who run into it a changelog entry might be good. If it's something that fails with a very clear information or Exception a changelog entry might not be necessary..

**Comment by MMesch** [comment]
ok. I rebased it on maintenance. Should I open a new PR then?

**Comment by krischer** [comment]
Yes. Github unfortunately does not allow to change the branch one wants to merge into :-(

**Comment by megies** [comment]
Ok, so closing as a duplicate of #1289.

**Pull request closed without merging**
