### PR TITLE
remove arclink client

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Removes arclink client

### Why was it initiated?  Any relevant Issues?

It has been deprecated for years, officially discontinued and main
servers have been shut down years ago. no point dragging this along

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [x] Add the "ready for review" tag when you are ready for the PR to be reviewed.

@trichter, feel free to bump to a later release

### CODE REVIEW

**Comment by trichter** [comment]
For me it's both OK, remove it now or right after the release of 1.3.0.

**Comment by d-chambers** [comment]
Should we think about removing the other depreciated modules at the same time?

**Comment by megies** [comment]
> Should we think about removing the other depreciated modules at the same time?

which ones? but probably.. yes.. since its been a real long time since last release anyway

**Comment by d-chambers** [comment]
> which ones? but probably.. yes.. since its been a real long time since last release anyway

At least obspy.db and obspy.client.sieshub

**Comment by megies** [comment]
> At least obspy.db and obspy.client.sieshub

I'd say yes, let's get rid of those two as well this release. I don't think these see much use anymore and we still have them in previous releases.

**Comment by megies** [comment]
Hmm.. actually, I realized that they have not been marked deprecated in last release, only in master. So.. not sure

**Comment by megies** [comment]
I'll push the remove commit anyway, since I was already done. Can still discuss and roll back that commit here

**Comment by d-chambers** [comment]
I don't think it is a big deal since they probably aren't used much anyway, but I don't have a strong opinion.

**Review by d-chambers — APPROVED** [review]

**Comment by trichter** [comment]
It's also no big deal if they stay in the next release. Both options are good with me.

**Comment by megies** [comment]
I got rid of the second commit that removed `db` and `clients.seishub`, to stay in line with our policy of showing a deprecation message for at least one major release before removing stuff.

**Comment by megies** [comment]
Rebased on current master

**Comment by megies** [comment]
Good to go from my point of view

**Review by trichter — APPROVED** [review]
Sorry, another line in pytest.ini can be removed.

**Comment by trichter** [comment]
> I got rid of the second commit (https://github.com/obspy/obspy/commit/ff6a21736c19f14c5890eb41d65393832526be96) that removed db and clients.seishub, to stay in line with our policy of showing a deprecation message for at least one major release before removing stuff.

You could move it to another branch. We can merge it after the release.

**Pull request merged**
