### PR TITLE
fix Stream.rotate with multiple-station or multiple-event streams

### PR DESCRIPTION
**Pull request by trichter**
### What does this PR do?

Fix Stream.rotate() with multiple-station Streams

### Why was it initiated?  Any relevant Issues?

See #2623

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [x] All tests still pass.
- [x] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [x] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
rebased and force pushed

**Comment by megies** [comment]
I'm not sure about this one @trichter.. it looks like more magic introduced by this PR, I would've just gone with a recursive scheme which is not changing the existing logic. That should work without problems, although I didn't write rigorous tests for it yet.

**Comment by trichter** [comment]
> it looks like more magic introduced by this PR,

I think I disagree, because this PR introduces minimal changes. It just looks up the baz and inci in the stats object of the first trace of the rotating substream and not in the first trace of the whole stream. As before it assumes the traces are already correctly sorted.

It also fixes a test case which I think was created exactly for this issue, but did not fail. (Now it would fail if only the test case was changed.)

Your PR is also nice, and IMHO includes much more magic than this one :) It fixes a different issue https://github.com/obspy/obspy/issues/2623#issuecomment-639872511. This issue here is fixed on the way, but not completely. I think the test case adapted in this PR will fail. It simulates the case in which two events are registered at a single station.

**Comment by megies** [comment]
superseded by #3155

**Pull request closed without merging**
