### PR TITLE
Fix taup py37 failures

### PR DESCRIPTION
**Pull request by d-chambers**
### What does this PR do?
I am attempting to fix the python 3.7 TauP failure on Travis in the least invasive way possible. 

### Why was it initiated?  Any relevant Issues?
#2269 fixed a lot of failures on master but we weren't sure how to fix this one.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [x] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by d-chambers** [comment]
@calum-chamberlain, what do you think of this? It is a bit of a hack but since no TauP experts are forthcoming this seems like a reasonable compromise. Hopefully all tests turn green after this change.

**Comment by calum-chamberlain** [comment]
This looks good to me. 

If we are uncertain about whether the implementation will impact anyones codes then we could warn that the reference to the original array is lost. It might also be worth linking to this PR so that if an issue does arise then the user can quickly find out why. I don't really like that idea, but its more of a "covering-our-backs" thing.

**Comment by d-chambers** [comment]
Yes, it is probably better to annoy than to surprise.

**Comment by calum-chamberlain** [comment]
The appveyor fail is an unrelated fail as far as I know - trace similarity things as we also discussed in #2269 
Looks good to me!

**Comment by megies** [comment]
Thanks @d-chambers!

**Pull request merged**
