### PR TITLE
taup: Support for buried receivers

### PR DESCRIPTION
**Pull request by QuLogic**
This is a port of buried receivers from the TauP prerelease (see commit messages for specifics.) Once this is merged, it should be easier to apply the fixes noted in #986. This is currently targeting 0.11 since it's an enhancement, but if we want the above bugfixes, it might be necessary to backport to 0.10. 

One test is failing; I am not sure if I made a mistake or whether the tests should be updated (some commit messages in TauP indicated some tests _might_ have needed updating.) @krischer Are you able to run the prerelease as well to run some checks?

I added a test _plot_, but no numerical tests. @krischer If you can run the prerelease, maybe you can add some tests as well? Otherwise, I'll look into running the prerelease TauP eventually.

### CODE REVIEW

**Comment by megies** [comment]
> it might be necessary to backport to 0.10.

Fine with me. Just do what is easiest, more important to not waste precious time trying to prevent a minor feature change leaking back.

**Comment by krischer** [comment]
I replaced the part thats failing with the output from the prerelease. For some reason it suddenly produces way less phases (but that might just due to it being at the CMB and some phase naming reasons) but that is consistent with your changes.

There are unfortunately a couple more differences. The takeoff angle appears to be off 180 - x degrees. Maybe some sign error somewhere? The traveltime is also a tiny bit off compared to the output from the prerelease java version. The difference is very small and I cannot tell if this will get away by the time we manage to implement the remaining changes.

None of the command line utilities can set the receiver depth (or at least I did not find the settings). I'll give the jython console a try once I get around to it to generate some test data for the buried receivers.

**Comment by QuLogic** [comment]
I think the `180 - x` thing might have been added in some later commits; I'll have a look for them. I think the command-line utilities should be able to take a `--stadepth` option.

**Comment by QuLogic** [comment]
I made some changes so that takeoff and incident angle calculations are consistent with the prerelease, but some new tests failures arose. They will probably need to be updated.

**Comment by QuLogic** [comment]
Ping? I'd like to add the other corrections.

**Comment by krischer** [comment]
I added a simple test for a buried receiver. It (and others) currently fails due to the aforementioned reasons.

I'm not sure how to best proceed here. Merge this and live with a failing master branch for a while? Keep working on this branch? Make a new branch from this branch here?

I would prefer one of the latter two options.

**Comment by QuLogic** [comment]
Oh, that's weird, I thought I had applied everything that could be related to angles. I guess we'll have to try implementing the rest and see how things go.

**Comment by megies** [comment]
@QuLogic, @krischer, what's the status on this? Close to be ready or rather punt it to future release?

**Comment by QuLogic** [comment]
We think it needs the long phase fixes; I'll work on that later tonight or tomorrow. I think it's nearly there now.

**Comment by megies** [comment]
What's it with the failing tests? I guess those are these fixed in master by merging #1189?

**Comment by krischer** [comment]
Should be fixed. #1189 had no test failures.

**Comment by QuLogic** [comment]
Yea, we never really figured out why it failed here as the buried receiver and long phase stuff is all mixed together in the Java version.

**Comment by megies** [comment]
Yeah, that's what I figured more or less.. :+1:

**Pull request merged**
