### PR TITLE
PPSD: add a switch for hydrophone data

### PR DESCRIPTION
**Pull request by megies**
... and unify with special handling of rotational data (from ringlaser).

I was asked whether we could add support for hydrophones (omitting the differentiation in processing), so here goes. There could be better / more canonical ways to do this.. any other suggestions welcome. One downside of unifying the handling of ring laser data could be problems when loading an old pickle. I'm trying to avoid those problems but this should be tested..

### CODE REVIEW

**Comment by QuLogic** [comment]
Should you not add a `deprecated_keyword` decorator for `is_rotational_data`?

**Comment by megies** [comment]
Need to get this inline with #1108...

**Comment by megies** [comment]
> Should you not add a deprecated_keyword decorator for is_rotational_data?

It's handled in a more custom fashion inside the routine as the decorator can't map from `is_rotational_data=True` to `special_handling=ringlaser`.

**Comment by megies** [comment]
@sstaehler, since this was originally prompted by you.. can you maybe comment on whether this still meets the hydrophone data needs (there was a change to the response removal with #1108)?

**Comment by megies** [comment]
Don't have test data, so including without test. We can add some if people using this report back.

**Pull request merged**
