### PR TITLE
Adding more location codes to the default priority list

### LINKED ISSUE #2155: massdownloader not finding stations
If you run the code below, the massdownloader wont find any stations/data in the circular region.  However I know there are stations there with data, and in the bottom of attached code, I show that the normal fdsn  client.get_stations  returns what I expect.

Am I doing something wrong? Or is there something broken in the massdownloader?

```

import obspy
from obspy.clients.fdsn.mass_downloader import CircularDomain, Restrictions, MassDownloader
from obspy.clients.fdsn import Client
from obspy.core import UTCDateTime
from obspy.clients.fdsn.header import URL_MAPPINGS

lat = 39.883
lon = -88.901
minR = 0.0
maxR = 1.0


st = obspy.UTCDateTime(2014,1,1, 1,0,0)
et = st+(3600*24*14)       

# via the massdownloader
print('\n\n')
print('------------- MASSDOWNLOADER OUTPUT -------------------')
domain = domain = CircularDomain(latitude=lat, longitude=lon, minradius=minR, maxradius=maxR)
restrictions = Restrictions( starttime=st, endtime=et, network='GS', minimum_length=0, reject_channels_with_gaps=False, sanitize=False)

mdl = MassDownloader(providers=['IRIS'])
mdl.download(domain, restrictions, mseed_storage="tmp/waveforms", stationxml_storage="tmp/stations") 



#now via the regular fdsn
print('\n\n\n\n')
print('--------------- FDSN Client.getStations OUTPUT ----------' )
client = Client('IRIS')
inv = client.get_stations(network='GS', starttime=st, endtime=et, latitude=lat, longitude=lon, minradius=minR, maxradius=maxR)

print(inv)

```

Here is the output...

```
------------- MASSDOWNLOADER OUTPUT -------------------
[2018-05-21 17:25:02,308] - obspy.clients.fdsn.mass_downloader - INFO: Initializing FDSN client(s) for IRIS.
[2018-05-21 17:25:06,285] - obspy.clients.fdsn.mass_downloader - INFO: Successfully initialized 1 client(s): IRIS.
[2018-05-21 17:25:06,285] - obspy.clients.fdsn.mass_downloader - INFO: Total acquired or preexisting stations: 0
[2018-05-21 17:25:06,285] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Requesting reliable availability.
[2018-05-21 17:25:06,461] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Successfully requested availability (0.18 seconds)
[2018-05-21 17:25:06,467] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Found 0 stations (0 channels).
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - No data available.
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: ============================== Final report
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: 0 MiniSEED files [0.0 MB] already existed.
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: 0 StationXML files [0.0 MB] already existed.
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Acquired 0 MiniSEED files [0.0 MB].
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Acquired 0 StationXML files [0.0 MB].
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: Downloaded 0.0 MB in total.



--------------- FDSN Client.getStations OUTPUT ----------
Inventory created at 2018-05-21T23:25:06.000000Z
	Created by: IRIS WEB SERVICE: fdsnws-station | version: 1.1.33
		    http://service.iris.edu/fdsnws/station/1/query?starttime=2014-01-01...
	Sending institution: IRIS-DMC (IRIS-DMC)
	Contains:
		Networks (1):
			GS
                Stations (12):
			GS.DEC01 (Heartland Borehole/Surface)
			GS.DEC02 (ADM Borehole/Surface)
			GS.DEC03 (Forest Parkway Borehole/Surface)
			GS.DEC04 (Sangamon Road Surface Site)
			GS.DEC05 (Apollo Drive Surface Site)
			GS.DEC06 (Neely Ave Surface Site)
			GS.DEC07 (Harrison Ave Surface Site)
			GS.DEC08 (Union Local 159 Surface Site)
			GS.DEC09 (Kile Street Surface Site)
			GS.DEC10 (Finch Street Surface Site)
			GS.DEC11 (Phillips Surface Site)
			GS.DEC12 (Boyd Road Surface Site)
		Channels (0):
```

### PR DESCRIPTION
**Pull request by krischer**
See discussion in #2155. Fixes #2155.

### CODE REVIEW

**Comment by megies** [comment]
If you can be bothered, I think it would be really nice to have a warning message when stations are dropped because they have data but all channels are dropped due to location priorities (esp. when the default is in effect). Not sure how complicated that would be to add..?

**Comment by krischer** [comment]
> If you can be bothered, I think it would be really nice to have a warning message when stations are dropped because they have data but all channels are dropped due to location priorities (esp. when the default is in effect). Not sure how complicated that would be to add..?

Good idea. I added some more commits to this PR to implement it.

**Comment by krischer** [comment]
Test failures in CI are unrelated (and weird - does someone understand them?). Merging.

**Comment by megies** [comment]
Thanks for adding that message, I think this is in really good shape now.

**Pull request merged**
