### PR TITLE
Ignore DeprecationWarnings and PendingDeprecationWarnings triggered by other modules

### PR DESCRIPTION
**Pull request by trichter**
### What does this PR do?

See title. It adds two filters to pytest.ini

### Why was it initiated?  Any relevant Issues?

Deprecation warnings triggered in external modules have to be fixed upstream. E.g. this deprecation in shapely has to be fixed in cartopy and it should not be shown in our test results:
https://tests.obspy.org/132205/#1

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] New modules, add the module to `CODEOWNERS` with your github handle
- [x] Add the `ready for review` tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by trichter** [comment]
@megies

`1 << 7 == 128` and `np.int8(128)=-128`

This is probably not the desired result?

```
Traceback (most recent call last):
File "[/usr/share/miniconda3/envs/test/lib/python3.11/site-packages/obspy/io/mseed/tests/test_mseed_util.py](https://github.com/obspy/obspy/blob/32cb3df757/obspy/io/mseed/tests/test_mseed_util.py#L309)", line 309, in test_get_flags
_create_mseed_file(
File "[/usr/share/miniconda3/envs/test/lib/python3.11/site-packages/obspy/io/mseed/tests/test_mseed_util.py](https://github.com/obspy/obspy/blob/32cb3df757/obspy/io/mseed/tests/test_mseed_util.py#L75)", line 75, in _create_mseed_file
arr[:flags[key][name]] = 1 << _i
~~~^^^^^^^^^^^^^^^^^^^
DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays. The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
```

**Comment by d-chambers** [comment]
The warning filters look fine, I didn't realize you could use them to ignore everything except a specified module, neat trick. 

I am not following the error from the bit shift magic going on in the miniseed module though. Is that related to the new warning filters?

**Comment by trichter** [comment]
> I am not following the error from the bit shift magic going on in the miniseed module though. Is that related to the new warning filters?

I do not understand what exactly is tested here, but some values of 128 were silently converted to -128 by np.int8. This is deprecated in NumPy's newest version 1.24.0. It is also visible as [warning](https://tests.obspy.org/132169/) on master, but the traceback is only visible in this branch (via `-W error`), because the other warning which is filtered here is raised earlier.

**Comment by megies** [comment]
> @megies
> 
> `1 << 7 == 128` and `np.int8(128)=-128`
> 
> This is probably not the desired result?

I have no idea what is going on in there, but that definitely doesn't feel right. Ideally somebody with better mseed internals knowledge could help sort it out, so we don't have to dig it up..?
In any case, if you change the dtype of that array to `uint8` so that `128` can be stored in there the test passes as well, which is kinda weird but makes me think maybe the dtype is just bad and maybe mseed is looking at `abd()` of these values..? No idea, really.

**Review by megies — APPROVED** [review]

**Pull request merged**
