### PR TITLE
adding RASPISHAKE to FDSN mapping

### PR DESCRIPTION
**Pull request by iannesbitt**
### What does this PR do?

This adds the base of the Raspberry Shake FDSN tree (http://fdsnws.raspberryshakedata.com) to the URL mapping list under `"RSHAKE"` so that it can be accessed via

```
client = Client("RSHAKE")
```

### Why was it initiated?  Any relevant Issues?

This is being initiated to add the [RASPISHAKE datacenter](ds.iris.edu/files/stats/datacenters/) (DOI: [10.7914/SN/AM](https://doi.org/10.7914/SN/AM)) to the list of URL mapping endpoints.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+DOCS"
- [x] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:clients.fdsn"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [x] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by iannesbitt** [comment]
It looks like (relevant) tests have passed, so updating PR checkbox above.

**Comment by krischer** [comment]
One thing to consider is if we should exclude this special data center from the default data centers in the mass downloader (https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.mass_downloader.html).

It could still be included if users choose to do so but I think this should be an explicit choice given the non-standard nature of this particular data center. It might also hit it with a lot of potentially unwanted requests.

**Comment by megies** [comment]
> It could still be included if users choose to do so but I think this should be an explicit choice given the non-standard nature of this particular data center. It might also hit it with a lot of potentially unwanted requests.

:+1: 

Also, I'd vote for `RASPISHAKE`
 - `RSHAKE` is not an (semi)official abbreviation as far as I know
 - it's way clearer
 - only 3 chars longer
 - it's the official Twitter handle
 - it's the name in the FDSN datacenter list

**Comment by iannesbitt** [comment]
> Also, I'd vote for `RASPISHAKE`

I had considered this but decided against it because it was longer than any others, and required a reformatting of the tab alignment on the docs page. I agree that it fits better with the datacenter's other identifiers.

**Comment by iannesbitt** [comment]
> One thing to consider is if we should exclude this special data center from the default data centers in the mass downloader

@krischer disabled by default would be best I think.

**Comment by iannesbitt** [comment]
@krischer am I correct in assuming that the exclusion for RASPISHAKE is done in the init function of the MassDownloader class, i.e. [https://docs.obspy.org/_modules/obspy/clients/fdsn/mass_downloader/mass_downloader.html#MassDownloader.\_\_init\_\_](https://docs.obspy.org/_modules/obspy/clients/fdsn/mass_downloader/mass_downloader.html#MassDownloader.__init__)?

**Comment by megies** [comment]
Looks like it. Also please add a note in the docstring for `providers` that raspishake is omitted by default and has to be specified/added explicitly.
I guess one would have to do e.g. something like the following to get raspishake in there

```python
from obspy.clients.fdsn import URL_MAPPINGS
MassDownloader(providers=URL_MAPPINGS)
```

**Comment by iannesbitt** [comment]
@megies ok, consider these changes:

```python
class MassDownloader(object):
    """
    Class facilitating data acquisition across all FDSN web service
    implementations.

    :param providers: List of FDSN client names or service URLS. Will use
        all FDSN implementations known to ObsPy except RASPISHAKE if
        set to None. The order in the list also determines their priority, if data
        is available at more then one provider it will always be downloaded
        from the provider that comes first in the list. To include RASPISHAKE,
        you must set this parameter to
        :class:`~obspy.clients.fdsn.header.URL_MAPPINGS` explicitly.
    :param debug: Debug flag passed to the underlying FDSN web service clients.
    :type providers: list of str or :class:`~obspy.clients.fdsn.client.Client`
        instances
    """
    def __init__(self, providers=None, debug=False):
# ...
        if providers is None:
            providers = dict(URL_MAPPINGS.items())
            del providers['RASPISHAKE']
# ...
```

**Comment by megies** [comment]
This needs to be adapted: https://travis-ci.org/obspy/obspy/jobs/650081061#L1438

Also some trailing whitespace.

**Comment by megies** [comment]
@iannesbitt just for future reference, you should work on branches in your fork, your master is now out of sync with the main repo master branch.

**Comment by iannesbitt** [comment]
> @iannesbitt just for future reference, you should work on branches in your fork, your master is now out of sync with the main repo master branch.

Ok. Noted. Thanks for the quick responses.

**Pull request merged**
