### PR TITLE
Python only CatchOutput

### PR DESCRIPTION
**Pull request by barsch**
had to remove C level support due to http://bugs.python.org/issue30555
(_io._WindowsConsoleIO breaks in the face of fd redirection)

continues #1684 - had to close the other one as merging current master became a real pain ;/

### CODE REVIEW

**Comment by barsch** [comment]
imho ready for review - at least Win 3.6 does not crash anymore ...

Return values from the ```CatchOutput``` context manager are now normalized (unicode & same newline char) - hopefully no more encoding issues in tests itself ...

looks also like some C level messages are suppressed some not, maybe we can handle the following messages within C to bring in in line ...:

* ```obspy.core.tests.test_response.ResponseTestCase.test_segfault_after_error_handling``` with
   ```
   EVRESP ERROR (... [File: <stdin>; Start date: ; Stage: 2]):
	check_channel; units mismatch between stages,
	skipping to next response now
   ```
* ```obspy.io.gse2.tests.test_libgse2.LibGSE2TestCase.test_no_dat2_null_pointer``` with
   
   ```
   decomp_6b: Neither DAT2 or DAT1 found!
   ```

**Comment by barsch** [comment]
btw: why does codecov/patch complain - about all those files which I didn't even touch ... - I really would opt for removing this discouraging check!

**Comment by Jollyfant** [comment]
I don't think anyone really knows why codecov does that.. I always pretty much ignore it.

**Comment by megies** [comment]
> btw: why does codecov/patch complain about all those files which I didn't even touch ... - I really would opt to remove this discouraging check!

@barsch I'm assuming you're referring to [this tab labelled "changes"](https://codecov.io/gh/obspy/obspy/compare/5dc0cb774242e6065f7fc8d4f39f607d777ba7e6...d83048b79683766fabbbfdc2ae7fe6fd1508b703/changes)?

This option is [already disabled in the settings](https://github.com/obspy/obspy/blob/master/codecov.yml#L28-L30), and I agree that it's very confusing and not very helpful. We never could figure out why it goes so utterly wrong. While codecov does not send a commit status for it anymore, it still computes this result, so you can find it if you go that page "manually".
But.. the fail for "codecov/patch" has nothing to do with the strange "changes" section, but rather with the [coverage percentage in the diff](https://codecov.io/gh/obspy/obspy/compare/5dc0cb774242e6065f7fc8d4f39f607d777ba7e6...d83048b79683766fabbbfdc2ae7fe6fd1508b703/diff) (in the new lines): `"85.92% of diff hit (target 90%)"`

If you look at the diff, it's clear that the missed lines are in Windows specific parts that won't be reached on Travis (Linux), e.g. [these lines in `_py36_windowsconsoleio_workaround()`](https://codecov.io/gh/obspy/obspy/compare/5dc0cb774242e6065f7fc8d4f39f607d777ba7e6...d83048b79683766fabbbfdc2ae7fe6fd1508b703/diff#D8-362).

So, this is caused by the Win-specific nature of the PR, not much that can be done, but disabling "codecov/patch" is not an option, IMHO. It's necessary to ensure proper coverage levels of new code coming in in PRs.

**Comment by QuLogic** [comment]
> If you look at the diff, it's clear that the missed lines are in Windows specific parts that won't be reached on Travis (Linux), e.g. these lines in _py36_windowsconsoleio_workaround().

Is codecov not uploading on AppVeyor?

**Comment by megies** [comment]
Ideally we should have a test to prevent new additions that add verbosity during tests.. because it's a real pain to fix it later on. But not sure how to check that.. :-/

**Comment by megies** [comment]
> Is codecov not uploading on AppVeyor?

Nope.

https://github.com/obspy/obspy/blob/master/appveyor.yml#L122-L134

**Comment by megies** [comment]
Thanks @barsch for fixing this one on Win!

**Pull request merged**
