### PR TITLE
More fixes various small issues, typos, UserWarnings, deprecations, etc.

### PR DESCRIPTION
**Pull request by barsch**
someone was to fast merging the previous one ;)

### CODE REVIEW

**Comment by megies** [comment]
> someone was to fast merging the previous one ;)

ooops, who could that be.. ;-)

**Comment by barsch** [comment]
imho ready to merge - dont feel like doing more :)

**Comment by barsch** [comment]
@krischer: I didn't add a test just for the print(st) part - "/path/to/225051000_00008656" is used multiple times in unittest as well as in doctest - so I didn't bother adding an extra test just for this basic functionalty - but if you insist I can add something

**Comment by barsch** [comment]
we could move that print(st[0].stats) also down to the second part of the doctest - than it is covered too

**Comment by krischer** [comment]
Done in 3c8899e052762f1efdb83751448c3269e81c1f0f.

**Pull request merged**
