### PR TITLE
test runner: Include link to submitted test in printed message on report submission

### PR DESCRIPTION
**Pull request by megies**
tests.obspy.org now sends a json response with a link to the submitted test report, so we should include it in the printed message by `obspy-runtests`.

see obspy/reporter#19

### CODE REVIEW

**Comment by megies** [comment]
```bash
$ obspy-runtests io.ah
Running /home/megies/git/obspy-master/obspy/scripts/runtests.py, ObsPy version '1.1.0.post0+3.g49d9d03cd4.dirty.obspy.master'
.....
----------------------------------------------------------------------
Ran 5 tests in 0.188s

OK
Do you want to report this to tests.obspy.org? [n]: y

Test report has been sent to tests.obspy.org: http://tests.obspy.org/90395/ Thank you!
```

**Comment by krischer** [comment]
How about:

`Your tests results have been reported and are available at: http://tests.obspy.org/90395/`

**Comment by megies** [comment]
> Your tests results have been reported and are available at: http://tests.obspy.org/90395/

Can do. I just thought I'd leave the original server url in there just in case we followed a redirect in the process

**Comment by megies** [comment]
```bash
$ obspy-runtests io.ah
Running /home/megies/git/obspy-master/obspy/scripts/runtests.py, ObsPy version '1.1.0.post0+16.g16687a74fa.dirty.obspy.parse.test.report.url'
.....
----------------------------------------------------------------------
Ran 5 tests in 0.260s

OK
Do you want to report this to tests.obspy.org? [n]: y

Your test results have been reported and are available at: http://tests.obspy.org/90407/
Thank you!
```

**Comment by megies** [comment]
```
https://travis-ci.org/obspy/obspy/jobs/301047404#L1813
```

```
Ran 1707 tests in 442.495s

OK

/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:304: DeprecationWarning: unicode for buf is no longer accepted, use bytes

  return self.connection.send(data)

Your test results have been reported and are available at: http://tests.obspy.org/90417/

Thank you!
```

**Comment by krischer** [comment]
Message looks nicer to me know to be honest. I don't think we have to worry about the reconnect. WIthout looking at the code: How about just trying to `.encode()` whatever gets send to the reporter? If its deeper in the code, I guess we can just ignore it for now.

**Comment by megies** [comment]
> WIthout looking at the code: How about just trying to .encode() whatever gets send to the reporter?

hmm.. cant reproduce this warning message locally anymore.. but it's still showing up in CI

**Comment by megies** [comment]
Last commit seems to properly suppress that warning message..
 - Travis py2 build before: https://travis-ci.org/obspy/obspy/jobs/314730789#L1862
 - Travis py2 build now: https://travis-ci.org/obspy/obspy/jobs/347265242#L2041

**Pull request merged**
