### PR TITLE
Fix for "TauBranch depths not compatible with slowness sampling" errors

### PR DESCRIPTION
**Pull request by johnrudge**
### What does this PR do?

In some circumstances taup fails with a "TauBranch depths not compatible with slowness sampling." error. A simple example which triggers this is:

```
from obspy.taup import TauPyModel
model = TauPyModel("ak135")
arrivals = model.get_ray_paths(2000.0, 60.0, ["P"])
```

I believe the bug lies in the `_fix_other_layers` routine in taup/slowness_model.py. That routine splits a layer, but the indexing assumes only ever a single layer gets split. In some circumstances more than one layer needs to be split, but later layers get inserted incorrectly because the size of `out` has grown and the subsequent indexing needs to be adjusted. This pull request fixes the indexing so the above example now works correctly. 

### Why was it initiated?  Any relevant Issues?

A related issue has been reported in #2682. This may also fix that issue, but I don't have the custom model used to test if that is the case. I think this is also the same issue as #1938. 

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [x] All tests still pass.
- [x] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [x] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
Nice catch! :+1: 
This should go into `maintenance_1.3.x`, actually. You could do `git rebase maintenance_1.3.x` on your branch, or if that makes problems simply delete the branch or hard reset it on maintenance and cherry-pick your commit.

Let me know if you need help. If all fails you can also just make a new branch and new PR I guess.

**Comment by johnrudge** [comment]
Sorry about the wrong branch. It's now changed to maintenance_1.3.x

**Comment by megies** [comment]
> Sorry about the wrong branch. It's now changed to maintenance_1.3.x

No worries!

Can you add a changelog one-liner for this please? Also please add the above example as a regression test. Just those three lines and maybe adding `assert int(arrivals[0].time) == 480` or similar should do, I think.

**Review by megies — APPROVED** [review]
- [x] changelog
- [x] simple regression test

Otherwise good to go =)

**Comment by megies** [comment]
You could also add yourself to contributors on this branch if you want, I think you're only in the master branch contributors file =)

**Comment by johnrudge** [comment]
Ok, I think I've done what you've asked @megies !

**Comment by johnrudge** [comment]
Thanks for a speedy merge!

**Pull request merged**
