### PR TITLE
Add support for models without a core or inner core in taup

### PR DESCRIPTION
**Pull request by johnrudge**
### What does this PR do?

This pull request builds on PR #2390, adding support in obspy.taup for models with missing discontinuities, such as no core or no inner core. The pull request contains the code from #2390, along with a port of the changes made to the java code to handle these cases https://github.com/crotwell/TauP/commit/b712c614f9a589b3beb6524096e03230a460a914
PR #2390 failed because of a bug in the `TauBranch.difference` method. The method assumed that if `index_p == -1` then one would also always have `index_s == -1`, but there are cases where that fails (and in particular it fails for their test example). This PR fixes the logic for `TauBranch.difference`.
Credit for this PR should go to @not522, @trichter, and @crotwell. I'm just putting the pieces together.

### Why was it initiated?  Any relevant Issues?

This fixes the issues with Mars models #1200 and #1423, and likely also fixes the issues with the solar model #2086 and the custom model in #2192. 

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [x] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by kaspervanwijk** [comment]
As someone who works with obspy/taup and the original java taup, I think it
may pay to coordinate some of these improvements with the java taup
developer Philip Crotwell. Maybe you already are?

We were running some custom models recently, and there were bugs in the
taup version in obspy (which I think are being fixed by John. Thank you!)
and in the java taup package. They were not the same bugs. It would be a
shame if these bug fixes would not be synthesized across the two software
efforts.

Cheers,
Kasper van Wijk
Department of physics
University of Auckland
https://www.physics.auckland.ac.nz/people/kvan637

**Comment by megies** [comment]
> As someone who works with obspy/taup and the original java taup, I think it may pay to coordinate some of these improvements with the java taup developer Philip Crotwell. Maybe you already are? We were running some custom models recently, and there were bugs in the taup version in obspy (which I think are being fixed by John. Thank you!) and in the java taup package. They were not the same bugs. It would be a shame if these bug fixes would not be synthesized across the two software efforts. Cheers, Kasper van Wijk Department of physics University of Auckland https://www.physics.auckland.ac.nz/people/kvan637

Well.. I tag @crotwell whenever I think something thats going on in here might be of interest for the original Java Taup. Since we just ported the existing Java Taup, you can hardly expect them to spend any extra efforts caused by a ported version. Of course it would be good if somebody would try to keep our port in line with whats happening upstream.. but it would take somebody willing to dedicate themselves to do that. That's something that just can't be handled by our already stretched thin core team, unfortunately.

**Comment by crotwell** [comment]
I am happy to coordinate, I try to follow any obspy issues in a casual sort of way, and will look into what parts of these 2 PR should be merged into my java code. But if you know of of any other bugs or issues with TauP that I should be aware of, please report them, either by tagging me as @megies does or directly to [TauP's issues](https://github.com/crotwell/TauP/issues). I obviously can't fix what I don't know about.

And @megies thanks for keeping me in the loop.

**Comment by kaspervanwijk** [comment]
This is great, all. I think with John's knowledge  and energy in this,
added to philip's, both the python and the java application of taup are
benefitting.

**Comment by dylanmikesell** [comment]
Does anyone have a working example of a homogeneous model? We were able to get close model by making a tiny inner core, but this is not matching our predictions computed by hand. We have a tvel file that contains
```
snow - P
snow - S
0.0000 5.8 3.46 2.7
44.9999 5.8 3.46 2.7
44.9999 5.8 3.461 2.7
45.0000 5.8 3.461 2.7
```
This is the minimum model we could get working with `build_taup_model()` from `obspy.taup.taup_create`. Perhaps there is a better way to do it. We are just trying to build a homogeneous model for now so that we can compute all of the different P and S phases we see in lab data. @kaspervanwijk if you have an example, please share! We could not find anything in the documentation online about this new capability to run models without discontinuities.

**Comment by megies** [comment]
@dylanmikesell I believe this is off topic and not related to this pull request. I don't know taup implementation, but [I would assume it just isn't made for that case](https://discourse.obspy.org/t/issue-with-build-taup-model/1548). Why even go through a complex software for such a calculation? If I understand correctly you just want to calculate the direct-line distance from earthquake to receiver (and then divide it by the scalar velocity to get the travel time?), so in the most general case without any simplifications basically the length of one side of a triangle given you know the two other sides (radius of the sphere minus depth of hypocenter and receiver, respectively) and the angle between them (great circle distance from hypocenter to receiver). With cosine rule you get `c**2 = a**2 + b**2 - 2*a*b*cos(gamma)`.

**Comment by dylanmikesell** [comment]
Okay @megies. Sorry, it seemed on topic to me since it was about models without an inner/outer core. I guess you are still assuming there is a crust in these models.

What I wanted was to build up the complexity of a model, starting from a homogeneous model. You are right that some simple trig will work for the homogeneous case, but we were also planning to add a sleeve/collar around the sample, etc. to build up more complicated models. For consistency, I thought using Taup for all models would be a good idea, plus it does nice plotting quickly and the taup computation is really not heavy. I also wanted more than just P,S, but also PP or PPP for example. We will go the trig route for the homogeneous case I guess. Thanks.

**Comment by kaspervanwijk** [comment]
Dylan, I will send you a solution in (java) taup shortly. I think it is on
topic and interesting. This capability was just not translated properly to
python.

Kasper

**Comment by johnrudge** [comment]
If there's a particular example that works in the java version but not in obspy's python version then that would be good to know. It's likely the appropriate fixes from the java version could be ported to the python version without too much trouble.

**Comment by kaspervanwijk** [comment]
Dear John,

Thanks for all the great upgrades to the obspy taup module, recently. Below
is the taup example that creates some travel times through a homogeneous
sphere in taup, which throws errors if you do the equivalent in the current
version of obspy/taup, as Dylan found out:

taup create -tvel 1_layer_model.tvel

where 1_layer_model.tvel (which ships with obspy/taup and with taup) is

0.0  6.2  3.57 NaN
6371.0  6.2  3.57 NaN

then:

taup time -mod 1_layer_model.taup -h 0.0 -deg 160.0 -ph ttall -o
time_arrivals

ngā mihi nui,
Kasper van Wijk
Department of physics
University of Auckland
https://www.physics.auckland.ac.nz/people/kvan637

**Pull request merged**
