### PR TITLE
fix processing when reading 0.5 byte datawide in WIN format

### PR DESCRIPTION
**Pull request by TazawaK17**
### What does this PR do?

Fixed below three bug.

1. When the data is 0.5 byte datawide and the sampling frequency is even, the code reads surplus 0.5 byte data at the end.
2. The shift operation have to be performed at first, but addition is performed before it.
3. The size of integer data in Python is not being considered. The shift operation has be not functioning.

### Why was it initiated?  Any relevant Issues?

See #3309

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [ ] All tests still pass.
- [x] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] New modules, add the module to `CODEOWNERS` with your github handle
- [ ] Add the yellow `ready for review` label when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by d-chambers** [comment]
Hi @TazawaK17,

Thanks for doing the PR. I should have some time early next week to take a closer look. I don't have any experience with this format or the parser implementation so if there is someone else who does feel free to jump in.

**Comment by d-chambers** [comment]
The test file you attached to #3309 is quite small. It is probably worth including it in the `obspy/io/win/tests/data` directory and writing a short test in `obspy/io/wind/tests/test_core.py` to ensure the problematic output is fixed.

**Comment by TazawaK17** [comment]
Here are the commits. I have made a commit for the test with a length of 6000 without including the "event noise" test. In contributors file, my name and the name of the discoverer have been added.

**Comment by d-chambers** [comment]
Very good work @TazawaK17 ! 

There is one small nitpick from reviewdog [here](https://github.com/obspy/obspy/actions/runs/5263180043/jobs/9527079774?pr=3310). It just wants a new line at the end of `test_core.py`. 

Other than that, the code looks good to me.  I am going to spend some time in the WIN format documentation sometime before the end of the week just to make sure I fully understand the changes, then, assuming I don't spot any other issues, we should be good to merge. 

Not strictly necessary, but I would like to get some feedback from @ThomasLecocq since he is a code owner for this module. 

Thanks again for taking the time to contribute to ObsPy!

**Review by megies — APPROVED** [review]
Thanks and great job on the pull request @TazawaK17 :smiley: 

Looks good to me, even though I can not really comment on the changes in the read logic, but everything around it (tests, changelog, ..) looks good and existing tests still pass.

**Comment by megies** [comment]
One little side note @TazawaK17, since you made these commits for the pull request on the `maintenance_1.4.x` branch of your fork its history will get out of sync with the main repository `maintenance_1.4.x`. That is no problem at all, just should you want to make more pull requests for this branch in the future you would want to reset it to mirror the main repo again first. Nothing to worry about at all, just something to keep in mind.
In general it is a good idea to make a dedicated branch when working on a pull request, that way there is no need to worry about things like that.

**Comment by TazawaK17** [comment]
Thanks for telling me @megies . I'll do that next time.

**Comment by TazawaK17** [comment]
Thanks for the review @d-chambers .
>  It just wants a new line at the end of test_core.py.

It has been corrected.

**Comment by megies** [comment]
We can give it a few days to see if @ThomasLecocq has something to say about this, otherwise we can merge this in a few days of no feedback :smiley:

**Pull request merged**
