### PR TITLE
unify logging configuration

### PR DESCRIPTION
**Pull request by trichter**
This PR tries to unify the logging configuration.
All calls to `logging.basicConfig` inside the library are deleted and some `loglevel` keywords are removed. Logging should be configured in the user's code. A simple `logging.basicConfig()` is often good enough. ~~I added the NullHandler to the obspy's root logger `'obspy'` so that by default no logging is emmited.~~ Logging is only ~~configured~~ displayed for `obspy-runtests -v`.

~~WIP: If this PR is endorsed I would further refine it.~~

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by trichter** [comment]
This PR is ready for review. I also added the possibility to specify a second `-v` flag in `obspy-runtests`. One `-v` will just display warnings. Two `-v` will use the verbose mode of runtests.

Closes #2625.

**Comment by heavelock** [comment]
Changes in  `obspy/signal/tf_misfit.py` seem to be unrelated.

**Comment by trichter** [comment]
> Changes in obspy/signal/tf_misfit.py seem to be unrelated.

Yes, these changes just  deal with a DeprecationWarning of matplotlib. Are only related, because both warnings and logs show when running obspy-runtests.

**Comment by heavelock** [comment]
I just took again a look on this PR and I though about something that new. Why only deprecation since it's targeting master? 
I think you could add deprecations to the 1.2.3 and here just drop it completely.

**Comment by trichter** [comment]
Thanks for having a look. I am all for fast depreciation, but I think most people favor a slower pace with depreciations only for mayor versions. IMHO this is ready for merging.

**Review by ThomasLecocq — APPROVED** [review]

**Comment by ThomasLecocq** [comment]
look OK if all tests 🟢

**Pull request merged**
