### PR TITLE
Show a warning for certain 'requests' versions

### PR DESCRIPTION
**Pull request by megies**
Show a warning for certain 'requests' versions and fix version in travis and appveyor for now.

See #1599.

### CODE REVIEW

**Comment by megies** [comment]
Any idea how to specify `conda install requests<2.12` on Windows?!?

**Comment by krischer** [comment]
Nope.

@barsch, @ThomasLecocq ?

**Comment by ThomasLecocq** [comment]
`conda install "requests<2.12"` should work

**Comment by megies** [comment]
Problem.. Ubuntu xenial and yakkety have a requests version that we can't work with..
 - http://tests.obspy.org/61797/
 - http://tests.obspy.org/61804/

Not sure how to get around the problem other than packaging a newer requests for those two.. :-/

**Pull request merged**
