### PR TITLE
enabled arclink decryption during download

### PR DESCRIPTION
**Pull request by barsch**
lesser memory footprint while having the same execution speed as before

### CODE REVIEW

**Comment by barsch** [comment]
coverage/coveralls lies - it includes files which were not changed in this PR - however I really love the idea of this feature if it would work ...

**Comment by krischer** [comment]
Yea coverage is funny sometimes...no clue why lists untouched files.

The PR itself looks fine to me. I assume you locally tested on py2 and py3?

**Comment by barsch** [comment]
tests were fine for windows - still would be nice if some would test it manually on linux

**Comment by krischer** [comment]
I get lots of timeouts when running `test_decrypt.py` but can run the normal arclinks tests just fine. Is this expected? Is encrypted data send over a different port?

**Comment by barsch** [comment]
hmm not good - I'll check at home if this is still running for me and report back - thanks for testing

**Comment by barsch** [comment]
oh and port 36000 needs to be open - see https://github.com/obspy/obspy/blob/master/obspy/clients/arclink/tests/test_decrypt.py#L35

**Comment by krischer** [comment]
I see. I'll test at home.

**Comment by krischer** [comment]
FYI: I just pushed a commit to this branch that allows to run the crypto tests with either supported crypto library.

**Comment by barsch** [comment]
EVPError is only defined for M2Crypto ! -> unfortunatly as far I tested pycrypto does not raise anything if there is an error during decrypting - so we have to stick with M2Crypto as default and only take pyCrypto as fallback

**Comment by krischer** [comment]
Hmm...there must be a way to figure out if the decrypt was successful, right? How does `m2crypto` even know? I mean we could always check the resulting miniseed file but m2crypto clearly does something else.

**Comment by barsch** [comment]
while using pycrypto it just fails later - either because it can't unpack using bzip2 or it can't read as its not a valid mseed

AFAIK m2crypto checks in the final call https://github.com/obspy/obspy/blob/master/obspy/clients/arclink/decrypt.py#L66 - so we could look into that

**Comment by megies** [comment]
+TESTS:clients.arclink

Travis should run ArcLink test suites for future commits/pushes to this branch now (see [here](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-a-pull-request)). Please ping me if it doesn't work..

**Comment by megies** [comment]
What's the status here, @barsch @krischer?

**Comment by barsch** [comment]
the later commit from @krischer does imho not work - see comment above - so either we stick with my orginal implementation, leave it as it is or find something better

**Comment by megies** [comment]
> and triggering a new test run did not work, or?

I rebased and force-pushed right now, that will trigger CI..

**Comment by megies** [comment]
Current Travis commit status includes Arclink tests: https://travis-ci.org/obspy/obspy/builds/176344138

Not sure if tests cover decryption, though?

**Comment by megies** [comment]
I'll bump this to 1.2.0. Feel free to add to 1.1.0 if it gets ready in the next couple of weeks.

**Comment by barsch** [comment]
imho ready to merge

**Comment by barsch** [comment]
failing test is not related - merging

**Comment by megies** [comment]
@barsch this PR should also have modified arclink extra/optional dependencies.. anybody know how to modify a set of OR dependencies in setup.py? I couldn't find it..

https://github.com/obspy/obspy/blob/master/setup.py#L116

Should be semantically be something like..
```
 'arclink': ['m2crypto | pycrypto | cryptography'],
```

**Comment by barsch** [comment]
I don't think there is such option - I would take it out completely and just document it

btw: pycryptodome does also work - its an drop-in replacement for pycrypto

**Pull request merged**
