### PR TITLE
try to fix loading cdll on windows

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Seems on Windows we suddenly have issues with '../' in the path?

see e.g. https://ci.appveyor.com/project/obspy/obspy/builds/30964871/job/rkt1cfbwk09uuejh#L3481
```
[00:06:52]   File "obspy\clients\filesystem\miniseed.py", line 20, in <module>
[00:06:52]     from obspy.clients.filesystem.msriterator import _MSRIterator
[00:06:52]   File "obspy\clients\filesystem\msriterator.py", line 14, in <module>
[00:06:52]     from obspy.io.mseed.headers import (HPTMODULUS, MS_NOERROR, MS_ENDOFFILE,
[00:06:52]   File "obspy\io\mseed\headers.py", line 22, in <module>
[00:06:52]     __clibmseed = _load_cdll("mseed")
[00:06:52]   File "obspy\core\util\libnames.py", line 98, in _load_cdll
[00:06:52]     raise ImportError(msg)
[00:06:52] 
[00:06:52] ImportError: Could not load shared library "libmseed_Windows_64bit_py27.pyd" ("obspy\core\util\..\..\lib\libmseed_Windows_64bit_py27.pyd").
[00:06:52] 
[00:06:52]  [Error 126] The specified module could not be found
[00:06:52] 
[00:06:52] >>> Cannot import test suite for module obspy.core due to:
```

Not sure why this never was a problem before.. maybe it's some other issue, we'll see after CI..

### Why was it initiated?  Any relevant Issues?

*Please fill in*

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
Checking this afternoon

**Comment by megies** [comment]
OK, looks like the `abspath` call fixed it, something weird goin on with relative path/working directory for ctypes, seems like.

But now gdal somehow cant be installed like it used to, can you check later @ThomasLecocq? 
https://ci.appveyor.com/project/obspy/obspy/builds/31041482/job/rrcniixnmkyxx3qi#L122

It used to install fine just some days ago, e.g. https://ci.appveyor.com/project/obspy/obspy/builds/30821955/job/kfs9esn38jvfx6n0#L163

**Comment by ThomasLecocq** [comment]
seems odd, like routing/package solving issues. I have also issues with Appveyor for MSNoise today....

**Comment by ThomasLecocq** [comment]
(and seriously, win32bits? ...)

**Comment by ThomasLecocq** [comment]
you could try setting the env variables before creating the env

```
set CONDA_FORCE_32BIT=1
conda create -n py27_32 python=2.7
```

works fine on my machine (otherwise I don't see how/when the 32bits is actually used in the build ?)

**Comment by ThomasLecocq** [comment]
a problem is the call to conda install being inside a if/else statement, which seemingly prevents the output (or maybe there is no output and it fails). 

Creating the same env with the same 32bits python works on my machine (win64 with the command above)

**Comment by megies** [comment]
I have no problem deactivating 32bit builds if you say we don't need them. I guess it *is* a bit ridiculous in 2020.

**Comment by ThomasLecocq** [comment]
dah, appveyor still not happy, I'm on it

**Comment by ThomasLecocq** [comment]
could you try putting conda-forge *before* calling ``conda update conda`` ?

**Comment by ThomasLecocq** [comment]
trying now. It would be good to be able to get the output of this command:

https://ci.appveyor.com/project/obspy/obspy/builds/31064132/job/3avdee8yqhc5kto2#L145

I *think* I can change the yml to define the ``%basemap%`` variable based on the condition, then execute a simple ``conda install ... %basemap%`` in the normal cmd. @megies this should work according to you?

**Comment by megies** [comment]
> I _think_ I can change the yml to define the `%basemap%` variable based on the condition, then execute a simple `conda install ... %basemap%` in the normal cmd. @megies this should work according to you?

Looks good to me :+1:

**Comment by ThomasLecocq** [comment]
CI is green for windows :-) will do the rest in #2569 when rebased :-)

**Pull request merged**
