### PR TITLE
filter warnings in spectral estimation test

### PR DESCRIPTION
**Pull request by trichter**
Fix for #2977.

Let's see if it is working.

### CODE REVIEW

**Comment by trichter** [comment]
I have got the impression that mpl plots are already closed when each test function finishes.
Some functions create more than 20 figures e.g. test_beachball.

**Comment by ThomasLecocq** [comment]
aaah, that could be! or the plot_spectral that creates all possible cmaps ?

**Comment by trichter** [comment]
```
Traceback (most recent call last):
File "[/home/runner/work/obspy/obspy/obspy/signal/tests/test_spectral_estimation.py](https://github.com/obspy/obspy/blob/0e075ccc3c/obspy/signal/tests/test_spectral_estimation.py#L704)", line 704, in test_issue1216
assert str(w_.message).startswith(
AssertionError: assert False
+ where False = <built-in method startswith of str object at 0x7fd5a7afc530>('Already covered time spans detected')
+ where <built-in method startswith of str object at 0x7fd5a7afc530> = 'Please use `zpk2tf` from the `scipy.signal` namespace, the `scipy.signal.ltisys` namespace is deprecated.'.startswith
+ where 'Please use `zpk2tf` from the `scipy.signal` namespace, the `scipy.signal.ltisys` namespace is deprecated.' = str(DeprecationWarning('Please use `zpk2tf` from the `scipy.signal` namespace, the `scipy.signal.ltisys` namespace is deprecated.'))
+ where DeprecationWarning('Please use `zpk2tf` from the `scipy.signal` namespace, the `scipy.signal.ltisys` namespace is deprecated.') = <warnings.WarningMessage object at 0x7fd5a72184c0>.message
```

**Comment by trichter** [comment]
If tests pass this is ready.

**Comment by trichter** [comment]
Can we merge this one (and #2978), so that we have a clean master.

**Review by d-chambers — APPROVED** [review]

**Pull request merged**
