### PR TITLE
docs: fix some residual links to old mailing lists on docs frontpage

### LINKED ISSUE #2735: docs: Replace mentions of obspy-users mailing list
I have tried to register - never received a response.
I tried to email to the list, got this "permanent error":

`A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:
  obspy-users@lists.swapbytes.de
    (generated from users@obspy.org)
    retry timeout exceeded
`
So I'll try https://gitter.im/obspy/obspy.

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

fixes #2735

### Why was it initiated?  Any relevant Issues?

*Please fill in*

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Review by trichter — APPROVED** [review]

**Comment by megies** [comment]
Looking good: https://docs.obspy.org/pr/docs_update_ml_forum_links/

**Comment by megies** [comment]
ideally we should monkey patch those 2-3 lines in the 1.3.0 live docs

**Comment by trichter** [comment]
Yeah, I can do this. We can also merge maintenance already into master. Then its also in the dev docs.

**Comment by trichter** [comment]
> Yeah, I can do this. 

Done

**Comment by megies** [comment]
> Yeah, I can do this. We can also merge maintenance already into master. Then its also in the dev docs.

Yup, already done that =)

**Pull request merged**
