### PR TITLE
seedlink basic client, get_info(): terminate properly

### LINKED ISSUE #2995: Seedlink client tests take very long, related error 'response: no data stream selector(s) accepted' logged
I think there might be some error in the seedlink class. The seedlink tests take very long and some error are logged:

```
(workhorse) eule@kiste:~/dev/obspy$ obspy-runtests --network clients/seedlink --durations=10 -rA -s
======= test session starts ========
platform linux -- Python 3.8.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/eule/dev/obspy/obspy, configfile: pytest.ini
plugins: sphinx-0.3.1, html-3.1.1, cov-2.10.1, metadata-1.11.0, json-report-1.4.1
collected 13 items                                                                                                                                                                                                                           

clients/seedlink/basic_client.py ..
clients/seedlink/easyseedlink.py .
clients/seedlink/tests/test_basic_client.py ...
clients/seedlink/tests/test_seedlinkconnection.py .
clients/seedlink/tests/test_slclient.py sss
clients/seedlink/tests/test_slnetstation.py .
clients/seedlink/tests/test_slpacket.py .
clients/seedlink/tests/test_slstate.py .

============== PASSES ==============
_______________________________________________________________________________________ [doctest] obspy.clients.seedlink.basic_client.Client.get_info ________________________________________________________________________________________
------------------------------------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------------------------------------
ERROR     obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:850 negotiation with remote SeedLink failed: 'response: no data stream selector(s) accepted'
WARNING   obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:702 terminating collect loop
ERROR     obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:850 negotiation with remote SeedLink failed: 'response: no data stream selector(s) accepted'
WARNING   obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:702 terminating collect loop
_____________________________________________________________________________________ [doctest] obspy.clients.seedlink.basic_client.Client.get_waveforms _____________________________________________________________________________________
------------------------------------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------------------------------------
ERROR     obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:850 negotiation with remote SeedLink failed: 'response: no data stream selector(s) accepted'
WARNING   obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:702 terminating collect loop
ERROR     obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:850 negotiation with remote SeedLink failed: 'response: no data stream selector(s) accepted'
WARNING   obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:702 terminating collect loop
________________________________________________________________________________________________________ ClientTestCase.test_get_info ________________________________________________________________________________________________________
------------------------------------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------------------------------------
ERROR     obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:850 negotiation with remote SeedLink failed: 'response: no data stream selector(s) accepted'
WARNING   obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:702 terminating collect loop
______________________________________________________________________________________________________ ClientTestCase.test_get_waveform ______________________________________________________________________________________________________
------------------------------------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------------------------------------
ERROR     obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:850 negotiation with remote SeedLink failed: 'response: no data stream selector(s) accepted'
WARNING   obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:702 terminating collect loop
_________________________________________________________________________________ ClientTestCase.test_multiple_waveform_requests_with_multiple_info_requests _________________________________________________________________________________
------------------------------------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------------------------------------
ERROR     obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:850 negotiation with remote SeedLink failed: 'response: no data stream selector(s) accepted'
WARNING   obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:702 terminating collect loop
ERROR     obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:850 negotiation with remote SeedLink failed: 'response: no data stream selector(s) accepted'
WARNING   obspy.clients.seedlink [rtserver.ipgp.fr:18000]:seedlinkconnection.py:702 terminating collect loop
======= slowest 10 durations =======
41.17s call     clients/seedlink/basic_client.py::obspy.clients.seedlink.basic_client.Client.get_waveforms
40.44s call     clients/seedlink/basic_client.py::obspy.clients.seedlink.basic_client.Client.get_info
8.91s call     clients/seedlink/tests/test_basic_client.py::ClientTestCase::test_multiple_waveform_requests_with_multiple_info_requests
4.37s call     clients/seedlink/tests/test_basic_client.py::ClientTestCase::test_get_waveform
4.14s call     clients/seedlink/tests/test_basic_client.py::ClientTestCase::test_get_info

(5 durations < 0.005s hidden.  Use -vv to show these durations.)
===== short test summary info 
SKIPPED [1] clients/seedlink/tests/test_slclient.py:18: test must be started manually
SKIPPED [1] clients/seedlink/tests/test_slclient.py:40: test must be started manually
SKIPPED [1] clients/seedlink/tests/test_slclient.py:27: test must be started manually
================================================================================================== 10 passed, 3 skipped in 99.39s (0:01:39) ==================================================================================================

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Seems seedlink basic client in `get_info()` did not properly signal that everything was received
and ready to terminate. not sure why it worked before..

### Why was it initiated?  Any relevant Issues?

tries to fix #2995 

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
Looks like `return False` in packet handler keeps the low-level client expecting more packets with data in them (here, metadata on available stations as xml plain text). So when a terminated/terminating (`TYPE_SLINFT: Packet type is terminated info packet.`) packet is received we should `return True` and then the low-level continuous packet reception loop is hitting a `break` statement and stopping.

Not sure how this worked before..

**Comment by megies** [comment]
@trichter ah, i should've probably added that network test label when opening the PR? :grimacing:

**Comment by trichter** [comment]
> @trichter ah, i should've probably added that network test label when opening the PR?

Just push another empty commit to trigger the tests.

**Comment by trichter** [comment]
That was a quick fix! Nice. It also reduces the spent time for network tests significantly :+1:

**Review by trichter — APPROVED** [review]

**Comment by trichter** [comment]
Do you want to include a changelog or just merge?

**Comment by megies** [comment]
Added changelog :+1:

**Pull request merged**
