### PR TITLE
test_code_formatting fails with ```from cryptography.hazmat.backends import default_backend``` 

### PR DESCRIPTION
**Pull request by megies**
see http://tests.obspy.org/70204/#1

```
Traceback (most recent call last):
File "/obspy/obspy/core/tests/test_code_formatting.py", line 205, in test_no_pyplot_import_in_any_file
self.assertEqual(len(failures), 0, "\n" + "\n\n".join(failures))
AssertionError:
File '/obspy/obspy/clients/arclink/decrypt.py' (line 31)
matches a forbidden matplotlib import statement outside of class/def statements
(breaking matplotlib backend switching on some systems):
' from cryptography.hazmat.backends import default_backend'
File '/obspy/obspy/clients/arclink/decrypt.py' (line 31)
matches a forbidden matplotlib import statement outside of class/def statements
(breaking matplotlib backend switching on some systems):
' from cryptography.hazmat.backends import default_backend'
```

This error is essentially blocking PR https://github.com/obspy/obspy/pull/1360

### CODE REVIEW

**Comment by megies** [comment]
This is now a PR that should fix the regex (and I've added a test to make sure the regex is matching the expected strings).

**Comment by megies** [comment]
No idea what flake8 is complaining about, since #1647 removed any failure messages from our flake8 test case.

**Comment by krischer** [comment]
screen shot 2017-02-21 at 09 54 02

;-)

**Comment by megies** [comment]
Those two pep8 fails are false positives from an issue in pep8 that was first reported over four years ago:

```python
179         positives = (
180             'from pylab import something',
181             '    from pylab import something',
182             'from pylab.something import something',
183             'import pylab',
184             '    import pylab',
185             'from matplotlib import pyplot',
186             '  from matplotlib import pyplot',
187             'from matplotlib import backends',
188             '  from matplotlib import backends',
189             'from matplotlib import dates, backends',
190             'import matplotlib.pyplot as plt',
191             'import matplotlib.pyplot',
192             'import matplotlib.backends',
193             '   import matplotlib.backends',
194             )
```

The indentation of the closing bracket is totally valid. [see pep8, 'indentation' at end of paragraph](https://www.python.org/dev/peps/pep-0008/#indentation)

I'm confused because I don't see any pep8 version installed in the test runner.. (supposedly it's fixed in pep8 1.4.6 in 2014)

**Comment by megies** [comment]
Rebased on current master and force-pushed.

**Comment by megies** [comment]
I think this is good to go..

 - flake8 check has two false positives, but this has to be fixed upstream or by using a different flake8/pep8 version
 - some docker testbots could not run due to #1671 

Merging now, to not delay @barsch's #1360 any longer.

**Pull request merged**
