### PR TITLE
sds client: add option to get all NSLC combinations on given point in time

### PR DESCRIPTION
**Pull request by megies**
Might still need a test..

### CODE REVIEW

**Comment by QuLogic** [comment]
Interesting; codecov is :arrow_up:, coveralls is :arrow_down:.

**Comment by megies** [comment]
> Interesting; codecov is :arrow_up:, coveralls is :arrow_down:.

I also can't really follow codecov how this PR supposedly reduces the number of files in the repo by 2??

> @@            master   #1362   diff @@ ======================================



> Files 369 367 -2

codecov seems to have a miraculous way to compute overall coverage from the individual Travis reports.. (also: number of files covered is 367 for 6/7 Travis jobs and 369 for 1/7 jobs)

codecov

**Comment by megies** [comment]
Added test, force pushed.

**Comment by QuLogic** [comment]
> (also: number of files covered is 367 for 6/7 Travis jobs and 369 for 1/7 jobs)

For some reason, `obspy/db/scripts/__init__.py` and `obspy/db/scripts/indexer.py` are included in 4535.3, but not the others. However, neither of them get any hits, so I it's a bug in counting untouched files, but I don't know if it's coverage or codecov.

**Pull request merged**
