### PR TITLE
fdsn: update raspi shake URL

### LINKED ISSUE #3263: RaspberryShake AM Network URL change
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Good morning, 

I am writing on behalf of RaspberryShake to report that the URL pointing to the FDSN RS AM Network has changed from the old one:

https://fdsnws.raspberryshakedata.com

to the new: 

https://data.raspberryshake.org

Would it be possible to update it where relevant? I have found three files in ObsPy where the old URL appears: 

```
line 128 - https://github.com/obspy/obspy/blob/ec7b76b888bacc12691ec19c29fe69a6ef974fbe/obspy/clients/fdsn/header.py
line 60 - https://github.com/obspy/obspy/blob/5a08e1d6c37a00cbea863a1ab039328768fbe98d/obspy/clients/fdsn/__init__.py
lines 82-85 - https://github.com/obspy/obspy/blob/13b6ca5db757c34a8cadeb00370a65b5932e47a8/obspy/clients/fdsn/tests/test_federator_routing_client.py
```

If anything else is required, I remain available.

### Code to Reproduce

_No response_

### Error Traceback

_No response_

### ObsPy Version?

1.4.0

### Operating System?

_No response_

### Python Version?

_No response_

### Installation Method?

conda

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Updates the URL for raspberryshake FDSN WS

### Why was it initiated?  Any relevant Issues?

fixes #3263 

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] New modules, add the module to `CODEOWNERS` with your github handle
- [ ] Add the `ready for review` tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by trichter** [comment]
Oh, we need to update all our `*env.yml` files in the `.github` folder to reflect the sqlalchemy version requirements. Maybe you could add the change directly in this branch.

**Review by trichter — APPROVED** [review]

**Comment by trichter** [comment]
Hm, wait a moment. In the network warnings test we have a seg fault and other network tests are still running.

```

clients/earthworm/__init__.py .                                          [  0%]
clients/earthworm/client.py ...                                          [  2%]
Fatal Python error: Segmentation fault
```

**Comment by trichter** [comment]
```
Hm, wait a moment. In the network warnings test we have a seg fault and other network tests are still running.
```

But on the other hand, it is not related to this PR.

**Comment by megies** [comment]
Re-ran failed tests, segfault at least is gone. The rest is unrelated fails.

**Pull request merged**
