### PR TITLE
Support for reading Seisan version 6 files

### LINKED ISSUE #1864: SeisAn format <= 6 not properly detected, test data attached
Even thought some code exists to detect SeisAn format 6 it is not properly detected under Python 3.6 (and likely others).  Detection via the internal _get_version() is fixed by adding the bytes literal declaration to the 'P' constant, i.e. `b'P'`, so 
https://github.com/obspy/obspy/blob/master/obspy/io/seisan/core.py#L102 should be:
```
if data[0:2] == b'KP' and data[82:83] == b'P':
```

But then it seams that this version of the format is not supported for reading.  I do not have time at the moment to investigate what it would take to add this support so I attach an example test file for someone else or a future me to use as a reference.

[2005-07-23-1452-04S.CER___030.gz](https://github.com/obspy/obspy/files/1258722/2005-07-23-1452-04S.CER___030.gz)

### LINKED ISSUE #1875: Seisan format file reading error
Hi,
I'm trying to read a seisan format file but I get this error. 

Running code:
```python
from obspy import read
s=read('D1360930.203', format='seisan')
````

Result:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-31>", line 2, in read
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/util/decorator.py", line 301, in _map_example_filename
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/stream.py", line 235, in read
    st.extend(_read(file, format, headonly, **kwargs).traces)
  File "<decorator-gen-32>", line 2, in _read
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/util/decorator.py", line 211, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/stream.py", line 277, in _read
    headonly=headonly, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/util/base.py", line 433, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/io/seisan/core.py", line 175, in _read_seisan
    temp = _readline(fh, 1040).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfb in position 0: ordinal not in range(128)
```

The file is attached in zip format here:
[D1360930.203.zip](https://github.com/obspy/obspy/files/1274607/D1360930.203.zip)

### PR DESCRIPTION
**Pull request by barsch**
should fix #1864 and fix #1875 - still WIP!

### CODE REVIEW

**Comment by barsch** [comment]
@megies: go ahead

**Comment by nikosT** [comment]
Hi,
I tried the latest master code but still I can't read the version 6 seisan file.

**Comment by barsch** [comment]
@nikosT strange - I even used the seisan file you provided in the tests ... what is the error message you got?

**Comment by nikosT** [comment]
```Python
>>> s=read('D1360000.206', format='seisan')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-31>", line 2, in read
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/util/decorator.py", line 301, in _map_example_filename
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/stream.py", line 235, in read
    st.extend(_read(file, format, headonly, **kwargs).traces)
  File "<decorator-gen-32>", line 2, in _read
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/util/decorator.py", line 211, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/stream.py", line 277, in _read
    headonly=headonly, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/util/base.py", line 433, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/io/seisan/core.py", line 175, in _read_seisan
    temp = _readline(fh, 1040).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfb in position 0: ordinal not in range(128)
```

**Comment by barsch** [comment]
in current master line 175 in ```obspy/io/seisan/core.py``` is not ```_readline(fh, 1049).decode()```, see

https://github.com/obspy/obspy/blob/master/obspy/io/seisan/core.py#L175

are you sure you are on master?

**Comment by nikosT** [comment]
I apologize you were right. It wasn't the master release. Pip needs `-I` to force reinstall since master version always is numbered as `'0.0.0+archive'`. I also test it and it works! Thanks :)

**Pull request merged**
