### PR TITLE
Fix build_taup_model for model with no discontinuity

### LINKED ISSUE #2086: taup problem with solar model
Hi, 

I am trying to use Obspy.taup to create some travel-time curves for a model of the Sun (though one that is currently a Poisson Solid) however I am getting an error when I try and use taup_create.build_taup_model.

I have checked this procedure with an iasp91 example, and that works fine, but with the custom model I am using a series of errors are thrown. The two models are identical in content, apart from the values of course being different. A .txt version of the .tvel file that I'm using is attached. 

Thanks, 

Ben 

-Obspy 1.1.0 on OsX downloaded using Anaconda

Using: from obspy.taup import taup_create 
taup_create.build_taup_model(‘solar_constant_density_backup.tvel’)

Building obspy.taup model for 'solar_constant_density_backup.tvel' ...
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-8d44c3e3d9da> in <module>()
----> 1 tc.build_taup_model('solar_constant_density_backup.tvel')

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/taup_create.py in build_taup_model(filename, output_folder, verbose)
    179                             output_filename=output_filename)
    180     mod_create.load_velocity_model()
--> 181     mod_create.run()
    182 
    183 

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/taup_create.py in run(self)
    119         """
    120         try:
--> 121             self.tau_model = self.create_tau_model(self.v_mod)
    122             # this reassigns model! Used to be TauModel() class,
    123             # now it's an instance of it.

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/taup_create.py in create_tau_model(self, v_mod)
     84             self.max_range_interval * pi / 180.0, self.max_interp_error,
     85             self.allow_inner_core_s,
---> 86             _DEFAULT_VALUES["slowness_tolerance"])
     87         if self.debug:
     88             print("Parameters are:")

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/slowness_model.py in __init__(self, v_mod, min_delta_p, max_delta_p, max_depth_interval, max_range_interval, max_interp_error, allow_inner_core_s, slowness_tolerance, skip_model_creation)
     74         if skip_model_creation:
     75             return
---> 76         self.create_sample()
     77 
     78     def __str__(self):

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/slowness_model.py in create_sample(self)
    154         if self.debug:
    155             print("coarse_sample")
--> 156         self.coarse_sample()
    157         if self.debug:
    158             self.validate()

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/slowness_model.py in coarse_sample(self)
    821             is_p_wave=self.p_wave,
    822             radius_of_planet=self.v_mod.radius_of_planet,
--> 823             is_spherical=self.v_mod.is_spherical)
    824 
    825         self.p_layers = np.insert(self.p_layers, index, curr_p_layer)

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/slowness_layer.py in create_from_vlayer(v_layer, is_p_wave, radius_of_planet, is_spherical)
    323 
    324         if bot_depth.shape:
--> 325             if bot_depth[-1] == radius_of_planet and bot_vel[-1] == 0.0:
    326                 bot_depth[-1] = 1.0
    327         ret['bot_p'] = (radius_of_planet - bot_depth) / bot_vel

IndexError: index -1 is out of bounds for axis 0 with size 0

[solar_constant_density_backup copy.txt](https://github.com/obspy/obspy/files/1784509/solar_constant_density_backup.copy.txt)

### LINKED ISSUE #2192: Custom models built from .tvel
I'm trying to create a custom model for the moon. In my .tvel file, the format is shown below:

NAME         nonlayered_1D
UNITS        m
depth vp vs rho
0	2637	1522	2217
1	3037	1753	2297
2	3382	1953	2360
3	3695	2133	2412
4	3987	2302	2459
5	4209	2430	2492
6	4422	2553	2523
7	4561	2633	2543
.
.
.
1125	7308	4219	2861
1126	7308	4219	2861
1127	7308	4219	2861
1128	7308	4219	2861
1129	7309	4220	2861
1130	7308	4220	2861
1131	7308	4219	2861
1132	7308	4219	2861
1133	7308	4219	2861

when I ran, this command 'obspy.taup.taup_create.build_taup_model('/import/deadlock-data/pjangthongsiri/Works/nonlayered_1D.tvel', output_folder='import/deadlock-data/pjangthongsiri/Works', verbose=True)', I got this error: IndexError: index -1 is out of bounds for axis 0 with size 0.

I tried to change the columns from vp vs rho to vs vp rho, I got an error that 'S velocity is greater than P velocity'. I don't know what I did wrong. Please help.

Sincerely,
Glory

### PR DESCRIPTION
**Pull request by not522**
### What does this PR do?

This PR fixes `build_taup_model` for the no discontinuity model. If the structure model has no first order discontinuity, `v_layer` in `create_from_vlayer` can be 1-D empty array.

### Why was it initiated?  Any relevant Issues?

This PR fixes #2086 and fixes #2192.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [x] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by krischer** [comment]
Thanks for this! Can you please rebase on top of the latest `master` and also change the target branch to `master`? ObsPy `1.1.x` is done. Please let me know if you need help with that!

**Comment by megies** [comment]
> Thanks for this! Can you please rebase on top of the latest `master` and also change the target branch to `master`? ObsPy `1.1.x` is done. Please let me know if you need help with that!

Ping @not522 

Also, you need to also add the expected phase arrivals in the test, currently this is not being tested because `zip` stops when one of the lists is exhausted.

**Comment by not522** [comment]
Sorry for the late reply. I'm trying to test the phase arrivals for the new case, but it fails due to other bugs. I'm working to fix them. It will take time.

**Comment by trichter** [comment]
Here is the failure mentioned by @not522.

It can be triggered with the branch obspy/fix_build_taup_model2 which is basically the commit from this branch rebased on current master.

Unfortunately, I am not really into the taup(y) stuff. 

```
(workhorse) eule@kiste:~/dev/obspy$ pytest -s -v -k test_regional_models obspy/taup/tests/test_tau.py
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.6.7, pytest-4.4.0, py-1.8.0, pluggy-0.9.0 -- /home/eule/anaconda/envs/workhorse/bin/python
cachedir: .pytest_cache
rootdir: /home/eule/dev/obspy, inifile: pytest.ini
plugins: remotedata-0.3.1, openfiles-0.3.1, doctestplus-0.3.0, arraydiff-0.3
collected 35 items / 34 deselected / 1 selected                                                                                                                                                                                              

obspy/taup/tests/test_tau.py::TauPyModelTestCase::test_regional_models FAILED

================================================================================================================== FAILURES ==================================================================================================================
__________________________________________________________________________________________________ TauPyModelTestCase.test_regional_models ___________________________________________________________________________________________________

self = <obspy.taup.tau_model.TauModel object at 0x7f3fa30672b0>, depth = 18.0

    def load_from_depth_cache(self, depth):
        # Very simple and straightforward LRU cache implementation.
        if self._depth_cache is not None:
            # Retrieve and later insert again to get LRU cache behaviour.
            try:
>               value = self._depth_cache.pop(depth)
E               KeyError: 18.0

obspy/taup/tau_model.py:228: KeyError

During handling of the above exception, another exception occurred:

self = <obspy.taup.tests.test_tau.TauPyModelTestCase testMethod=test_regional_models>

    def test_regional_models(self):
        """
        Tests small regional models as this used to not work.
    
        Note: It looks like too much work to get a 1-layer model working.
        The problem is first in finding the moho, and second in coarsely-
        sampling slowness. Also, why bother.
        """
        model_names = ["2_layer_model", "5_layer_model",
                       "2_layer_no_discontinuity_model"]
        expected_results = [
            [("p", 18.143), ("Pn", 19.202), ("PcP", 19.884), ("sP", 22.054),
             ("ScP", 23.029), ("PcS", 26.410), ("s", 31.509), ("Sn", 33.395),
             ("ScS", 34.533)],
            [("Pn", 17.358), ("P", 17.666), ("p", 17.804), ("P", 17.869),
             ("PcP", 18.039), ("ScP", 19.988), ("sP", 22.640), ("sP", 22.716),
             ("sP", 22.992), ("PcS", 23.051), ("sP", 24.039), ("sP", 24.042),
             ("Sn", 30.029), ("S", 30.563), ("s", 30.801), ("S", 30.913),
             ("ScS", 31.208)],
             None]
    
        for model_name, expects in zip(model_names, expected_results):
            with TemporaryWorkingDirectory():
                folder = os.path.abspath(os.curdir)
                build_taup_model(
                    filename=os.path.join(DATA, os.path.pardir,
                                          model_name + ".tvel"),
                    output_folder=folder, verbose=False)
                model = TauPyModel(os.path.join(folder, model_name + ".npz"))
    
            arrivals = model.get_ray_paths(source_depth_in_km=18.0,
>                                          distance_in_degree=1.0)

obspy/taup/tests/test_tau.py:1037: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
obspy/taup/tau.py:693: in get_ray_paths
    rp.run()
obspy/taup/taup_time.py:38: in run
    self.depth_correct(self.source_depth, self.receiver_depth)
obspy/taup/taup_pierce.py:63: in depth_correct
    TauPTime.depth_correct(self, depth, receiver_depth)
obspy/taup/taup_time.py:50: in depth_correct
    self.depth_corrected_model = self.model.depth_correct(depth)
obspy/taup/tau_model.py:221: in depth_correct
    return self.load_from_depth_cache(depth)
obspy/taup/tau_model.py:230: in load_from_depth_cache
    value = self._load_from_depth_cache(depth)
obspy/taup/tau_model.py:241: in _load_from_depth_cache
    depth_corrected = self.split_branch(depth)
obspy/taup/tau_model.py:323: in split_branch
    out_ray_params)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <obspy.taup.tau_branch.TauBranch object at 0x7f3fa30674e0>, top_branch = <obspy.taup.tau_branch.TauBranch object at 0x7f3fa31edf98>, index_p = -1, index_s = 6
s_mod = <obspy.taup.slowness_model.SlownessModel object at 0x7f3fa3028470>, min_p_so_far = 1024.6774193548385
ray_params = array([ 1784.59383754,  1784.29826795,  1784.00269837,  1783.41155921,
        1782.22928089,  1779.86472425,  1779.55...3866496,    24.11037108,
          18.05992487,    15.03470177,    12.00947867,     6.00473934,
           0.        ])

    def difference(self, top_branch, index_p, index_s, s_mod, min_p_so_far,
                   ray_params):
        """
        Generates a new tau branch by "subtracting" the given tau branch from
        this tau branch (self). The given tau branch is assumed to by the
        upper part of this branch. index_p specifies where a new ray
        corresponding to a P wave sample has been added; it is -1 if no ray
        parameter has been added to top_branch. index_s  is similar to index_p
        except for a S wave sample. Note that although the ray parameters
        for index_p and index_s were for the P and S waves that turned at the
        source depth, both ray parameters need to be added to both P and S
        branches.
        """
        if top_branch.top_depth != self.top_depth \
                or top_branch.bot_depth > self.bot_depth:
            if top_branch.top_depth != self.top_depth \
                    and abs(top_branch.top_depth - self.top_depth) < 0.000001:
                # Really close, just move top.
                self.top_depth = top_branch.top_depth
            else:
                raise TauModelError(
                    "TauBranch not compatible with slowness sampling.")
        if top_branch.is_p_wave != self.is_p_wave:
            raise TauModelError(
                "Can't subtract branches is is_p_wave doesn't agree.")
        # Find the top and bottom slowness layers of the bottom half.
        top_layer_num = s_mod.layer_number_below(top_branch.bot_depth,
                                                 self.is_p_wave)
        bot_layer_num = s_mod.layer_number_below(self.bot_depth,
                                                 self.is_p_wave)
        top_s_layer = s_mod.get_slowness_layer(top_layer_num, self.is_p_wave)
        bot_s_layer = s_mod.get_slowness_layer(bot_layer_num, self.is_p_wave)
        if bot_s_layer['top_depth'] == self.bot_depth \
                and bot_s_layer['bot_depth'] > self.bot_depth:
            # Gone one too far.
            bot_layer_num -= 1
            bot_s_layer = s_mod.get_slowness_layer(bot_layer_num,
                                                   self.is_p_wave)
        if top_s_layer['top_depth'] != top_branch.bot_depth \
                or bot_s_layer['bot_depth'] != self.bot_depth:
            raise TauModelError(
                "TauBranch not compatible with slowness sampling.")
        # Make sure index_p and index_s really correspond to new ray
        # parameters at the top of this branch.
        s_layer = s_mod.get_slowness_layer(s_mod.layer_number_below(
            top_branch.bot_depth, True), True)
        if index_p >= 0 and s_layer['top_p'] != ray_params[index_p]:
            raise TauModelError("P wave index doesn't match top layer.")
        s_layer = s_mod.get_slowness_layer(s_mod.layer_number_below(
            top_branch.bot_depth, False), False)
        if index_s >= 0 and s_layer['top_p'] != ray_params[index_s]:
            raise TauModelError("S wave index doesn't match top layer.")
        del s_layer
        # Construct the new TauBranch, going from the bottom of the top half
        # to the bottom of the whole branch.
        bot_branch = TauBranch(top_branch.bot_depth, self.bot_depth,
                               self.is_p_wave)
        bot_branch.max_ray_param = top_branch.min_ray_param
        bot_branch.min_turn_ray_param = self.min_turn_ray_param
        bot_branch.min_ray_param = self.min_ray_param
        p_ray_param = -1
        s_ray_param = -1
        array_length = len(self.dist)
        if index_p != -1:
            array_length += 1
            p_ray_param = ray_params[index_p:index_p + 1]
            time_dist_p = bot_branch.calc_time_dist(
                s_mod, top_layer_num, bot_layer_num, p_ray_param)
        if index_s != -1 and index_s != index_p:
            array_length += 1
            s_ray_param = ray_params[index_s:index_s + 1]
            time_dist_s = bot_branch.calc_time_dist(s_mod, top_layer_num,
                                                    bot_layer_num, s_ray_param)
        else:
            # In case index_s==P then only need one.
            index_s = -1
    
        if index_p == -1:
            # Then both indices are -1 so no new ray parameters are added.
>           bot_branch.time = self.time - top_branch.time
E           ValueError: operands could not be broadcast together with shapes (364,) (365,)

obspy/taup/tau_branch.py:249: ValueError
```

**Comment by krischer** [comment]
I looked at this for quite a bit but cannot figure it out unfortunately :-( Can anyone test if such a model would work with the Java TauP package?

**Comment by trichter** [comment]
The [fix_build_taup_model2](https://github.com/obspy/obspy/tree/fix_build_taup_model2) branch adds 2 commits on top of this branch.

**Comment by not522** [comment]
Sorry for my long inactive period. Let me close this PR because #3070 takes over this problem.

**Pull request closed without merging**
