### PR TITLE
Adding python 3.10 to CI testing

### PR DESCRIPTION
**Pull request by ThomasLecocq**
### What does this PR do?

just testing PRs on python 3.10 and checking if all goes well

### Why was it initiated?  Any relevant Issues?

3.10.0 was released on 4 October 2021, and 3.10.1 on 6 December 2021.

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
for now, only image comparisons fail it seems!

**Comment by trichter** [comment]
Fell free to merge.

`sys.version_info` even easier to use: `sys.version_info < (3, 9)`

**Comment by d-chambers** [comment]
@ThomasLecocq

Maybe easier if we just incorporate this into #2489?

**Comment by ThomasLecocq** [comment]
agree :) but you wanted to release #2489 _after_ 1.3.0 no ?

**Comment by d-chambers** [comment]
I originally thought that, but @trichter convinced me its ok to be in 1.3 :wink:

**Comment by ThomasLecocq** [comment]
rebasing on #2489 now...

**Comment by ThomasLecocq** [comment]
> rebasing on #2489 now...

done :-)

**Pull request merged**
