### PR TITLE
Adding basemap with beachball from read_events plot to Obspy Gallery, issue #1750

### PR DESCRIPTION
**Pull request by LMurrayBergquist**
### What does this PR do?
Creates a file with code that creates a basemap with a beachball plot from an inventory event.

### Why was it initiated?  Any relevant Issues?
Part of adding a new map to Obspy Gallery, issue #1750.

### PR Checklist
- [ ] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
+DOCS  (this comment will cause the docs to be built automagically @LMurrayBergquist -- but only when you push another commit to this branch, the docs buildbot only looks at updated PRs)

**Comment by megies** [comment]
@LMurrayBergquist please give the PR a meaningful title and fill in the "What does this PR do?" in the description above with a short info.

**Comment by LMurrayBergquist** [comment]
> +DOCS (this comment will cause the docs to be built automagically @LMurrayBergquist -- but only when you push another commit to this branch, the docs buildbot only looks at updated PRs)
> 
> EDIT: Actually, looks like the buildbot started a build due to the base branch change i made..

Ok, I saw that '+DOCS' was mentioned in the pull request general information, but were should I put that, do I add +DOCS to the name of the pull request?

**Comment by megies** [comment]
> Ok, I saw that '+DOCS' was mentioned in the pull request general information, but were should I put that, do I add +DOCS to the name of the pull request?

It can be in the PR description up top or in any comment in the PR, doesn't matter. The only thing is that adding +DOCS only has an effect on the next update of the PR.

The docs build is here (as indicated by the CI link at the bottom): http://docs.obspy.org/pull-requests/2353/index.html

There you can check if things look like they should after your changes.

**Comment by LMurrayBergquist** [comment]
The document still doesn't show up when the plot is clicked on, although I changed 'target', so that I think should work now...what does the 'alt' section mean? Could that be the issue?

**Comment by megies** [comment]
> The document still doesn't show up when the plot is clicked on, although I changed 'target', so that I think should work now...what does the 'alt' section mean? Could that be the issue?

The link works correctly now. Please note that the docs buildbot needs at least an hour to build new PR docs. As long as it's still yellow at the bottom in the PR checks it's not updated yet.

"Alt" means text that is shown when the image is not showing up correctly.

Other CI fails are unrelated.

**Pull request merged**
