### PR TITLE
bugfix CNV write, fixes #2001

### LINKED ISSUE #2001: CNV writing phase_mapping fails
This line:
https://github.com/obspy/obspy/blob/master/obspy/io/cnv/core.py#L63

doesn't work because 

``values.update(("P", "S"))`` returns ``None``

This works:
```python
values = set(phase_mapping.values())
values.update(("P","S"))
    if values != set(("P", "S")):

```

### PR DESCRIPTION
**Pull request by ThomasLecocq**
Passing ``phase_mapping`` to ``Catalog.write(format="CNV", phase_mapping=...)`` resulted in an exception.

Bugfix #2001 

This https://github.com/obspy/obspy/issues/2009 is not linked but could be part of the same PR?

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
How do I disable the warnings when S phases don't have a mapping in the last test?

**Comment by krischer** [comment]
`warnings.catch_warnings()` - you can also use this to test the raised warning and if it is an expected warning it is a good idea to do so.

**Comment by megies** [comment]
Oh.. @ThomasLecocq should be rebased on `maintenance_1.1.x`!

**Comment by ThomasLecocq** [comment]
@megies did you rebase or just changed the "base branch" of the PR ?

**Comment by ThomasLecocq** [comment]
I _think_ I rebased on ``maintenance_1.1.x`` but then why does it show stuff from you... dunno...

**Comment by megies** [comment]
> I think I rebased on maintenance_1.1.x but then why does it show stuff from you... dunno...

I don't think this worked.. those commits are from `master` and they're not even the original ones but re-commited.. 😜 

I can rebase your branch if you like, but you'll need to check it out fresh from here then..?

**Comment by ThomasLecocq** [comment]
Pleeeaaase do!!!

**Comment by megies** [comment]
@ThomasLecocq please double check. :-)

**Comment by megies** [comment]
Rebased.. can we merge this @ThomasLecocq?

**Comment by ThomasLecocq** [comment]
Yep, if test pass, I guess it's good to go.

**Comment by megies** [comment]
Yeah some conda packaging issues for proj on win it seems

**Pull request merged**
