### PR TITLE
SEG2 date/time separator support

### PR DESCRIPTION
**Pull request by janwillembuist**
### What does this PR do?
Added a regular expression for separating the date and time strings. Before these were hardcoded with separators, but across the world different standard separators for date and time are being used. I changed it with a regex that will split the time string on any non-numeric character, which will split on any default separator as well as on hms. For the date I used a regex that will split on the worldwide accepted separators: oblique stroke (slash), full stop, dot or point (period), hyphen (dash), and space.

I am not really sure how these pull requests work, please correct me if I am wrong!

### Why was it initiated?  Any relevant Issues?

As a happy obspy user I was stumbling upon some seg data that could not be read by obspy. Therefore digged into the date and time stripping methods.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by claudiodsf** [comment]
Continous Integration works again, thanks to @ThomasLecocq! 🥳 

@janwillembuist: could you please rebase and force push, to trigger all the tests?

**Comment by ThomasLecocq** [comment]
> Continous Integration works again, thanks to @ThomasLecocq! 🥳

Yééé, I fixed numpy<1.22 for now, as the error we got is really a bug on their side, hopefully no other stuff will pop up in the meantime

**Comment by ThomasLecocq** [comment]
@claudiodsf should I (huuuuu ? or anyone else who know how this works for branches) cherry-pick the CI for the maintenance branch ?

**Comment by ThomasLecocq** [comment]
or, alternatively, @janwillembuist PR to master

**Comment by claudiodsf** [comment]
> or, alternatively, @janwillembuist PR to master

That will be much easier if @janwillembuist rebases this PR onto master!

**Comment by ThomasLecocq** [comment]
closing this in favor of #2922

**Pull request closed without merging**
