### PR TITLE
update of gcf reader to latest revision of format

### PR DESCRIPTION
**Pull request by paitor**
### What does this PR do?

Update of gcf reader to latest revision of format as described in [SWA-RFC-GCFR, version F - December 2021](https://www.guralp.com/documents/SWA-RFC-GCFR). Move from pure python code to C-base to speed up decoding

### Why was it initiated?  Any relevant Issues?

At present the gcf reader in obspy is not up to date (e.g. see issue #2291) and references to official format documentation is missing (issue #3003). The choice to move to C-base is primarily to speed up reading gcf data but also since I hace an updated C-library that is up to date and tested.

### PR Checklist
(to be completed once update is completed)
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [x] All tests still pass.
- [x] Any new features or fixed regressions are covered via new tests.
- [x] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by trichter** [comment]
> I'm nearing the end of updating the gcf reader and are left with some cleaning up and testing, as well as figuring out how to register the gcf writer that I also added. A quick test indicates a speed-up of a factor of ~80 (albeit using CPython yields a speed-up of a factor ~250)

:+1:

>  The code base will in principle replace the exising code rather than being an update, the exception being the init.py file and code upstream registering the reader under obspy.read(). Given that Ran Novitsky Nof put in an effort in the code to be replaced, I assume that you are fine with me simply adding my name to copyright listed the init.py file rather than replacing his name (wouldn't feel good to erase his effort from contributing, but do not know what is the common procedure)?

I'd say leave his name in there, if some code of Ran is left and/or updated, just add your name. 

>  Part of the code where written by a former colleague of mine (I have his consent to use these parts), would it be appropriate that I also add his name to the init.py file as well as CONTRIBUTORS.txt

Absolutely!

> Is there a way to build and proof-read the documentation prior to submitting the PR (in order to spare the time of everyone but me)

Yes, you can build the documentation locally. Please search the wiki for installation hints. Additionally the documentation will be build with github actions for review, but it takes around 20 minutes.

**Comment by megies** [comment]
> Is there a way to build and proof-read the documentation prior to submitting the PR (in order to spare the time of everyone but me)

just let it build in the PR, doesnt cost anybody any additional time ;-)

**Comment by paitor** [comment]
Yes, sorry. Should never state that one is nearing the end as reality will come haunting you. Unfortunately had some sickness in the family (typical season stuff you get with kids in the pre-school germ pool) as well as some higher prioritized work stuff I had to address, hoping to pick this work up this week but perhaps should not say this out loud...

**Comment by paitor** [comment]
Quick simple question (sorry, never done this before and I'm having problems to digest the information I've found on the web).

What would be the proper command to push my fork (gcf-c-source)?

**Comment by paitor** [comment]
I'm done with the update (including write functionality), have added tests and run through obspy-runtests with no failures but are stuck at pushing the branch. Not really being able to figure out the proper command I tried

    :~$ git push
    fatal: The current branch gcf-c-source has no upstream branch.
    To push the current branch and set the remote as upstream, use
    
        git push --set-upstream origin gcf-c-source

so hoping for some guidance. 

Just noted that this PR is associated with a branch [gcf_alternative](https://github.com/obspy/obspy/tree/gcf_alternative) which is not the name I gave when I created the branch to work in so presumably I've fucked up somewhere along the way

**Comment by paitor** [comment]
Seems like obspy adds some overhead so speedup is only a factor of ~40 (9 s vs. 0.23 s to read a 15 minute file with 4kHz data ~ 7.1MB in size)

**Comment by megies** [comment]
Can you do `git branch -v | grep gcf` and post output here? Way to fix your problems kinda depends on what your branches look like.

**Comment by paitor** [comment]
Here it is:

    :~$ git branch -v | grep gcf
    * gcf-c-source aa156bdaf Merge pull request #3009 from obspy/sds_faster_latency_check

The branch were checked out using:

    :~$ git clone https://github.com/paitor/obspy.git
    Username: paitor
    Password: <token>
    :~$ cd obspy
    :~$ git checkout master
    Already on 'master'
    Your branch is up-to-date with 'origin/master'.
    :~$ git checkout -b gcf-c-source
    Switched to a new branch 'gcf-c-source'

**Comment by megies** [comment]
I don't know what happened to your original branch you opened this PR with, but I guess if you just want to push what you currently have on that other branch you could do something like

```
git branch --set-upstream-to=origin/gcf_alternative
git push -f
```

**Comment by paitor** [comment]
Ok I'll try that out when I get home this evening, just a bit curious as to why the branch ended up to be `gcf_alternative` which is an older and to some extent not relevant branch (as I do not make use of the changes proposed in it) and not the branch `gcf-c-source` I thought I created. Is this something I missed (made a wrong choice) when I opened the PR?

It would be nice to know for future reference as I'm planning to also add read/write support for the bc-format (a waveform data format associated with the SIL processing system used in Iceland and Sweden) as well as some plot functionality for plotting amplitude and phase spectra that I think is missing at present in obspy, so would be good to do it properly next time.

**Comment by megies** [comment]
> just a bit curious as to why the branch ended up to be `gcf_alternative` which is an older and to some extent not relevant branch (as I do not make use of the changes proposed in it) and not the branch `gcf-c-source` I thought I created. Is this something I missed (made a wrong choice) when I opened the PR?

I have no clue, I guess you just picked a wrong branch from the dropdown?

In any case, the head branch can't be changed for a PR, so you can either force push over this branch's history (like above) or close this PR and open a new PR. I don't care either way, the latter would just spread out discussion on the topic across multiple tickets.

**Comment by paitor** [comment]
Good, so I'll try a force push then to keep it together if possible

**Comment by megies** [comment]
Even though its not strictly necessary (git would've kept the info without a branch tip pointing at it too), I've pushed a copy of the branch to here, so feel free to just force push over it.
https://github.com/obspy/obspy/tree/gcf_alternative_backup_2022

**Comment by paitor** [comment]
Sorry to say that did not work out of the box, suggestions?

    :~$ git branch --set-upstream-to=origin/gcf_alternative
    Branch 'gcf-c-source' set up to track remote branch 'gcf_alternative' from 'origin'.
    :~$ git push -f
    fatal: The upstream branch of your current branch does not match
    the name of your current branch.  To push to the upstream branch
    on the remote, use
    
        git push origin HEAD:gcf_alternative
    
    To push to the branch of the same name on the remote, use
    
        git push origin gcf-c-source
    
    To choose either option permanently, see push.default in 'git help config'.
    
    :~$ git push origin HEAD:gcf_alternative
    Username for 'https://github.com': paitor
    Password for 'https://paitor@github.com': 
    remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
    remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
    fatal: Authentication failed for 'https://github.com/paitor/obspy.git/'
    :~$ git push origin HEAD:gcf_alternative
    Username for 'https://github.com': paitor
    Password for 'https://paitor@github.com': 
    To https://github.com/paitor/obspy.git
     ! [rejected]            HEAD -> gcf_alternative (non-fast-forward)
    error: failed to push some refs to 'https://github.com/paitor/obspy.git'
    hint: Updates were rejected because a pushed branch tip is behind its remote
    hint: counterpart. Check out this branch and integrate the remote changes
    hint: (e.g. 'git pull ...') before pushing again.
    hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Presumably HEAD should have been something else but what (sorry for the newbie questions).

**Comment by paitor** [comment]
Perhaps it is just easier to close this PR and open a new one, just a few questions to try to get it right this time:

- In the new PR I simply chose the gcf-c-source branch, or do I need create a new branch and migrate my changes there? (interestingly when I search for branches on https://github.com/obspy/obspy/branches I can't find any branch called gcf-c-source)
- How do I close this PR?

**Comment by paitor** [comment]
Ok, I finally figured it out. Basically never having used git before what I failed to understand were that I after checking out a new branch also needed to set the upstream branch on the first push and this has to be done prior to submitting a PR else the branch is not available on github. Anyway, I decided to simply close this PR and open a new one (#3055 ) as most of the discussion here so far rather reflects my lack of understanding of git than the PR

**Pull request closed without merging**
