### PR TITLE
Fix #2421. Read/write support for StationXML schema version 1.1

### LINKED ISSUE #2421: Update to FDSN StationXML 1.1
We need to update to StationXML 1.1: see https://github.com/FDSN/StationXML/releases/tag/v1.1

### PR DESCRIPTION
**Pull request by nick-iris**
### What does this PR do?

This PR adds read/write support for StationXML schema version 1.1.

A list of updates between schemas 1.0 and 1.1 may be found at:
https://github.com/FDSN/StationXML/blob/master/Changes.md

The following is a checklist of updates that have been implemented in this PR so far. All of these need to be completed before merging.
- [X] Add (persistent) \<Identifier\> element to all base nodes (Network, Station, Channel)
- [x] Unify response elements, allow "number" attribute to \<Numerator> and \<Denominator\>
- [X] Allow \<CreationDate\> to be optional
- [x] Use xs:double for \<ApproximationLowerBound\>, \<ApproximationUpperBound\> and \<MaximumError\>
- [x] Include data availability elements described in the fdsn-station+availability-1.0.xsd extension schema as options elements of the main schema
- [X] Remove \<StorageFormat\> from \<Channel\>
- [X] Limit each \<Operator\> to a single \<Agency\>
- [x] Allow more than a single \<Equipment\> occurrences in \<Channel\>, same as in \<Station\>
- [X] Allow \<Operator\> at the <Network> level, same as in \<Station\>
- [x] Add "sourceID" attribute, with URI value, to the base node type for \<Network\>,\<Station\>,\<Channel\>
- [x] Do not require and disallow \<StageGain\> for \<Polynomial\> response stages
- [x] Add "measurementMethod" attribute to "uncertaintyDouble" attribute group used by azimuth, dip, distance, latitude, longitude, elevation, etc. types
- [X] Add \<WaterLevel\> and within \<Station\> and \<Channel\>
- [x] Add "subject" attribute to \<Comment\> to allow relating comments, make "id" attribute optional.

### Why was it initiated?  Any relevant Issues?

Fix for issue #2421

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [x] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
I think aiming at supporting to write multiple different StationXML versions is opening Pandora's box. It will get a mess real quick. The way to go IMHO is only ever write latest StationXML version and rely on stylesheets for conversion which honestly should be something FDSN has to maintain. Other opinions?

**Comment by ThomasLecocq** [comment]
agree, what about providing a wrapper to the stylesheets conversion ? 👍

**Comment by megies** [comment]
Do stylesheets exist?

**Comment by megies** [comment]
If started fixing this but there's still loads to do.

**Comment by nick-iris** [comment]
I'll work on this some more today. I'll remove support for writing both versions of StationXML. I agree that this will make the code cleaner, and we can always add this capability later if necessary.

**Comment by nick-iris** [comment]
@megies We're getting closer. There's still a few more features of StationXML 1.1 that need to be added (see the list in the PR description).

I've created the attached xml file for my local testing. The file exposes the features/limitations of StationXML 1.1 that have been addressed so far in the code. We're going to need to rework a bunch of the unit tests.

Can you help me with this?

[sxml_1_1.zip](https://github.com/obspy/obspy/files/3929782/sxml_1_1.zip)

**Comment by megies** [comment]
We'll need to see what to do about this: https://github.com/FDSN/StationXML/commit/e43e5145c0c6c7e328468ce774ac9f8cada0e7dc#r36407872

**Comment by megies** [comment]
@nick-iris I think most should be handled now.. but we still need tests for 1.1 xmls.

* Add (persistent) <Identifier> element to all base nodes (Network, Station, Channel)
       - check if invalid URI strings are allowed by xml schema!
* Allow more than a single <Equipment> occurrences in <Channel>, same as in <Station>
       - check kwarg deprecation decorator
* Do not require and disallow <StageGain> for <Polynomial> response stages
       - should we remove stage gain from polynomial completely?
* Add "measurementMethod" attribute to "uncertaintyDouble" attribute group used by azimuth, dip, distance, latitude, longitude, elevation, etc. types
       - check measurement_method loading/saving for Poles/Zeros
* Include data availability elements described in the fdsn-station+availability-1.0.xsd extension schema as options elements of the main schema
       - API change in attributes of DataAvailability, missing tests for full range of possibilities
* Unify response elements, allow "number" attribute to <Numerator> and <Denominator>
       - also removed the "unit" in schema, should we adapt that as well?

should be done fully:
* Add "sourceID" attribute, with URI value, to the base node type for <Network>,<Station>,<Channel>
* Add <WaterLevel> and within <Station> and <Channel>
* Add "subject" attribute to <Comment> to allow relating comments, make "id" attribute optional.
* Limit each <Operator> to a single <Agency>
* Allow <Operator> at the <Network> level, same as in <Station>
* Use xs:double for <ApproximationLowerBound>, <ApproximationUpperBound> and <MaximumError>
* Allow <CreationDate> to be optional
* Remove <StorageFormat> from <Channel>

**Comment by megies** [comment]
Most problems should be fixed, let's see what CI says..

**Comment by megies** [comment]
We should definitely still need to add a test reading a 1.0 file that has all the old stuff which was changed and check if we're good with that.

**Comment by megies** [comment]
@nick-iris I might not be able to further work on this any time soon, for reference, the remaining things to look at are mentioned in https://github.com/obspy/obspy/pull/2510#issuecomment-566629706

**Comment by nick-iris** [comment]
@megies Thanks for letting me know. I'll work on this when I have time.

**Comment by megies** [comment]
I think mainly it need some more testing.. if I remember correctly

**Comment by megies** [comment]
I'll probably merge this tomorrow, I think it might be OK like this and I guess there won't be more feedback in here anyway, so can only get feedback from a RC or well.. maybe only from the release, I guess

**Comment by megies** [comment]
Actually still working on this, adding tests and it was still quite buggy..

**Comment by megies** [comment]
Sheeeeeesh, this should do it hopefully..

**Comment by megies** [comment]
@nick-iris this version should now be ready for StationXML 1.1, I hope.. this would be a good time to do some testing/playing around with real world data, esp. looking at those things that changed with StationXML 1.1.

Will push a RC for the obspy release soon.

CC @chad-iris

**Comment by nick-iris** [comment]
Thanks @megies. Sorry I was on PTO for the last week. The [ph5ws-station](https://service.iris.edu/ph5ws/station/1/) web service is now serving StationXML 1.1, and will be a good test case.

**Comment by chad-iris** [comment]
I did some light testing against RESIF's service (http://ws.resif.fr/fdsnws/station/1/), which is returning StationXML 1.1.  No problems, all seemed to work fine.

**Comment by nick-iris** [comment]
I successfully loaded response level StationXML 1.1 from all 109 experiments served from the ph5ws web services. I think this looks good.

**Comment by megies** [comment]
OK, thanks for the feedback, Chad, Nick. Good to hear we can read that big data set without errors. There still might be some kinks in there, as I had to change some attribute names etc on obspy classes. I think I have it all covered with deprecation helpers but.. famous last words ;)

**Pull request merged**
