### PR TITLE
Default units "DEF" option for sensor response

### PR DESCRIPTION
**Pull request by claudiodsf**
### What does this PR do?

Adds a `"DEF"` option (default units) to `Inventory.plot_response()` and `Trace.remove_response()` (plus other helper functions).

Useful if the units for a particular type of sensor (e.g., a pressure sensor) cannot be converted to displacement, velocity
or acceleration.

This option is available in the underlying library `evalresp` (see `-u def` in evalresp manpage). This PR simply exposes it via
the ObsPy API.

### Why was it initiated?  Any relevant Issues?

The current options for `output` in `Trace.remove_response()` (`"DISP"`, `"VEL"` or `"ACC"`) are confusing for people working on non-ground-motion sensors (e.g., a pressure sensors). Correctly removing the response for these kind of sensors requires using the `"VEL"` option, which is misleading.

An example of user confused by the option is [here](https://gitter.im/obspy/obspy?at=60461bc444f5a454a4613a01).

In this PR, I expose the `"DEF"` option which is already available in `evalresp` (see `-u def` in [manual](https://ds.iris.edu/ds/nodes/dmc/software/downloads/evalresp/5-0-0/manual/))

### PR Checklist
- [X] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [X] This PR is not directly related to an existing issue (which has no PR yet).
- [X] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by barsch** [comment]
> 
> 
> Not sure if `1T_MONN_00_EDH.xml` is in the right path (currently in `obspy/core/tests/data/`).

shouldn't that test be part of ```io.stationxml``` ?

**Review by ThomasLecocq — CHANGES_REQUESTED** [review]
agree with @barsch the XML could go to the io/stationxml/data location

**Comment by ThomasLecocq** [comment]
@claudiodsf could you move the XML file & rebase, then it's good to go

**Comment by ThomasLecocq** [comment]
the macOS test will fail, but I'm on it, so it'll require one last rebase if I succeed :-)

**Comment by ThomasLecocq** [comment]
@claudiodsf looks like the test will pass smoothly... Just re-reading it all now, and wonder if it wouldn't be better to be more explicit for the ``output`` and call it ``DEFAULT`` instead of ``DEF`` ?

**Comment by claudiodsf** [comment]
> @claudiodsf looks like the test will pass smoothly... Just re-reading it all now, and wonder if it wouldn't be better to be more explicit for the `output` and call it `DEFAULT` instead of `DEF` ?

I don't know: other options are abbreviated (`"DISP"`, `"VEL"`, `"ACC"`), mimicking --I guess-- `evalresp` options (`dis`, `vel`, `acc`, `def`).

**Comment by ThomasLecocq** [comment]
> > @claudiodsf looks like the test will pass smoothly... Just re-reading it all now, and wonder if it wouldn't be better to be more explicit for the `output` and call it `DEFAULT` instead of `DEF` ?
> 
> I don't know: other options are abbreviated (`"DISP"`, `"VEL"`, `"ACC"`), mimicking --I guess-- `evalresp` options (`dis`, `vel`, `acc`, `def`).

ok for me :-)

**Comment by ThomasLecocq** [comment]
@claudiodsf sorry, again: please add a line in the changelog about this!

**Review by ThomasLecocq — APPROVED** [review]

**Comment by ThomasLecocq** [comment]
thanks! merged!

**Pull request merged**
