### PR TITLE
Fix documentation of get_pierce_points_geo()

### PR DESCRIPTION
**Pull request by seisman**
### What does this PR do?

Fixes a small error in documentation.

### Why was it initiated?  Any relevant Issues?

NO
### PR Checklist
- [X] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [X] This PR is not directly related to an existing issue (which has no PR yet).
- [X] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+DOCS"
- [X] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [X] All tests still pass.
- [X] Any new features or fixed regressions are be covered via new tests.
- [X] Any new or changed features have are fully documented.
- [X] Significant changes have been added to `CHANGELOG.txt` .
- [X] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by seisman** [comment]
BTW, there are four `maintenance...` branches. It's a little confusing to choose the correct one. Please delete useless branches.

**Comment by megies** [comment]
> It's a little confusing to choose the correct one. Please delete useless branches.

Good point, I'm gonna push those (most likely never again needed) backup branch tips to my fork and delete them on the main repo.

**Comment by megies** [comment]
Thanks for the docs bugfix @seisman. :+1:

**Comment by seisman** [comment]
@megies What about the branch [maintenance_1.0.x](https://github.com/obspy/obspy/tree/maintenance_1.0.x)? I think it's outdated and also should be deleted.

**Comment by megies** [comment]
It's still a valid branch head, even though we don't do bug fix releases for older versions. I don't know, it's been around for a long while and I don't think a lot of people were confused by it. It's pretty normal with Python projects on github to leave old version branches open, so I'd vote to keep it.

**Pull request merged**
