### PR TITLE
fix github master actions

### PR DESCRIPTION
**Pull request by d-chambers**
### What does this PR do?

This PR is a follow up on #2689. The workflows which are set to run on any pushes to master previously passed module names prepended with a "obspy." to the test runner. This resulted in no tests being run and our code coverage (temporarily) being reported at 5%. This should be fixed as soon as tests on master pass again.  

The CI badges were also changed. The name of the GH action now matches the name of the default master test workflow, which currently is "master_default_tests", but we can change the name so the badge is more clear. 

image

### PR Checklist
- [ ] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
I'll just merge this and see what happens :laughing:

**Comment by d-chambers** [comment]
Ok, it looks like it did what it is supposed to do. We should be good to go once we fix the mpl issues.

**Comment by megies** [comment]
> once we fix the mpl issues

we might not be able too, since its between mpl and basemap. might be the time to abandon ship..

**Comment by megies** [comment]
Also coverage shows 5% now somehow..

**Comment by d-chambers** [comment]
> might be the time to abandon ship

So it is time to rewrite ObsPy in Julia, Go, or Rust? Or maybe Fortran 77 if we want to reach more seismologists? 😜 

> Also coverage shows 5% now somehow..

Yes, sorry if my explanation wasn't clear. Before the modules to test were not collected correctly on the master branch tests so it just reported test coverage from a small part of ObsPy. Now the correct module names are getting passed to the test runner but the tests are failing so CI fails before it gets to the upload coverage step. Once the tests pass again on master it should report the correct coverage.

**Comment by megies** [comment]
> Once the tests pass again on master it should report the correct coverage.

Oh OK, gotcha

**Comment by megies** [comment]
> > might be the time to abandon ship
> 
> So it is time to rewrite ObsPy in Julia, Go, or Rust? Or maybe Fortran 77 if we want to reach more seismologists? stuck_out_tongue_winking_eye

:stuck_out_tongue_winking_eye: was talkin bout basemap :wink:

**Pull request merged**
