### PR TITLE
fix ci builds

### PR DESCRIPTION
**Pull request by d-chambers**
### What does this PR do?

This PR attempts to get the travis CI working again.

### Why was it initiated?  Any relevant Issues?

Travis is failing

### PR Checklist
- [ ] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by QuLogic** [comment]
Well, it's definitely looking better... We need to decide on something for the pickling thing to fix the last few bits (except the Python 2.7 build).

**Comment by d-chambers** [comment]
It looks like py 2.7 the min dep. version is missing gfortran still, perhaps related to the [issue you opened](https://github.com/ContinuumIO/anaconda-issues/issues/445)? I will try explicitly installing it on the min dep build.

**Comment by d-chambers** [comment]
Travis 2.7 build is still failing, any ideas on that one?

**Comment by QuLogic** [comment]
Hmm, I'm confused. Both `pip freeze` and `conda list` say  NumPy is installed, so it should be... It must be failing to load some shared library dependency or something, but the message is not too clear. Try running a simple script that just `import numpy` and see what the real error is?

We should get out 1.2.0 and drop Python 2.7 support ASAP.

**Pull request merged**
