### PR TITLE
Remove extra executable bits and shebangs

### PR DESCRIPTION
**Pull request by QuLogic**
### What does this PR do?

These files have no code to run, so remove the executable bit and shebang.

Some files do have a doctest boilerplate, but no doctests to run, so remove the boilerplate too. I left the shebang and boilerplate in files with actual doctests, though actually, I think we should remove the shebang in those files too since they were never marked executable.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [] Any new features or fixed regressions are be covered via new tests.
- [] Any new or changed features have are fully documented.
- [??] Significant changes have been added to `CHANGELOG.txt` .
- [] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by megies** [comment]
I fully agree with the executable bit / shebang stuff. With the superfluous  doctest parts, I'm a bit torn. Obviously they should in principle be removed, but I think it bears the danger of people copy/pasting to create new submodules and then failing to add the doctest part again (if there are doctests anyway). It's easy to get overlooked in PR reviews

**Comment by QuLogic** [comment]
TBH, I'd rather remove all the doctest boilerplate altogether. The files aren't executable, so you have to run `python path/to/file.py` anyway, then you might as well run `python -m doctest path/to/file.py`, and for installed files, you could use `pytest` (bit unfortunate to have to use a different command there though.)

**Comment by megies** [comment]
Actually yeah, I kinda agree, we might as well get rid of all these

**Review by ThomasLecocq — APPROVED** [review]

**Comment by megies** [comment]
sorry for not merging earlier

**Pull request merged**
