### PR TITLE
add changelog for #2723

### PR DESCRIPTION
**Pull request by trichter**
I wanted to push directly to master, but I was not allowed. So, here is the changelog entry.

### CODE REVIEW

**Comment by megies** [comment]
That's weird.. I just checked and you are in @obspy/maintainers and that team should be able to make normal fast-forward pushes to master (no force pushes), according to the branch protection rules.

**Review by megies — APPROVED** [review]
feel free to merge this one or try to push commit directly on master again (should work in principle)

**Comment by trichter** [comment]
Now pushing the master branch was working, but I suspect it only worked because you approved the commit here.
Previously an error about one needed approving review was displayed.

**Comment by megies** [comment]
> Now pushing the master branch was working, but I suspect it only worked because you approved the commit here.

Hmm.. i still think you should be able to push fast-forwardable commits to master directly according to the settings. Well no big deal anyway

**Comment by trichter** [comment]
I'll try again, the next time.

**Pull request merged**
