### PR TITLE
Fix incomplete read

### LINKED ISSUE #3028: http.client.IncompleteRead: IncompleteRead(145883 bytes read)
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

In python console, whenever I request for data with minmag less than 7, it throws this error. But when I use minmag 7 or greater than that, it works fine.
I tried updating obspy too.
Plz help.
image

### Code to Reproduce

```python
from obspy.clients.fdsn import Client
client = Client()
cat=client.get_events(starttime='2013-07-01', endtime='2599-12-31', minmagnitude=6)
print(cat)
```

### ObsPy Version?

1.3.0

### Operating System?

windows

### Python Version?

3.8.12

### Installation Method?

conda

### PR DESCRIPTION
**Pull request by wsja**
### What does this PR do?

Handle IncompleteRead exception by giving the user a hint on how to circumvent it.

### Why was it initiated?  Any relevant Issues?

fixes  #3028

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [x] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [x] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by wsja** [comment]
Sorry, this should be merged into `maintenance_1.3.x`, which changed during refresh.

**Comment by wsja** [comment]
`IncompleteRead` does not have a `message` attribute, which is why we are raising `HTTPException` instead. The `IncompleteRead` will still show up in the traceback.

**Review by megies — APPROVED** [review]
Looks good to me. :+1: 
I'll retrigger CI so we get FDSN tests run..

**Comment by megies** [comment]
You could add a changelog one-liner, but it's a small change so I'm also OK with not having one.

**Comment by megies** [comment]
Thanks!

**Comment by megies** [comment]
Added you to the devs team too, so you can push branches to main repo next time if you prefer that.

**Pull request merged**
