### PR TITLE
Remove use of distutils

### PR DESCRIPTION
**Pull request by QuLogic**
### What does this PR do?

In main code, `distutils` can be dropped, as the version check is no longer necessary. In tests, it can be replaced by `packaging.version`.

### Why was it initiated?  Any relevant Issues?

`distutils` is deprecated and will be removed in Python 3.12.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Review by trichter — APPROVED** [review]

**Comment by d-chambers** [comment]
Any ideas on the windows failure in the CI?

**Comment by trichter** [comment]
Could the test fail in windows be related to the changes in this PR?

**Comment by d-chambers** [comment]
> Could the test fail in windows be related to the changes in this PR?

Let's see if it happens again on a restart.

**Comment by d-chambers** [comment]
Same failure on windows, python 3.7 after restart.

**Comment by QuLogic** [comment]
OK, I'll drop the `sysconfig` commit for now, though it really should be a copy of the main one. I'll put that in #2422 instead.

**Review by ThomasLecocq — APPROVED** [review]

**Pull request merged**
