### PR TITLE
Enable means of creating response object from pole/zero list

### PR DESCRIPTION
**Pull request by amkearns-usgs**
Thank your for contributing to ObsPy!

Before submitting a PR, please review the pull request guidelines:
https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-a-pull-request

Also, please make sure you are following the ObsPy branching model:
https://github.com/obspy/obspy/wiki/ObsPy-Git-Branching-Model

### What does this PR do?

Adds a means of creating a response object from lists of poles and zeros, using default parameters as appropriate. (Feature request)

### Why was it initiated?  Any relevant Issues?

This was initiated from discussion in issue #1824.

### PR Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests still pass.
- [*] Any new features or fixed regressions are be covered via new tests.
- [*] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [*] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by krischer** [comment]
Something went wrong there. Make sure to apply your changes to the latest `master`.

You somehow added another `obspy` folder and copied everything there.

**Comment by amkearns-usgs** [comment]
Argh. Let me see if I can revert that. (Danged ingrained habits from our
work's git setup, I'm blaming this on...like four different configurations
at this point, must have happened when I tried to do git clone or git
checkout).

*Aaron Kearns*

KBRwyle  |  Software Engineer
Target Road 10002 Isleta SE  |  Kirtland AFB, NM 87117  |  USA
Office: +1 505.853.2582  |  Mobile: +1 304.997.0148  |  akearns@usgs.gov  |
 aaron.kearns@kbrwyle <aaron.kearns@kbrwyle.com>.com
<aaron.kearns@honeywell.com>

**Comment by krischer** [comment]
You still have to delete the other top-level folder copies in the inner `obspy` folder. You can locally check with 

```bash
git diff --name-status master
```

to see all the files that changed relative to `master`. Once you are done, please squash all commits and do a force push.

**Comment by amkearns-usgs** [comment]
Still running into an issue -- when I get that I get the error `ambiguous argument 'master': unknown revision or path not in the working tree.` I assume this is because it's not sure which fork to compare to?

**Comment by amkearns-usgs** [comment]
Never mind, needed to set `upstream/master`. This should be just a minute or two.

**Comment by krischer** [comment]
Just pinging you to let you know that now there is nothing to see here. Would be great to have this functionality.

**Comment by aringler-usgs** [comment]
Lion I think we are battling our internal (USGS) git conventions.  We will try to get this sorted out.

**Comment by krischer** [comment]
No need to hurry :) Just wanted to make sure you are aware of this!

**Pull request closed without merging**
