### PR TITLE
Linear regression cleanup

### PR DESCRIPTION
**Pull request by ThomasLecocq**
cleanup version of #1716

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
+DOCS

**Comment by ThomasLecocq** [comment]
i have no |@#{#^ idea how to @{|@[ rebase this  |@# on master. I'll stop git|@#[ for a few hours/days. Cheers guyz

**Comment by krischer** [comment]
> should I allow *kwargs to be passed @krischer ?

why not I guess - but seems you already did so.

**Comment by krischer** [comment]
Let me know when you are done so I can review.

**Comment by ThomasLecocq** [comment]
@krischer I think this is now ok

**Pull request merged**
