### PR TITLE
Fix some network test fails

### PR DESCRIPTION
**Pull request by megies**
Been working on this report: http://tests.obspy.org/53048/

 - Arclink and Neic fails are resolved.
 - I can't reproduce the seedlink fails 
 - Will leave the syngine fails to @krischer.

+TESTS:ALL

### CODE REVIEW

**Comment by megies** [comment]
Rebased and force-pushed to see current status of fails.. @krischer maybe you can check those syngine fails when you find some time (and when CI is finished running the current commit in here)?

**Comment by krischer** [comment]
The `clients.syngine` failures are not our fault and all related to https://github.com/iris-edu/irisws-syngine/issues/33.

**Comment by megies** [comment]
Rebased and force-pushed. We can check again if there's anything left to do in the Travis reports..

**Comment by krischer** [comment]
The syngine service has been fixed and I changes the one test to overly rely on the velocity model used to calculate the times. Should be good now.

**Comment by megies** [comment]
Looks like we need to do some minimal change to arclink tests too.. https://travis-ci.org/obspy/obspy/jobs/170783439#L997

**Comment by krischer** [comment]
Should be good now - let's wait for CI.

**Comment by megies** [comment]
Gonna merge this now. Let's see how build status for maintenance and master evolve from there..

**Pull request merged**
