### PR TITLE
FDSN Mass Downloader supporting restricted data

### PR DESCRIPTION
**Pull request by krischer**
It could be useful if "FDSN Mass Downloader" would support downloading restricted data apart from public one.

Could be something like this:

`providers = [`
`[http://fdsn.service, username, password],`
`[http://fdsn.service2, username2, password2],`
`[http://fdsn.service3, username3, password3]`
`]`

### CODE REVIEW

**Comment by krischer** [comment]
This is now a PR including tests and documentation. It now works like this:

```python
from obspy.clients.fdsn import Client

client_orfeus = Client("ORFEUS", user="random", password="some_pw")
client_eth = Client("ETH", user="from_me", password="to_you")

mdl = MassDownloader(providers=[client_orfeus, "IRIS", client_eth])
```

This is nice because its quite general and will also work if we potentially support other authentication methods in the future. It will just reuse the passed client instance.

**Comment by krischer** [comment]
No reviews yet but I'm merging as this is a small change, mostly on a part of ObsPy that is my doing, and it has a test :-)

**Comment by megies** [comment]
@krischer, changelog maybe?

**Comment by krischer** [comment]
Oops. My bad - I just added it to the latest master.

**Pull request merged**
