### PR TITLE
Omit more warnings in unit/doctests

### PR DESCRIPTION
**Pull request by barsch**
also small bugfixes in sac and pde which resulted into warnings ...

### CODE REVIEW

**Comment by barsch** [comment]
failing tests are unrelated - see #1554 - imho ready to merge

**Comment by barsch** [comment]
@jkmacc-LANL if ```header.get(hdr)``` is numeric you will get an ```Unicodewarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal```

**Comment by jkmacc-LANL** [comment]
Oi, that might be a typo.  The relative time headers are all floats, so I think comparison should be against the float null value, `HD.FNULL`.  Yup, I'm pretty sure it should be `HD.FNULL`.  If you make that change with the original `in ( )` syntax, do the warnings go away?

**Comment by barsch** [comment]
will check once I'm at home

**Comment by jkmacc-LANL** [comment]
Thanks for the catch!

**Pull request merged**
