### PR TITLE
add example and improve stream detrend docs

### PR DESCRIPTION
**Pull request by d-chambers**
### What does this PR do?

Tries to improve the docstring for `obspy.core.stream.Stream.detrend` method by rewording slightly and adding an example.

### Why was it initiated?  Any relevant Issues?

see #2055

+DOCS

### CODE REVIEW

**Comment by megies** [comment]
Thanks! Would you mind adding the `:param options:` as proposed by OP in #2055, I think he has a point there.

**Comment by trichter** [comment]
The code block does not render correctly.
Here is a link to the relevant [doc](http://docs.obspy.org/pull-requests/2237/packages/autogen/obspy.core.stream.Stream.detrend.html#obspy.core.stream.Stream.detrend).

**Comment by d-chambers** [comment]
I cherry-picked the relevant commits onto master to get rid of the merge commit. When docs are done building this should be ready to review/merge if the example renders correctly.

**Comment by megies** [comment]
Actually, on a second look, the detail descriptions and example should probably go to the API docs of `Trace.detrend()`, I think. For all methods on Stream that are basically just doing a `for tr in self.traces: ...`, we always have the Stream docs pretty much empty, pointing to the corresponding Trace method, mainly to avoid duplicated maintenance efforts (which are also prone to get broken on changes).

**Comment by d-chambers** [comment]
@megies, sure, I don't mind moving the changes to `trace.detrend`. I think we should keep the in-place warning on `Stream` though. Also, there are other stream methods with fairly extensive docs/examples such as `attach_response`, `normalize`, `std`, `interpolate`, `decimate`, etc. Should we look and pushing most of the detail in the docs for those methods to their corresponding `trace` methods?

**Comment by krischer** [comment]
> @megies, sure, I don't mind moving the changes to `trace.detrend`. I think we should keep the in-place warning on `Stream` though. Also, there are other stream methods with fairly extensive docs/examples such as `attach_response`, `normalize`, `std`, `interpolate`, `decimate`, etc. Should we look and pushing most of the detail in the docs for those methods to their corresponding `trace` methods?

I wanna say yes. I think for a proper solution we should try to find some automated way to deal with this. We could use decorators to mark functions as being in-place and only document things at the `Trace` level and have some sphinx trickery to also render it with the equivalent `Stream` functions.

**Comment by calum-chamberlain** [comment]
[docrep](https://docrep.readthedocs.io/en/latest/) might be useful here - it would be nice to not have to jump from a `Stream` method to a `Trace` method.  I haven't tried docrep, so I don't know if it will work/be useful, and it would add a dependency.

**Comment by krischer** [comment]
> [docrep](https://docrep.readthedocs.io/en/latest/) might be useful here - it would be nice to not have to jump from a `Stream` method to a `Trace` method. I haven't tried docrep, so I don't know if it will work/be useful, and it would add a dependency.

That's fine - I think we can make this a doc building only dependency. We'd just try to import it and if its not available we provide dummy decorators.

This look really nice -  I think I'll use this for a bunch of my things. Thanks for making me aware of it!

**Comment by d-chambers** [comment]
The only subtlety here is that we will want to be careful not to ruin the usefulness of docstrings in the REPL. If we don't make it a hard dependency this would be easy to do.

**Comment by megies** [comment]
> Should we look and pushing most of the detail in the docs for those methods to their corresponding `trace` methods?

That would make it more consistent, yeah. Or look into the docrep thingy right away.
Anything that improves docs is fine by me.

**Comment by megies** [comment]
> If we don't make docrep a hard dependency

As mentioned before, no hard dependency for sure. Just for docs building.

Btw.. how does docrep templates show up in e.g. IPython docstring queries? I guess these will be a bit messy then. Actually, I guess that was what @d-chambers pointed out (no idea what REPL stands for ^^)

**Comment by d-chambers** [comment]
@megies exactly my concern. REPL is Read Eval Print Loop (like ipython). I am done with this unless you think it's worth trying to cleanup all the trace/stream docs in this PR, which I don't mind doing.

**Comment by megies** [comment]
> I am done with this unless you think it's worth trying to cleanup all the trace/stream docs in this PR, which I don't mind doing.

Gonna merge this then. You can do a new PR if you feel like more cleanup, though there might be better spots to work on, I think, esp. what's left in https://github.com/obspy/obspy/milestone/17 and combing through https://github.com/obspy/obspy/milestone/16

**Pull request merged**
