### PR TITLE
docker: adjust cronjob docker testbot script for usage outside of vbox

### PR DESCRIPTION
**Pull request by megies**
on a normal workstation, and also add some more docs..

CC @krischer

### CODE REVIEW

**Comment by krischer** [comment]
As far as I understand it I have to merge this before I can try it, right?

**Comment by megies** [comment]
> As far as I understand it I have to merge this before I can try it, right?

You can check out this branch in a local clone and run it there

**Comment by krischer** [comment]
Oh - so you mean haveing one obspy repository with the script and a separate working dir. Got it.

**Comment by megies** [comment]
Reportedly works well with @krischer's new testbot, so merging.

**Pull request merged**
