### PR TITLE
Enhance Trace.times() (more output options)

### PR DESCRIPTION
**Pull request by megies**
First and foremost intended for convenient plotting in matplotlib axes with a
time axis..

```python
import matplotlib.pyplot as plt
from obspy import read

tr = read()[0]
plt.plot(tr.times(type="matplotlib"), tr.data)
fig = plt.gcf()
fig.autofmt_xdate()
fig.axes[0].xaxis_date()
plt.show()
```

Still needs ..
 * [x] tests
 * [x] mention in "plotting waveforms" tutorial page
 * [x] changelog

### CODE REVIEW

**Comment by krischer** [comment]
Very cool. We should have added this ages ago!

**Comment by megies** [comment]
> Very cool. We should have added this ages ago!

Oh, yes. The last time i wanted to show somebody how to plot the dates and then hacking together an ugly one-liner for this finally was the last drop.. ;-)

**Comment by QuLogic** [comment]
Hah, I was just thinking of how this could be done yesterday... We're on the same wavelength, it seems...

One more useful thing is to add a `reftime=...` for the relative timing, so instead of starting at 0, start at `starttime - reftime`.

**Comment by krischer** [comment]
> One more useful thing is to add a reftime=... parameter for the relative timing, so instead of starting at 0, start at starttime - reftime.

:+1: That would indeed be useful.

**Comment by megies** [comment]
`reftime` for me sounds like a static reference time.. (i.e. i'd expect it as time of first sample -- is that concept coming from SAC?) I'd rather expect a name like `relative_offset` or similar for a shift from `stats.starttime`.

If it's a simple shift it could of course also be done by just `tr.times("relative") - shift` without a kwarg (that would only have an effect for one specific `type`).

**Comment by QuLogic** [comment]
> `reftime` for me sounds like a static reference time.. (i.e. i'd expect it as time of first sample -- is that concept coming from SAC?) I'd rather expect a name like `relative_offset` or similar for a shift from `stats.starttime`

I don't understand what you mean; you expect it to be the time of the first element? If that were the case, why would it be named `reftime` and not `starttime`?

The name is consistent with the argument used in plotting with relative x-axis.

> If it's a simple shift it could of course also be done by just tr.times("relative") - shift without a kwarg (that would only have an effect for one specific type).

That wouldn't handle `UTCDateTime` as a reference time.

**Comment by QuLogic** [comment]
> I'd vote for a non-abbreviated name like `reference_time` though.

Sorry, I missed that. Feel free to change, though as I said, it matches the name in the plotting routine.

**Comment by megies** [comment]
> Sorry, I missed that. Feel free to change, though as I said, it matches the name in the plotting routine.

Yeah, not sure myself.. probably matching the existing kwarg name is more important. Fine with me if it stays as is.

**Comment by megies** [comment]
Will need a rebase for tests to pass, but there's still some TODOs (tests etc.), so no hurry.

**Comment by megies** [comment]
Have to skip one doctest, see 31a2a1a. Should be good to merge now if Travis passes.

**Comment by megies** [comment]
> 2 files (not in diff) in obspy/io/shapefile were modified. more
> 
>     Misses +133
>     Hits -133

Really strange how codecov thinks all these files have been changed when they haven't been.

Merging..

**Pull request merged**
