### PR TITLE
try to fix CI problem

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Changes obspy installation in CI from editable to a regular pip installation.

Also remove the `[tests]` modifier, which does nothing in combination with `--no-deps` anyway and we rely on an environment file for all (testing) dependencies anyway.

### Why was it initiated?  Any relevant Issues?

Some test currently fails because files are being looked up in the install location, which is only holding a link to the source tree though, due to being a pip editable installation.

 - https://github.com/obspy/obspy/actions/runs/3066925112/jobs/4952650308#step:10:268
 - https://tests.obspy.org/127117/#1
 - https://github.com/obspy/obspy/blob/9d10a93d9e862b46b4ce761530ddbb55b414a283/obspy/core/tests/test_waveform_plugins.py#L211-L220

### PR Checklist
- [ ] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
@trichter not sure if there was a reason for doing an editable install in CI, but it started to cause issues and it looks like a regular install does just fine..

**Comment by trichter** [comment]
I think for no specific reason.

**Comment by trichter** [comment]
What I do not understand is, why this error appeared all of a sudden in the CI setup. I myself use this setup for my obspy installation. Will report when/if it breaks.

**Comment by megies** [comment]
I use editable installs all the time too, locally. But CI can have some special setups makin it weird, looks like auto stripping of test file directries maybe? Who knows..

**Comment by megies** [comment]
I actually can reproduce the problem locally now.. happens when using a pip editable install and then going via `obspy-runtests`.

**Comment by trichter** [comment]
For my local installation it is still working. Maybe a change in the entry points stuff of setuptools. Should we revert this PR?

**Comment by megies** [comment]
> For my local installation it is still working. Maybe a change in the entry points stuff of setuptools. Should we revert this PR?

This was fixed by #3142. On a fresh installation with all the newest packages and installing obspy editable after reverting that commit, it fails. As you say, seems to be a change in setuptools, reporting the shimmy directory instead of the git repository location as install base dir.

Anyway, I dont care, if you want to revert this go ahead.

**Comment by megies** [comment]
to reproduce:
```
conda create -n trash obspy
conda activate obspy
conda remove --force --offline obspy
pip install -e /path/to/obspy
# manually revert this commit
obspy-runtests
```

**Comment by megies** [comment]
Oh boy.. too many swapping around tabs and issues.. @trichter yes this change in CI script can be changed back to editable install if you want

**Comment by trichter** [comment]
It's OK. I don't care enough.

**Pull request merged**
