### PR TITLE
rebrand IRIS -> EarthScope

### LINKED ISSUE #3336: Renaming IRIS -> Earthscope
IRIS is now EarthScope. We should rename accordingly, with deprecation handling for a some major release cycles.

see https://github.com/obspy/obspy/issues/3046#issuecomment-1649958130

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Rename IRIS -> EarthScope, this is mostly just docs/docstrings, leave "obspy.clients.iris" module naming as is.

### Why was it initiated?  Any relevant Issues?

Fixes #3336 

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] New modules, add the module to `CODEOWNERS` with your github handle
- [x] Add the yellow `ready for review` label when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
@chad-earthscope I went through our codebase and tried to most appropriately replace "IRIS" wording, even though some of the web services still go under the "IRISWS" label and also I'm not sure if/where it might be more appropriate to use "SAGE" instead of "EarthScope".

Feel free to comment and check out the docs build for this PR when CI is done (https://docs.obspy.org/pr/).

I would really rather keep the module structure/Pathon file naming of `obspy.clients.iris` as is, it's just an insane amount of work to do that and make sure deprecation rerouting works and things can easily break and a lot of peoples' codes will break eventually, since not a lot of people really act on `DeprecationWarnings` :rofl: 
Also, these services are still kinda labeled as "IRISWS" anyway on the respective websites.

**Comment by jkmacc-LANL** [comment]
ObsPy is many students' first introduction to community data at IRIS-now-EarthScope; I think that `from obspy.clients.earthscope import Client` means a lot more than just a Python import.  Is it possible to at least alias a stub `obspy.clients.earthscope` module to `obspy.clients.iris` so that the import statement works?  I realize that it may be more complicated than I realize, but if it's not, it seems worth doing.

**Comment by d-chambers** [comment]
> I realize that it may be more complicated than I think, but if it's not, it seems worth doing.

We could just do a wildcard import at the top of a newly created earthscope module no? 

```python
from obspy.clients.iris import *
```

In that case the modules should behave identically.

**Review by jkmacc-LANL — APPROVED** [review]

**Comment by megies** [comment]
I'll merge this for now @chad-earthscope, but let me know if you have any comments

**Comment by chad-earthscope** [comment]
Thanks @megies, very appreciated change that I've had in the back of my mind, but have no time to deal with.  "EarthScope" is probably best label for now ("SAGE" is our funders facility name, which will change next year).

I agree with all your changes with one exception: "IRISWS Federator" should be "EarthScope Federator".  While there is `irisws` in the interfaces paths, which will remain indefinitely for compatibility, everything else around it will be EarthScope branded.

**Pull request merged**
