### PR TITLE
Update obspy/clients/fdsn/__init__.py

### PR DESCRIPTION
**Pull request by nikosT**
Adding NOA fdsn web service

### CODE REVIEW

**Comment by nikosT** [comment]
I had forked the ObsPy repository, and add NOA line to obspy/clients/fdsn/__init__.py file. I'm not sure though if my fork had the latest obspy/clients/fdsn/__init__.py file. Can you check?

**Comment by petrrr** [comment]
Hi Nicos, that's not the right place to add the data center abbreviations. You just changed the doc string. Please have a look at the `header.py` sources. It should be quite obvious where to put a new data center abbreviation.

**Comment by nikosT** [comment]
You are right!

**Comment by nikosT** [comment]
wrong pull_request

**Comment by krischer** [comment]
Please reopen this pull request. You need to change it in the doc and in the `header.py`.

**Comment by krischer** [comment]
Just add one more commit to the branch.

**Comment by nikosT** [comment]
Actually, I had made a new one here: https://github.com/obspy/obspy/pull/1284
I apologize, since I didn't know how pull_requests work. So this pull and the one https://github.com/obspy/obspy/pull/1283 should be totally removed.

Remove: https://github.com/obspy/obspy/pull/1283, https://github.com/obspy/obspy/pull/1282
Accept: https://github.com/obspy/obspy/pull/1284

**Pull request closed without merging**
