### PR TITLE
Create StationMagnitudeContributions when importing GSE2 bulletin

### LINKED ISSUE #2718: GSE2 bulletin reading: station magnitude contribution not created
I can see there is already a related/similar issue with this [(https://github.com/obspy/obspy/pull/2420 )] but since it has not been finalized I would create a new one.
I am not able to include stationMagnitude to the catalog conversion with my GSE2 format catalog. I thought it was because of my catalog. It might have some formatting problem but I tested it with the example file which was given in the documentation with the same result (no success). Basically, I am able to convert everything apart from the stationMagnitudes. I tested this with the latest v1.2.2 and v1.2.0 with the same result. > Any suggestion or any comment or help are highly appreciated.

### PR DESCRIPTION
**Pull request by acarapetis**
### What does this PR do?

Modifies the `obspy.io.gse2` bulletin reader to link station magnitudes with network magnitudes. For each pick with a station magnitude, we check if the origin has any network magnitudes with the same magnitude type, and if so, we associate them together with a `StationMagnitudeContribution`.

Also ensures the `StationMagnitude.waveformID` attribute is populated (with the same value as `Amplitude.waveformID` and `Pick.waveformID`). (The [documentation](https://docs.obspy.org/packages/autogen/obspy.core.event.magnitude.StationMagnitude.html) suggests this is unnecessary when the stamag's linked amplitude/pick already includes the waveformID; but currently if you import GSE2, export to seiscomp XML and open the resulting magnitude in seiscomp, the station information is missing in the GUI; so at least from a seiscomp-centric perspective the data seems incomplete.)

I've updated the existing `test_bulletin.py`, replacing the previous assertions (which were that there were no associated stamagcontributions and no waveformID) with new ones - hopefully that's all that's required?

Based it on the maintenance branch since it feels like a bug fix to me, let me know if it needs to be rebased.

### Why was it initiated?  Any relevant Issues?

Fixes #2718 

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [x] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [x] All tests still pass.
- [x] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Review by comoglu — COMMENTED** [review]
This fix worked for me.

**Review by megies — APPROVED** [review]
Looks good to me, thanks! Also thanks for the feedback on the PR @comoglu!

**Comment by megies** [comment]
> Based it on the maintenance branch since it feels like a bug fix to me, let me know if it needs to be rebased.

Fine for me, I'll change the PR base branch then

Also @acarapetis feel free to add yourself to the contributors list (CONTRIBUTORS.txt) and please add a short one-liner in the changelog.

**Comment by megies** [comment]
Thanks again @acarapetis, good for merging after CI is done

**Comment by acarapetis** [comment]
@megies no worries, happy to contribute :)
Not sure what the problem with the CI runs is but it doesn't seem related to my changes.

**Comment by megies** [comment]
Yes, unrelated CI fails due to missing images for old Python versions we supported on 1.2.x, merging. Thanks!

**Pull request merged**
