### PR TITLE
Fix for plotting percentiles on a frequency axis.

### PR DESCRIPTION
**Pull request by rannof**
Adding a check for frequency axis and converting percentiles periods to frequency.

### CODE REVIEW

**Comment by megies** [comment]
Thanks for the patch!
Turns out, this bit isn't covered by a test yet. If you feel like it you could add another image test, basically copy pasting this test routine. The baseline image would have to be created using matplotlib 1.3.1 though. Otherwise somebody else can do it in a follow up on this ticket.

Also, feel free to add yourself to [contributors list](https://github.com/obspy/obspy/blob/master/obspy/CONTRIBUTORS.txt).

**Comment by rannof** [comment]
Hi Tobias,
Thanks for the offer. However, I'm not sure I understand completely how to
add a baseline image to the test suit. should I just run it on my computer
and add as a new file?
Cheers,
Ran

On Wed, May 18, 2016 at 6:31 AM, Tobias Megies <notifications@github.com>
wrote:

> Thanks for the patch!
> Turns out, this bit isn't covered by a test yet. If you feel like it you
> could add another image test, basically copy pasting this test routine. The
> baseline image would have to be created using matplotlib 1.3.1 though.
> Otherwise somebody else can do it in a follow up on this ticket.
>
> Also, feel free to add yourself to contributors list
> <https://github.com/obspy/obspy/blob/master/obspy/CONTRIBUTORS.txt>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/obspy/obspy/pull/1406#issuecomment-220026424>
>



-- 
Ran Novitsky Nof
Post-Doc Fellow
Berkeley Seismological  Laboratory
University of California Berkeley

Rm 209, McCone Hall
Mob: 1-805-418-0581
Web: http://ran.rnof.info

**Comment by megies** [comment]
Nevermind about the image test, we can do it if you're unsure about it.

**Comment by rannof** [comment]
Cheers!

On Wed, May 18, 2016 at 1:00 PM, Tobias Megies <notifications@github.com>
wrote:

> Nevermind about the image test, we can do it if you're unsure about it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/obspy/obspy/pull/1406#issuecomment-220140561>
>



-- 
Ran Novitsky Nof
Post-Doc Fellow
Berkeley Seismological  Laboratory
University of California Berkeley

Rm 209, McCone Hall
Mob: 1-805-418-0581
Web: http://ran.rnof.info

**Pull request merged**
