### PR TITLE
Fix gcf block bug, second attempt

### PR DESCRIPTION
**Pull request by paitor**
### What does this PR do?
Fixes a BUG in the algorithm to split and encode last few data points into GCF blocks

### Why was it initiated?  Any relevant Issues?
Issue were brought up in post "MiniSEED to GCF" in discourse.obspy.org forum (https://discourse.obspy.org/t/miniseed-to-gcf/1598)

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [x] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [x] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [ ] All tests still pass.
- [x] Any new features or fixed regressions are covered via new tests.
- [x] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [x] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [x] New modules, add the module to `CODEOWNERS` with your github handle
- [x] Add the `ready for review` tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by paitor** [comment]
Aaarrrggghhhh, please do, appologies

**Comment by megies** [comment]
> Aaarrrggghhhh, please do, appologies

No worries :smile:

**Comment by QuLogic** [comment]
Please correct the commit message as well (or squash merge if you want).

**Review by megies — APPROVED** [review]

**Comment by megies** [comment]
rebased and force pushed

**Pull request merged**
