### PR TITLE
pin sqlalchemy<2

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Pin SQLalchemy to version <2 and suppress deprecation warnings in tests

### Why was it initiated?  Any relevant Issues?

Non backwards compatible changes coming in upcoming version 2.0

- https://docs.sqlalchemy.org/en/20/errors.html#error-b8d9
- https://docs.sqlalchemy.org/en/20/changelog/migration_20.html

CC @chad-earthscope 

Screenshot from 2023-01-20 10-13-22

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] ~~While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds~~
- [ ] ~~If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.~~
- [ ] ~~If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.~~
- [ ] All tests still pass.
- [ ] ~~Any new features or fixed regressions are covered via new tests.~~
- [ ] ~~Any new or changed features are fully documented.~~
- [ ] ~~Significant changes have been added to `CHANGELOG.txt` .~~
- [ ] ~~First time contributors have added your name to `CONTRIBUTORS.txt` .~~
- [ ] ~~If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts.~~
- [ ] ~~New modules, add the module to `CODEOWNERS` with your github handle~~
- [x] Add the `ready for review` tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Review by trichter — APPROVED** [review]
In the long run we should migrate our code. Maybe open a new issue?
Also:
> The most prominent architectural features and API changes that are considered to be “SQLAlchemy 2.0” were in fact released as fully available within the 1.4 series

**Comment by megies** [comment]
> In the long run we should migrate our code. Maybe open a new issue?

Well yeah, somebody would have to step up though, I am not familiar with that code.

**Comment by megies** [comment]
@trichter I'm confused, might be doing something wrong. The added filters in pytest.ini catch the warnings but with `-W err` like in the test runner, they will still show an error

**Comment by megies** [comment]
Even with `ignore:(?s).*` or `ignore:.*` if I add `-W err` the test run fails with that warning raised as an error

**Comment by megies** [comment]
Aren't we doing it like this already for some other warnings? But if I understand docs correctly these filters don't apply with `-W err`?

Screenshot from 2023-01-20 13-24-38

**Comment by trichter** [comment]
> Aren't we doing it like this already for some other warnings?
Exactly
>  But if I understand docs correctly these filters don't apply with -W err?
No, this warning is about the python standard filters.

I'll check out locally.

**Comment by trichter** [comment]
I checked, you are right.

> The added filters in pytest.ini catch the warnings but with -W err like in the test runner, they will still show an error

It is working as expected for the other warnings.

**Comment by trichter** [comment]
I pushed one unrelated commit to this branch.

**Comment by trichter** [comment]
Now I remember... I have seen this before

> ERROR collecting clients/filesystem/db.py

The error is raised in the collection stage before the test suite is started.
If you replace `filterwarnings =` in `pytest.ini` with
````
filterwarnings =
error
```

and start the runtests normally it is working as expected.
I see two solutions:
1. Move `Base = declarative_base()` into the two functions or
2. Do not use `-W error`, but a different custom flag which writes a temporary ini file and load this with `-c`

**Comment by megies** [comment]
> The error is raised in the collection stage before the test suite is started.

Ah... makes sense. Nice catch.

> I see two solutions:
> 
>     1. Move `Base = declarative_base()` into the two functions or
> 
>     2. Do not use `-W error`, but a different custom flag which writes a temporary ini file and load this with `-c`

Two more options:

 3. we could put a warning filter into `db.py` directly and catch it there manually for this one special case, dont see any negatives to this
 4. we could make use of that ENV variable you can set allegedly to suppress the warning


```
<stdin>:1: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```

**Comment by megies** [comment]
I think goin with `3.` should be fine

**Comment by trichter** [comment]
> I think goin with 3. should be fine

:+1: 

I guess the filter in pytest.ini is not needed anymore, but it does not hurt either.

**Pull request merged**
