### PR TITLE
Nordic files: full length longitudes and depth not being fully read

### PR DESCRIPTION
**Pull request by shicks-seismo**
Problems reading 3-figure depths and negative 3-figure longitudes.

### What does this PR do?
Fixes a couple of formatting issues when reading a NORDIC file

### Why was it initiated?  Any relevant Issues?
I found that depths >=100 km were not being correctly read. Also noticed an issue with the longitude read.

### PR Checklist
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Thanks for that @shicks-seismo - can you add a brief test with a negative longitude and a deep earthquake? Shows my NZ shallow-earthquake focus (and misreading of the indexes in the docs - failed to convert to starting indexing from zero I think).

**Comment by megies** [comment]
> can you add a brief test with a negative longitude and a deep earthquake?

Also add a short changelog entry, please. Thanks!

As a bug, this should go into `maintenance_1.1.x`, I'll change the base branch.

**Comment by megies** [comment]
@shicks-seismo can you please rebase your branch on `maintenance_1.1.x`? Thanks!

**Comment by krischer** [comment]
> Might be worth closing this PR?

indeed. Thanks @shicks-seismo for making us aware of this.

**Pull request closed without merging**
