### PR TITLE
docs: Fix merge seismograms and update seismometer correction tutorial (and maybe some more smaller things)

### PR DESCRIPTION
**Pull request by megies**
### What does this PR do?

Tries to fix some issues in docs

 - "merge seismogram" tutorial has some code ~~that's not working with newer matplotlib (`matplotlib.use("..."`)~~ that uses a non-GUI backend (what is used for docs building): get rid of that and also modernize the one tutorial snippet
 - some plots not showing up.. not sure why, maybe we have some fundamental issue with matplotlib backend choice or something??

### Why was it initiated?  Any relevant Issues?

see https://discourse.obspy.org/t/attributeerror-after-running-source-code-from-tutorial-merging-seismograms/1392/2

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the "build_docs" tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the "test_network" tag to this PR.
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [x] Add the "ready for review" tag when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by megies** [comment]
# 1.2.0 docs

Screenshot from 2022-04-05 15-33-29

---

# 1.3.0 docs

Screenshot from 2022-04-05 15-35-30

**Comment by megies** [comment]
@trichter for stuff like that it would be nice to have something cimilar to `no_ci` that switches of tests but can still build docs.. or is that by any chance already what `no_ci`+`build_docs` is doing?

**Review by trichter — APPROVED** [review]

**Comment by megies** [comment]
@trichter I'm still unsure why some plots do not show up, but maybe we should address that in a separate issue

**Comment by megies** [comment]
@trichter i think some of these images are simply never copied during the docs build? i couldn't find why e.g. in `waveform_plotting_tutorial.rst` only 2 out of 6 plots show up, i don't find error messages in the [docs build log](https://github.com/obspy/obspy/runs/5834447578?check_suite_focus=true), searching for `waveform_plotting_` i only find were the `.rst` is parsed and then at the end when it says `copying images` for 2/6 images from the corresponding `.py` files

**Comment by trichter** [comment]
I re-triggered the CI of your last push.

The doc of this branch at

https://docs.obspy.org/pr/fix_plot_tutorial/

was not correctly deployed due to an error in the compression.

Server error log:
```
ERROR:deploy_docs:2022-04-05 15:56:33 Unexpected error in run 2097209228
Traceback (most recent call last):
  File "/home/obspy/scripts/docs_deploybot/deploy_docs.py", line 143, in deploy
    state = deploy_artifact(run, **kw)
  File "/home/obspy/scripts/docs_deploybot/deploy_docs.py", line 96, in deploy_artifact
    tar.extractall(path)
  File "/home/obspy/anaconda3/envs/deploy_docs/lib/python3.10/tarfile.py", line 2040, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/home/obspy/anaconda3/envs/deploy_docs/lib/python3.10/tarfile.py", line 2081, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/home/obspy/anaconda3/envs/deploy_docs/lib/python3.10/tarfile.py", line 2154, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/obspy/anaconda3/envs/deploy_docs/lib/python3.10/tarfile.py", line 2203, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/home/obspy/anaconda3/envs/deploy_docs/lib/python3.10/tarfile.py", line 248, in copyfileobj
    buf = src.read(bufsize)
  File "/home/obspy/anaconda3/envs/deploy_docs/lib/python3.10/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/home/obspy/anaconda3/envs/deploy_docs/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/obspy/anaconda3/envs/deploy_docs/lib/python3.10/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
_lzma.LZMAError: Corrupt input data
```

**Comment by trichter** [comment]
I think the images are always missing when stream.plot is involved (except for `type='section'`).

**Comment by megies** [comment]
Worth checking out, could indeed be a reason

**Comment by megies** [comment]
> Just a guess: I saw that the `__del__` method is closing the figures when fig is not present in the kwargs. Maybe that could be the reason?

That's actually the problem, if I put `handle=True` in there to prevent `__del__` closing the figure it shows up alright.

Two ways to fix it..
 - put `handle=True` in every `Stream.plot(...)` call we have in docs
 - add something to the `if` clause in `WaveformPlotting.__del__` that recognizes we are in github actions and prevents closing the figure

Second option introduces some more magic, but it's future failsafe (when more plots get added to docs) and much less to change.

What's the best way to detect we are in gh-actions @trichter? Probably just look up some env variable?

**Comment by megies** [comment]
> What is the reasoning behind the `__del__` method?

Basically people running into problems doing lots of plots to file in loops not knowing to close those figures, as matplotlib does not garbage collect them, even if there are no references to a figure anymore so eventually the RAM runs full, see #512.

**Comment by megies** [comment]
I hope this patches up the issue now. I left some trial n error commits in there with a revert commit deliberately.. it might help explain the issue when somebody looks back at this later on

**Comment by megies** [comment]
https://docs.obspy.org/pr/fix_plot_tutorial/tutorial/code_snippets/waveform_plotting_tutorial.html

Looks like we got our plots in the docs back, so this is ready to merge

**Comment by megies** [comment]
Good to go now.

**Pull request merged**
