### PR TITLE
Win py3.11 wheels obspy 1.4.0

### PR DESCRIPTION
**Pull request by trichter**
**Do not merge**

I am trying to build the wheels for win3.11 obspy 1.4.0 in this PR. This could not be done due to missing lxml wheels when the release was originally created. See #3338 and https://github.com/obspy/obspy/pull/3205#issuecomment-1307316646.

What I have done:
```
git checkout master
git checkout -b this_branch
git reset --hard 1.4.0
git reset --soft master
git commit
```

I also hard-coded the version number in get_git_version and updated the wheel building workflow to build the windows wheel for py3.11. I also removed the test command in the wheel building workflow, because some tests are failing for obspy version 1.4.0 nowadays.

### CODE REVIEW

**Comment by trichter** [comment]
@ThomasLecocq Could you check the windows wheel for py3.11 in the [zip artifact](https://github.com/obspy/obspy/suites/14966814522/artifacts/853727544) of the run? We can upload it to pypi if it works for you.

**Comment by trichter** [comment]
Next time we should avoid this hassle and publish all wheels right away when tagging the release. If we are sure, we can, as in this PR, disable the tests in the wheel building workflow.

**Comment by ThomasLecocq** [comment]
Will do tomorrow morning! Thanks a bunch already!

**Comment by QuLogic** [comment]
Why are there >300 files changed?

**Comment by trichter** [comment]
> Why are there >300 files changed?

It is because I created a commit with the full diff between master and tag 1.4.0. Just to be able to open a PR in github for which cibuildwheel via github actions will build the missing wheel for ObsPy 1.4.0.

**Comment by megies** [comment]
Also.. we could just push [1.4.1](https://github.com/obspy/obspy/milestone/26) which is pretty much ready to go and then we can ignore missing some wheels for 1.4.0?

**Comment by trichter** [comment]
> What's the deal with this one?

@ThomasLecocq asked for the missing win wheel for 1.4.0. I created this PR to build the missing wheel.  The wheel is ready, it just needs to be uploaded to pypi.

> I guess you needed a clean release version so that wheel building gets kicked off?

No wheel building in this PR gets kicked due to the `test_wheels` tag, but indeed I needed a PR based on master (or maintanance). 

> Or how to proceed?

I think nothing needs to be changed in general. This branch can be deleted or archived when issue #3338 is closed. For the future: https://github.com/obspy/obspy/pull/3339#issuecomment-1672292834

> Also.. we could just push [1.4.1](https://github.com/obspy/obspy/milestone/26) which is pretty much ready to go and then we can ignore missing some wheels for 1.4.0?

That would be perfectly OK.

**Comment by trichter** [comment]
> > The wheel is ready, it just needs to be uploaded to pypi.
> 
> You mean manually using `twine`?

Exactly.

**Comment by megies** [comment]
Gotcha. @ThomasLecocq it's on testpypi if you wanna try it before I push to pypi?
https://test.pypi.org/project/obspy/#files

**Comment by ThomasLecocq** [comment]
Your test results have been reported and are available at: https://tests.obspy.org/135189/

**Comment by ThomasLecocq** [comment]
seems good, the 2F are linked to a new deprecation

>\obspy\core\trace.py:2174: DeprecationWarning: Importing hann from 'scipy.signal' is deprecated and will raise an error in SciPy 1.13.0. Please use 'scipy.signal.windows.hann' or the convenience function 'scipy.signal.get_window' instead.
    taper_sides = func(2 * wlen + 1, **kwargs)

**Comment by megies** [comment]
> seems good, the 2F are linked to a new deprecation

this is already fixed with #3329

**Comment by megies** [comment]
wheel is up on pypi

**Comment by trichter** [comment]
Thanks for uploading!

**Pull request closed without merging**
