### PR TITLE
Respect `method='full'` for `Stream.plot(type='section')`

### LINKED ISSUE #3375: `Stream.plot(type='section')` does not respect `method='full'`
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

When using the Stream plotting method with `type='section'`, no matter the `method` used the data are resampled if they exceed 10,000 samples, see here in the `__init__()` method for `WaveformPlotting`:
https://github.com/obspy/obspy/blob/00122ed909bf6a488ed25d279a83dbea10a6599a/obspy/imaging/waveform.py#L125-L129
and in `__sect_init_traces()`:
https://github.com/obspy/obspy/blob/00122ed909bf6a488ed25d279a83dbea10a6599a/obspy/imaging/waveform.py#L1235-L1239

It seems to me that the latter bit of code should be checking if `method='full'` and if so, setting `tmp_data = tr.data` — rather than resampling. Currently that kwarg is not checked. Therefore, as it stands, users have no way of fully plotting the data without resampling if they're using `type='section'`.

I'm happy to make a PR to address this.

### Code to Reproduce

_No response_

### Error Traceback

_No response_

### ObsPy Version?

1.4.0

### Operating System?

macOS (M1)

### Python Version?

3.11.5

### Installation Method?

conda

### PR DESCRIPTION
**Pull request by liamtoney**
### What does this PR do?

For section-type plots: Ensures that the full Trace is plotted when a user requests it to be (i.e., when specifying `method='full'`). Parallels the [logic implemented in the `WaveformPlotting.plot()` method](https://github.com/obspy/obspy/blob/maintenance_1.4.x/obspy/imaging/waveform.py#L392-L406).

### Why was it initiated?  Any relevant Issues?

Fixes #3375.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] While the PR is still work-in-progress, the `no_ci` label can be added to skip CI builds
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just add the `build_docs` tag to this PR.
      Docs will be served at [docs.obspy.org/pr/{branch_name}](https://docs.obspy.org/pr/) (do not use master branch).
      Please post a link to the relevant piece of documentation.
- [ ] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are covered via new tests.
- [ ] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .
- [ ] If the changes affect any plotting functions you have checked that the plots
      from all the CI builds look correct. Add the "upload_plots" tag so that plotting 
      outputs are attached as artifacts. 
- [ ] New modules, add the module to `CODEOWNERS` with your github handle
- [ ] Add the yellow `ready for review` label when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by liamtoney** [comment]
Demo:
```python
from obspy import read
import matplotlib.pyplot as plt
import numpy as np

# Read in example data
st = read()

# Pretend that the three components are actually traces
# from different stations at 10, 20, 30 km from source
for tr, distance in zip(st, [10 * 1000, 20 * 1000, 30 * 1000]):
    tr.stats.distance = distance  # [m]

# Artifically increase the number of points in each trace to exceed max_npts
# (this makes the resampling for 'fast' clear)
for tr in st:
    tr.data = np.tile(tr.data, 20)

# Plot record section
fig = plt.figure()
st.plot(fig=fig, type='section', orientation='horizontal', method='fast', alpha=1, color='red')
st.plot(fig=fig, type='section', orientation='horizontal', method='full', alpha=1)
fig.axes[0].set_xlim(5, 10)  # Zoom in to show effect of the different plotting methods
fig.show()
```
out

**Comment by liamtoney** [comment]
> seems like a nice fix! i think you may have to rebase to the current maintenance branch though

Sorry, I don't understand. The current maintenance branch is [`maintenance_1.4.x`](https://github.com/obspy/obspy/tree/maintenance_1.4.x), no?

**Comment by filefolder** [comment]
> > seems like a nice fix! i think you may have to rebase to the current maintenance branch though
> 
> Sorry, I don't understand. The current maintenance branch is [`maintenance_1.4.x`](https://github.com/obspy/obspy/tree/maintenance_1.4.x), no?

ahh you're right sorry! i have lost track of the passage of time between versions.

**Comment by liamtoney** [comment]
Hi folks, just checking if there is more feedback on this PR. Thanks.

**Review by filefolder — APPROVED** [review]
looks good to me and tested fine on my machine

**Comment by liamtoney** [comment]
> looks good to me and tested fine on my machine

Great! Looks like this is ready to be merged, then? I can't do that part :)

**Comment by megies** [comment]
sorry for the delay @liamtoney.. looks good to me, just two comments:

1. would be nice to have a minimal regression test, easy to do with just a few lines using e.g. `np.random.random_integers(-100, 100, 10010)` as a single Trace's data and then plotting it and checking the resulting `Line` object, something like `assert len(ax.lines[0].get_xdata()) == 10010` (to make sure point number is not reduced to `max_npts`.

2. I was wondering why the min-max plot was looking that off from the original data.. turns out it's doing something different completely from the min-max routine on normal wiggle plot. I think it might be good to refactor the `_plot_min_max` routine a little bit to factor out the calculation routine for x/y values and then use the same routine in the section plot.

Would be nice to still get 1. in here, but 2. could be something for a different PR / another time.

**Comment by liamtoney** [comment]
> 2\. I was wondering why the min-max plot was looking that off from the original data.. turns out it's doing something different completely from the min-max routine on normal wiggle plot. I think it might be good to refactor the `_plot_min_max` routine a little bit to factor out the calculation routine for x/y values and then use the same routine in the section plot.

Are you referring to the fact that the section plot resamples the data while the standard plot does the min/max? Maybe a separate PR for that?

**Comment by liamtoney** [comment]
> 1. would be nice to have a minimal regression test, easy to do with just a few lines using e.g. `np.random.random_integers(-100, 100, 10010)` as a single Trace's data and then plotting it and checking the resulting `Line` object, something like `assert len(ax.lines[0].get_xdata()) == 10010` (to make sure point number is not reduced to `max_npts`.

Nice test idea! I implemented that and am ready for re-review, I think.

**Comment by megies** [comment]
> Are you referring to the fact that the section plot resamples the data while the standard plot does the min/max? Maybe a separate PR for that?

Yes, I was assuming it was doing the same min-max thing we have for the regular wiggle plot and was confused why the line was overshooting in some points and stuff. And yes, definitely something for another time, if at all. It's not a big deal really.

**Review by megies — APPROVED** [review]
Thanks for the fix! :rocket:

**Pull request merged**
