### PR TITLE
CatchOutput manager makes tests crash on Windows Python 3.6

### PR DESCRIPTION
**Pull request by megies**
See https://github.com/obspy/obspy/issues/1561#issuecomment-282266027

```
py3.6 on Windows crashes on our CatchOutput implementation
```

### CODE REVIEW

**Comment by krischer** [comment]
Man - can we maybe get rid of the C-level catching? If its only for a couple of tests we could also modify the C sources. Otherwise let me know once you think you got it working and I'll test on OSX which is also problematic with these things.

**Comment by QuLogic** [comment]
IIRC, one of the problems on Python 3 is that `flush` does not necessarily flush the libc cache, which is mentioned in the test. Maybe adding a `libc.flush` somewhere will help fix it.

**Comment by barsch** [comment]
yeah I tried all kind of libc flushes libc.flush(c_stdout) as well as clib.flush(None) as shown in various recipies

here some recipies I tried:

http://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/
http://stackoverflow.com/questions/17942874/stdout-redirection-with-ctypes-and-python
https://github.com/Drekin/readline-hooks/blob/master/readline_hooks.py (various c level stream filepointer for windows)
https://github.com/pytest-dev/pytest/blob/master/_pytest/capture.py
https://github.com/behave/behave/blob/master/behave/capture.py
etc.

it may run for your test environment - but as soon as you start testing against all supported python versions on Windows it fails

**Comment by megies** [comment]
Rebased on current master and force-pushed to update CI results.

**Comment by barsch** [comment]
not working - we should just remove all C-level catching - makes our life much easier ...

**Comment by megies** [comment]
In any case we need to decide what to do with this PR in the next days to not hold up 1.1.0...

Minimal solution: Short-circuit/disable CatchOutput manager on Py36+Win?

**Comment by ThomasLecocq** [comment]
@barsch  It looks like the pytest guys also struggled and this https://github.com/pytest-dev/pytest/pull/2462 is their solution....

**Comment by ThomasLecocq** [comment]
@barsch : found that adding ``setbuf(stdout, NULL);`` to the ``decomp_6b_buffer`` routine solves the CatchOutput issue.

(modifying this too, of course):

```python
    def test_no_dat2_null_pointer(self):
        """
        Checks that null pointers are returned correctly by read83 function
        of read. Error "decomp_6b: Neither DAT2 or DAT1 found!" is on
        purpose.
        """
        filename = os.path.join(self.path,
                                'loc_RJOB20050831023349_first100_dos.z')
        fout = io.BytesIO()
        with open(filename, 'rb') as fin:
            lines = (l for l in fin if not l.startswith(b'DAT2'))
            fout.write(b"".join(lines))
        fout.seek(0)
        # with CatchOutput() as out:
        with CatchOutput() as out:
            self.assertRaises(GSEUtiError, libgse2.read, fout)
        # XXX: CatchOutput does not work on Py3k, skipping for now
        self.assertEqual(out.stdout,
                        b"decomp_6b: Neither DAT2 or DAT1 found!\n")
```

**Comment by barsch** [comment]
@ThomasLecocq will look into it - thanks for the link

**Comment by barsch** [comment]
the saga continues in #1854

**Comment by barsch** [comment]
@ThomasLecocq where exactly did u put ```setbuf(stdout, NULL);``` to ```decomp_6b_buffer```?

**Pull request closed without merging**
